### ISSUE TITLE
"The page you were looking for doesn't exist."

### ISSUE THREAD

**Issue by Azimoth** [huginn/huginn#2040]
Hi, 
I tried to install Huginn last night. On the way there I got stuck a few times (apparently the SQL user password cannot contain a "#", I figured).

When it came to "sudo bundle exec rake production:export" there were a few errors of "file not found", so I tried "sudo runsvdir /etc/service &" and manually entering the SQL information in config/database.yml .
After this did not help I called it night and went to bed.

This morning, I (for whatever reason) re-ran "sudo bundle exec rake production:export" and it did not produce any errors (no idea what changed).

Now the only problem left is, that when I go to https://FQDN/huginn I end up at a message "The page you were looking for doesn't exist.".

Automatic redirect from http to https works, this is not an nginx error, the ssl cert is ok, so I assume, that I'm acutally at the right page, but the content is not there. 
In /var/log/nginx/huginn_access.log it says:
127.0.0.1 - - [25/Jun/2017:11:40:51 +0200] "GET /huginn HTTP/1.0" 404 728 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"

I'm not sure, I did configure nginx correctly. As I only have a dyndns, I can only use one FQDN and several folders in the web root (from where I ln -s to /home/huginn/huginn). 

Do you have any idea how I might fix this?

The nginx config files look like this:

```
upstream huginn {
  server unix:/home/huginn/huginn/tmp/sockets/unicorn.socket fail_timeout=0;
}

server {
        listen 443 ssl http2;
        server_name FQDN 192.168.X.Y;
  
        #
        # Configure SSL
        #
        ssl on;

        < I SKIP SEVERAL LINES HERE THAT DON'T BELONG TO HUGINN >
      
        location /huginn {

		proxy_read_timeout      300;
		proxy_connect_timeout   300;
		proxy_redirect          off;

		proxy_set_header    Host                $http_host;
		proxy_set_header    X-Real-IP           $remote_addr;
		proxy_set_header    X-Forwarded-Ssl     on;
		proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
		proxy_set_header    X-Forwarded-Proto   $scheme;
                proxy_set_header    X-Frame-Options     "SAMEORIGIN";

		proxy_pass http://127.0.0.1:3000;
	}
}

```
and 

```
server {
  listen 127.0.0.1:3000;
  server_name 127.0.0.1;

  ## Individual nginx logs for this huginn vhost
  access_log  /var/log/nginx/huginn_access.log;
  error_log   /var/log/nginx/huginn_error.log;

  location / {
    ## Serve static files from defined root folder.
    ## @huginn is a named location for the upstream fallback, see below.
    try_files $uri $uri/index.html $uri.html @huginn;
  }

  ## If a file, which is not found in the root folder is requested,
  ## then the proxy passes the request to the upsteam (huginn unicorn).
  location @huginn {
    ## If you use HTTPS make sure you disable gzip compression
    ## to be safe against BREACH attack.
    gzip off;

    proxy_read_timeout      300;
    proxy_connect_timeout   300;
    proxy_redirect          off;

    proxy_set_header    Host                $http_host;
    proxy_set_header    X-Real-IP           $remote_addr;
    proxy_set_header    X-Forwarded-Ssl     on;
    proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_set_header    X-Forwarded-Proto   $scheme;
    proxy_set_header    X-Frame-Options     SAMEORIGIN;

    proxy_pass http://huginn;
  }

  ## Enable gzip compression as per rails guide:
  ## http://guides.rubyonrails.org/asset_pipeline.html#gzip-compression
  ## WARNING: If you are using relative urls remove the block below
  ## See config/application.rb under "Relative url support" for the list of
  ## other files that need to be changed for relative url support
  location ~ ^/(assets)/ {
    root /home/huginn/huginn/public;
    gzip_static on; # to serve pre-gzipped version
    expires max;
    add_header Cache-Control public;
  }

  error_page 502 /502.html;
}


```

**Comment by dsander** [comment]
Hi @Azimoth,

is Huginn the only application served by your nginx server? If that is the case I recommend using the [default nginx configurations](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#6-nginx). It looks like you are trying to serve Huginn from a subpath which we do not support, can you use a subdomain for Huginn?

**Comment by Azimoth** [comment]
No, I use Nginx as well for Nextcloud and other stuff. Also, I cannot use a subdomain because I only have a free dynamic DNS "as is", so I can have as many subpaths as I want, but cannot use subdomains. 

So basically, there's no way for this to work, even IF my nginx config is correct? Is this something that's supposed to be fixed/changed later on?

**Comment by dsander** [comment]
It is possible to serve rails applications from a [subdirectory](http://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root), you can try to set `RAILS_RELATIVE_URL_ROOT=/huginn` in you `.env.` and reexport the services. It might work, but I don't think anyone ever tested it.

What will work is using a second dynamic dns name for Huginn or creating a `CNAME` dns record on a domain which points to your dynamic dns name.

**Comment by Azimoth** [comment]
Well, somebody has to test it, so why not me? ;) 

Is "RAILS_RELATIVE_URL_ROOT=/huginn" supposed to be inserted in a certain part of .env?
It was not included in my file, so I simply inserted it underneath the "PORT=" entry.

After re-exporting "The page you were looking for doesn't exist." changed into a "502 Bad Gateway" error from nginx.

**Comment by dsander** [comment]
Hmm looks like the rails application does not handle the routes properly. Can you try to change [line 5 of config.ru](https://github.com/huginn/huginn/blob/master/config.ru#L5) to this and restart/rexport?
```ruby
map Huginn::Application.config.relative_url_root || "/" do
  run Huginn.application
end
```

**Comment by Azimoth** [comment]
After altering config.ru and re-exporting (and restarting nginx) "The page you were looking for doesn't exist." changed into a "502 Bad Gateway" error from nginx. For real, this time. ;)

**Comment by dsander** [comment]
Can you check the `production.log`? I guess my code snipped is producing some kind of exception.

**Comment by Azimoth** [comment]
I don't know what to look for, so I put /home/huginn/huginn/log/production.log on pastebin. Here we go:

https://pastebin.com/74NFupb9

**Comment by dsander** [comment]
Hmm I don't see any HTTP requests in there, did you try to access Huginn in the time frame the log captured?

**Comment by Azimoth** [comment]
I might have forgotten to do so after restarting. Another pastebin:

https://pastebin.com/XZrGRaK2

**Comment by dsander** [comment]
I had a typo in my snipped, does it work with that? (it should be `Huginn::Application` not `Huginn.application`)

```ruby
map Huginn::Application.config.relative_url_root || "/" do
  run Huginn::Application
end
```

After changing the code you need to restart again and give the application server a few dozen seconds to boot.

**Comment by Azimoth** [comment]
We have some progress. 
Adding that to config.ru lead to a loading page, ALTHOUGH it's layout is somehow flawed. No graphics are loaded and it looks like css (?) is not working. I could login using my admin account but logout leads back to "The page you were looking for doesn't exist."

Also, the list of "FATAL" errors got noticeably longer:

> I, [2017-06-28T07:01:22.795042 #11331]  INFO -- : [6a08c482-313e-48e6-a158-e1a800688307] Started GET "/huginn/assets/application-e6f4549e8791bed5333febcea95f824094f3f2a8bffda8496e1dfaceeae9824f.css" for 92.204.89.196 at 2017-06-28 07:01:22 -0700
> F, [2017-06-28T07:01:22.797271 #11331] FATAL -- : [6a08c482-313e-48e6-a158-e1a800688307]   
> F, [2017-06-28T07:01:22.797444 #11331] FATAL -- : [6a08c482-313e-48e6-a158-e1a800688307] ActionController::RoutingError (No route matches [GET] "/assets/application-e6f4549e8791bed5333febcea95f824094f3f2a8bffda8496e1dfaceeae9824f.css"):
> F, [2017-06-28T07:01:22.797577 #11331] FATAL -- : [6a08c482-313e-48e6-a158-e1a800688307]   
> F, [2017-06-28T07:01:22.797685 #11331] FATAL -- : [6a08c482-313e-48e6-a158-e1a800688307] config/initializers/silence_worker_status_logger.rb:3:in `call'
> I, [2017-06-28T07:01:22.798355 #11328]  INFO -- : [2ba5a69d-164d-410f-bcad-1f76e495d528] Started GET "/huginn/assets/spinner-arrows-f4cfc5bc84f34fa882bc9125cd8730bb4ea4844c0ac6fd981bae2de9bb33aebc.gif" for 92.204.89.196 at 2017-06-28 07:01:22 -0700
> F, [2017-06-28T07:01:22.801743 #11328] FATAL -- : [2ba5a69d-164d-410f-bcad-1f76e495d528]   
> F, [2017-06-28T07:01:22.801998 #11328] FATAL -- : [2ba5a69d-164d-410f-bcad-1f76e495d528] ActionController::RoutingError (No route matches [GET] "/assets/spinner-arrows-f4cfc5bc84f34fa882bc9125cd8730bb4ea4844c0ac6fd981bae2de9bb33aebc.gif"):
> F, [2017-06-28T07:01:22.802140 #11328] FATAL -- : [2ba5a69d-164d-410f-bcad-1f76e495d528]   
> F, [2017-06-28T07:01:22.802390 #11328] FATAL -- : [2ba5a69d-164d-410f-bcad-1f76e495d528] config/initializers/silence_worker_status_logger.rb:3:in `call'
> I, [2017-06-28T07:01:22.802478 #11331]  INFO -- : [b51f2af2-18ed-48d7-a8d8-d9e424c054f5] Started GET "/huginn/assets/odin-4aea0258f53748e9cc20b6ddd655824d8d1b26901015d43ad97c6d166bf88227.jpg" for 92.204.89.196 at 2017-06-28 07:01:22 -0700
> I, [2017-06-28T07:01:22.803223 #11325]  INFO -- : [af5cee02-f767-4940-a400-7e1d5e5d8a0e] Started GET "/huginn/assets/application-817343186571e423416ac05aafb637146900cff8b89a1897c4070bde1d2db75a.js" for 92.204.89.196 at 2017-06-28 07:01:22 -0700
> F, [2017-06-28T07:01:22.804656 #11331] FATAL -- : [b51f2af2-18ed-48d7-a8d8-d9e424c054f5]   
> F, [2017-06-28T07:01:22.804826 #11331] FATAL -- : [b51f2af2-18ed-48d7-a8d8-d9e424c054f5] ActionController::RoutingError (No route matches [GET] "/assets/odin-4aea0258f53748e9cc20b6ddd655824d8d1b26901015d43ad97c6d166bf88227.jpg"):
> F, [2017-06-28T07:01:22.804923 #11331] FATAL -- : [b51f2af2-18ed-48d7-a8d8-d9e424c054f5]   
> F, [2017-06-28T07:01:22.805031 #11331] FATAL -- : [b51f2af2-18ed-48d7-a8d8-d9e424c054f5] config/initializers/silence_worker_status_logger.rb:3:in `call'
> F, [2017-06-28T07:01:22.806990 #11325] FATAL -- : [af5cee02-f767-4940-a400-7e1d5e5d8a0e]   
> F, [2017-06-28T07:01:22.807372 #11325] FATAL -- : [af5cee02-f767-4940-a400-7e1d5e5d8a0e] ActionController::RoutingError (No route matches [GET] "/assets/application-817343186571e423416ac05aafb637146900cff8b89a1897c4070bde1d2db75a.js"):
> F, [2017-06-28T07:01:22.807558 #11325] FATAL -- : [af5cee02-f767-4940-a400-7e1d5e5d8a0e]   
> F, [2017-06-28T07:01:22.807730 #11325] FATAL -- : [af5cee02-f767-4940-a400-7e1d5e5d8a0e] config/initializers/silence_worker_status_logger.rb:3:in `call'
> I, [2017-06-28T07:01:22.995512 #11331]  INFO -- : [74cbc2d9-397c-4cc0-89e5-1e21ea4ae3a5] Started GET "/huginn/assets/odin-4aea0258f53748e9cc20b6ddd655824d8d1b26901015d43ad97c6d166bf88227.jpg" for 92.204.89.196 at 2017-06-28 07:01:22 -0700
> I, [2017-06-28T07:01:22.995552 #11325]  INFO -- : [cf2d57f4-0ac3-4946-aeb2-2d1fd446160c] Started GET "/huginn/assets/spinner-arrows-f4cfc5bc84f34fa882bc9125cd8730bb4ea4844c0ac6fd981bae2de9bb33aebc.gif" for 92.204.89.196 at 2017-06-28 07:01:22 -0700
> F, [2017-06-28T07:01:22.998710 #11331] FATAL -- : [74cbc2d9-397c-4cc0-89e5-1e21ea4ae3a5]   
> F, [2017-06-28T07:01:22.998972 #11331] FATAL -- : [74cbc2d9-397c-4cc0-89e5-1e21ea4ae3a5] ActionController::RoutingError (No route matches [GET] "/assets/odin-4aea0258f53748e9cc20b6ddd655824d8d1b26901015d43ad97c6d166bf88227.jpg"):
> F, [2017-06-28T07:01:22.999114 #11331] FATAL -- : [74cbc2d9-397c-4cc0-89e5-1e21ea4ae3a5]   
> F, [2017-06-28T07:01:22.999197 #11325] FATAL -- : [cf2d57f4-0ac3-4946-aeb2-2d1fd446160c]   
> F, [2017-06-28T07:01:22.999270 #11331] FATAL -- : [74cbc2d9-397c-4cc0-89e5-1e21ea4ae3a5] config/initializers/silence_worker_status_logger.rb:3:in `call'
> F, [2017-06-28T07:01:22.999382 #11325] FATAL -- : [cf2d57f4-0ac3-4946-aeb2-2d1fd446160c] ActionController::RoutingError (No route matches [GET] "/assets/spinner-arrows-f4cfc5bc84f34fa882bc9125cd8730bb4ea4844c0ac6fd981bae2de9bb33aebc.gif"):
> F, [2017-06-28T07:01:22.999563 #11325] FATAL -- : [cf2d57f4-0ac3-4946-aeb2-2d1fd446160c]   
> F, [2017-06-28T07:01:22.999717 #11325] FATAL -- : [cf2d57f4-0ac3-4946-aeb2-2d1fd446160c] config/initializers/silence_worker_status_logger.rb:3:in `call'
> I, [2017-06-28T07:01:30.724486 #11325]  INFO -- : [6b648fe6-e9ca-4665-accb-5375b9729ce3] Started GET "/huginn/users/sign_out" for 92.204.89.196 at 2017-06-28 07:01:30 -0700
> F, [2017-06-28T07:01:30.728022 #11325] FATAL -- : [6b648fe6-e9ca-4665-accb-5375b9729ce3]   
> F, [2017-06-28T07:01:30.728267 #11325] FATAL -- : [6b648fe6-e9ca-4665-accb-5375b9729ce3] ActionController::RoutingError (No route matches [GET] "/users/sign_out"):
> F, [2017-06-28T07:01:30.728414 #11325] FATAL -- : [6b648fe6-e9ca-4665-accb-5375b9729ce3]   
> F, [2017-06-28T07:01:30.728679 #11325] FATAL -- : [6b648fe6-e9ca-4665-accb-5375b9729ce3] config/initializers/silence_worker_status_logger.rb:3:in `call'
> I, [2017-06-28T07:01:35.328068 #11325]  INFO -- : [bd407457-f0c4-46dd-aa21-b1c106550cdd] Started GET "/huginn/users/sign_out" for 92.204.89.196 at 2017-06-28 07:01:35 -0700
> F, [2017-06-28T07:01:35.331501 #11325] FATAL -- : [bd407457-f0c4-46dd-aa21-b1c106550cdd]   
> F, [2017-06-28T07:01:35.331744 #11325] FATAL -- : [bd407457-f0c4-46dd-aa21-b1c106550cdd] ActionController::RoutingError (No route matches [GET] "/users/sign_out"):
> F, [2017-06-28T07:01:35.331891 #11325] FATAL -- : [bd407457-f0c4-46dd-aa21-b1c106550cdd]   
> F, [2017-06-28T07:01:35.332051 #11325] FATAL -- : [bd407457-f0c4-46dd-aa21-b1c106550cdd] config/initializers/silence_worker_status_logger.rb:3:in `call'

**Comment by dsander** [comment]
Yeah I just hit that brick wall with the ajax calls myself, can you revert the `config.ru` changes to the default, restart and modify your first nginx config?
```
change :
		proxy_pass http://127.0.0.1:3000;
to:
		proxy_pass http://127.0.0.1:3000/;
```
To my understanding this should remove the `/huginn` subdirectory when proxing the request to the Huginn nginx server.

If that works and the css still seems to be missing try [precompiling the assets](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#compile-assets) again.

**Comment by Azimoth** [comment]
Done. The start page now looks as expected, but clicking "login" leads to 404 (from nginx).

**Comment by Azimoth** [comment]
After my little database adventure everything remained as it was before (normally looking site, login and signup lead to nginx 404). BUT this time the production.log produces no more "FATAL" entries. 
Should I look for something else that might indicate the problem?

**Comment by dsander** [comment]
I don't know if it is possible. The 'correct' way to serve a Rails application using a sub directory would be that https://github.com/huginn/huginn/issues/2040#issuecomment-311666166, but that requires the modification of all AJAX calls we are doing because they always assume that Huginn is served via the root 'directory'. Adding support for that is not on my priority as it would also require some changes to the installation guides.

I think the simplest solution would be to use a DNS `CNAME` which points to your DynamicDNS hostname or to set up a second DynDNS host.

**Comment by atkinsj** [comment]
+1 on this. I almost had it working with an nginx config doing string replaces:
```
location /huginn {
                proxy_pass http://127.0.0.1:3000/;
                rewrite /huginn(.*) /$1  break;
                sub_filter_once off;
                sub_filter 'src="/'  'src="/huginn/';
                sub_filter 'href="/'  'href="/huginn/';
                sub_filter 'action="/'  'action="/huginn/';
                proxy_redirect    off;
        }
```

This causes it to render correctly but login fails, probably a CORS protection or something with the Location: headers being SNAFU.

**Comment by skaa** [comment]
I'm not very familiar with nginx, so the configuration may looks ugly or be suboptimal. My working config for `https://domain/huginn` location:
Root config:
```
upstream huginn {
  server unix:/home/huginn/huginn/tmp/sockets/unicorn.socket fail_timeout=0;
}

server {
  ...

  location @huginn {
    ## If you use HTTPS make sure you disable gzip compression
    ## to be safe against BREACH attack.
    gzip off;
    gzip_static off;

    proxy_read_timeout      300;
    proxy_connect_timeout   300;

    proxy_set_header    Host                $http_host;
    proxy_set_header    X-Real-IP           $remote_addr;
    proxy_set_header    X-Forwarded-Ssl     on;
    proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_set_header    X-Forwarded-Proto   $scheme;
    proxy_set_header    X-Frame-Options     SAMEORIGIN;
    proxy_set_header    Accept-Encoding     "";

    proxy_pass http://huginn;

    rewrite /huginn(.*) $1 break;
    sub_filter_once off;
    #sub_filter_types text/css text/javascript application/javascript;
    sub_filter 'src="/' 'src="/huginn/';
    sub_filter 'href="/' 'href="/huginn/';
    sub_filter 'action="/' 'action="/huginn/';
    sub_filter '?return=%2F' '?return=%2Fhuginn%2F';
    #sub_filter 'getJSON("/' 'getJSON("/huginn/';
    #sub_filter 'url("/' 'url("/huginn/';
    #sub_filter 'url(\"/' 'url(\"/huginn/';
    #sub_filter 'url(\'/' 'url(\'/huginn/';
    #sub_filter 'url(/' 'url(/huginn/';

    proxy_redirect ~^(http?s://.*?)(/.*)$ $1/huginn$2;
  }

  location ^~ /huginn {
    include /etc/nginx/sites-available/site-huginn;
    gzip off;
    gzip_static off;
  }
}
```

Included config:
```
alias /home/huginn/huginn/public;

location /huginn {
    try_files $uri $uri/index.html $uri.html @huginn;

    sub_filter_once off;
    sub_filter_types text/css text/javascript application/javascript;
    sub_filter 'getJSON("/' 'getJSON("/huginn/';
    sub_filter '.ajax("/' '.ajax("/huginn/';
    sub_filter '.post("/' '.post("/huginn/';
    sub_filter '.get("/' '.get("/huginn/';
    #sub_filter 'forPathsMatching:/^agents/' 'forPathsMatching:/^huginn/agents/';
    sub_filter 'url("/' 'url("/huginn/';
    sub_filter 'url(/' 'url(/huginn/';
    sub_filter '_IMG="/' '_IMG="/huginn/';
    #proxy_redirect    off;
}

location ~ /huginn/assets/\.(css|js|woff|svg|gif|jpg)$ {
    gzip_static off;
    try_files $uri /assets/$1 =404;
    expires max;
    add_header Cache-Control public;
}
```
