### ISSUE TITLE
Email Error

### ISSUE THREAD

**Issue by dopefishh** [huginn/huginn#2094]
I've configured the email variables in the `.env` file and added an email agent to my huginn instance.
The SMTP server settings are correct but no email is sent and the mail server logs don't report any activity. My experience with Ruby is limited so to pinpoint the problem I have a couple of questions.
I have tried accessing the SMTP server locally via `localhost` and via the correct domain name.

- Is there any way of testing the configuration for the ruby SMTP client directly? 
- Might it be a problem that the mailserver is on the same machine?
- Is it possible to just use the sendmail instance on the server to send email instead of hassling with SMTP.

The following errors are being logged:
```
/usr/local/lib/ruby/2.3.0/net/smtp.rb:542:in `initialize'
/usr/local/lib/ruby/2.3.0/net/smtp.rb:542:in `open'
/usr/local/lib/ruby/2.3.0/net/smtp.rb:542:in `tcp_socket'
/usr/local/lib/ruby/2.3.0/net/smtp.rb:552:in `block in do_start'
/usr/local/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/usr/local/lib/ruby/2.3.0/net/smtp.rb:551:in `do_start'
/usr/local/lib/ruby/2.3.0/net/smtp.rb:521:in `start'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/mail-2.6.5/lib/mail/network/delivery_methods/smtp.rb:113:in `deliver!'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/mail-2.6.5/lib/mail/message.rb:2149:in `do_delivery'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/mail-2.6.5/lib/mail/message.rb:237:in `block in deliver'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:558:in `block in deliver_mail'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:556:in `deliver_mail'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/mail-2.6.5/lib/mail/message.rb:237:in `deliver'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionmailer-5.1.1/lib/action_mailer/message_delivery.rb:96:in `block in deliver_now'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionmailer-5.1.1/lib/action_mailer/rescuable.rb:15:in `handle_exceptions'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/actionmailer-5.1.1/lib/action_mailer/message_delivery.rb:95:in `deliver_now'
/home/huginn/huginn/app/models/agents/email_digest_agent.rb:61:in `block in check'
/home/huginn/huginn/app/models/agents/email_digest_agent.rb:52:in `each'
/home/huginn/huginn/app/models/agents/email_digest_agent.rb:52:in `check'
/home/huginn/huginn/app/jobs/agent_check_job.rb:7:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/execution.rb:37:in `block in perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/i18n-0.8.1/lib/i18n.rb:257:in `with_locale'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `block in tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/execution.rb:33:in `perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/execution.rb:22:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/reloader.rb:68:in `block in wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/reloader.rb:67:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/execution.rb:20:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/gems/activejob-5.1.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:36:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/backend/base.rb:78:in `invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/local/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/local/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:230:in `block in run'
/usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:229:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:213:in `block in work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:212:in `times'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:212:in `work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:172:in `loop'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:172:in `block in start'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:79:in `block in add'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.3.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:171:in `start'
/home/huginn/huginn/lib/delayed_job_worker.rb:6:in `run'
/home/huginn/huginn/app/concerns/long_runnable.rb:71:in `block in run!'
```

**Comment by dsander** [comment]
Hi @dopefishh,

at the moment Huginn only supports sending mails via SMTP. Can you check the logs again? Your backtrace is missing the actual exception description you should find it in before the first line of the backtrace. It looks like that either the ip/host or port is mis-configured.

**Comment by dopefishh** [comment]
Thanks for the hints @dsander, The `/home/huginn/huginn/log/production-*.log` files show no more errors. After the `block in run!` line it shows:
```E, [2017-08-23T04:12:02.931840 #16504] ERROR -- : 2017-08-23T04:12:02-0700: [Worker(host:helheim pid:16504)] Job ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper (id=28188) (queue=default) FAILED (1 prior attempts) with Net::OpenTimeout: execution expired```

My settings are:
```
SMTP_DOMAIN=myactual.domain
SMTP_USER_NAME=huginn@myactual.domain
SMTP_PASSWORD=xxxxxxxxxxxxxxxxx
SMTP_SERVER=myactual.domain
SMTP_PORT=587
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
SEND_EMAIL_IN_DEVELOPMENT=false
EMAIL_FROM_ADDRESS=huginn@myactual.domain
```

If I do a `nc myactual.domain` I get the following messages:
```
$ nc myactual.domain 587
220 helheim.myactual.domain ESMTP Postfix (Debian/GNU)
HELO myactual.domain
250 helheim.myactual.domain
STARTTLS
220 2.0.0 Ready to start TLS
```

Sending `EHLO myactual.domain` gives this:
```
250-helheim.colo.transip.net
250-PIPELINING
250-SIZE 10240000
250-VRFY
250-ETRN
250-STARTTLS
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
```

So the SMTP server is reachable via that hostname and port. And it's configured to do STARTTLS.

When I start a starttls session:
```
$ openssl s_client -connect myactual.domain:587 -starttls smtp
Bunch of tls stuff.
EHLO myactual.domain
250-helheim.myactual.domain
250-PIPELINING
250-SIZE 10240000
250-VRFY
250-ETRN
250-AUTH PLAIN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 DSN
```

ps. helheim is the hostname of the server itself

**Comment by dopefishh** [comment]
Problem solved!
The irony, I forgot to export after changing the env file...

**Comment by dsander** [comment]
Ah! Glad to hear it works now, can we close the issue?

**Comment by WangQiru** [comment]
emmm... I ran into the same issue but I run huginn in docker so the env should be automatically exported.
```
-e SMTP_DOMAIN=domain.com \
-e SMTP_USER_NAME=huginn@domain.com \
-e SMTP_PASSWORD=password \
-e SMTP_SERVER=smtp.domain.com \
-e SMTP_PORT=587 \
-e SMTP_AUTHENTICATION=plain \
-e SMTP_ENABLE_STARTTLS_AUTO=true \
-e EMAIL_FROM_ADDRESS=huginn@domain.com \
```

I also tried with gmail and zoho, both produced the same log
```
Exception during receive. execution expired: /usr/lib/ruby/2.4.0/net/smtp.rb:539:in `initialize'
```

Any idea? @dsander @cantino
