### ISSUE TITLE
Halo man,I need some help!

### ISSUE THREAD

**Issue by kejour** [huginn/huginn#2096]
while i make a Post_agent,i got a error.
It seems in the ruby?I never use ruby,so i need some help!😢
by the way, i use the docker for mac,so,i  don't know where to find .env file(the first time for docker and ruby...Zzz)
Here are the error:

> Exception during check. request timed out: /app/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/adapters/faraday.rb:92:in `block in request'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/request/callbacks.rb:129:in `block in execute_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/request/callbacks.rb:128:in `map'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/request/callbacks.rb:128:in `execute_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/request/operations.rb:35:in `finish'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/easy_factory.rb:105:in `block in set_callback'
/app/vendor/bundle/ruby/2.4.0/gems/ethon-0.7.1/lib/ethon/easy/response_callbacks.rb:65:in `block in complete'
/app/vendor/bundle/ruby/2.4.0/gems/ethon-0.7.1/lib/ethon/easy/response_callbacks.rb:65:in `each'
/app/vendor/bundle/ruby/2.4.0/gems/ethon-0.7.1/lib/ethon/easy/response_callbacks.rb:65:in `complete'
/app/vendor/bundle/ruby/2.4.0/gems/ethon-0.7.1/lib/ethon/easy/operations.rb:25:in `perform'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/request/operations.rb:16:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/request/cacheable.rb:18:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/request/block_connection.rb:31:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/request/stubbable.rb:23:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/request/before.rb:26:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/adapters/faraday.rb:68:in `perform_request'
/app/vendor/bundle/ruby/2.4.0/gems/typhoeus-0.6.9/lib/typhoeus/adapters/faraday.rb:58:in `call'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/faraday_middleware-59088da02940/lib/faraday_middleware/gzip.rb:24:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.1/lib/faraday/request/url_encoded.rb:15:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.1/lib/faraday/request/multipart.rb:15:in `call'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/faraday_middleware-59088da02940/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/faraday_middleware-59088da02940/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
/app/app/concerns/web_request_concern.rb:26:in `call'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
/app/app/models/agents/post_agent.rb:218:in `handle'
/app/app/models/agents/post_agent.rb:156:in `check'
/app/app/jobs/agent_check_job.rb:7:in `perform'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:37:in `block in perform_now'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/i18n-0.8.1/lib/i18n.rb:257:in `with_locale'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `block in tag_logger'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `tag_logger'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:33:in `perform_now'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:22:in `block in execute'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/reloader.rb:68:in `block in wrap'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/reloader.rb:67:in `wrap'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:20:in `execute'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:36:in `perform'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/backend/base.rb:78:in `invoke_job'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:230:in `block in run'
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:229:in `run'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:213:in `block in work_off'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:212:in `times'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:212:in `work_off'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:172:in `loop'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:172:in `block in start'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle

**Comment by dsander** [comment]
Hi @kejour,

the error means that the request timed out, i.e. it took too long to finish. It could either be caused by a slow website or a network issue.

You can pass any option of the `.env` file either as [environment variable](https://docs.docker.com/engine/reference/run/#env-environment-variables) or use the `--env-file` flag to pass the variables from an external `.env` file.
