### ISSUE TITLE
Error while trying to load gem 'coffee-rails'

### ISSUE THREAD

**Issue by TamanShud** [huginn/huginn#2158]
Consistently seeing this error during rake secret token generation:

Bundler::GemRequireError: There was an error while trying to load the gem 'coffee-rails'.
Gem Load Error is: wrong argument type Class (expected Module)
Backtrace for gem load error is:
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:23:in `include'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:23:in `block (2 levels) in <top (required)>'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:22:in `class_eval'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:22:in `block in <top (required)>'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:21:in `each'
/usr/lib/ruby/vendor_ruby/v8/conversion.rb:21:in `<top (required)>'
/var/lib/gems/2.3.0/gems/therubyracer-0.12.3/lib/v8.rb:22:in `require'
/var/lib/gems/2.3.0/gems/therubyracer-0.12.3/lib/v8.rb:22:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/execjs/ruby_racer_runtime.rb:108:in `require'
/usr/lib/ruby/vendor_ruby/execjs/ruby_racer_runtime.rb:108:in `available?'
/usr/lib/ruby/vendor_ruby/execjs/runtimes.rb:53:in `each'
/usr/lib/ruby/vendor_ruby/execjs/runtimes.rb:53:in `find'
/usr/lib/ruby/vendor_ruby/execjs/runtimes.rb:53:in `best_available'
/usr/lib/ruby/vendor_ruby/execjs/runtimes.rb:47:in `autodetect'
/usr/lib/ruby/vendor_ruby/execjs.rb:5:in `<module:ExecJS>'
/usr/lib/ruby/vendor_ruby/execjs.rb:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `require'
/var/lib/gems/2.3.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `require'
/var/lib/gems/2.3.0/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/coffee-rails-4.2.1/lib/coffee-rails.rb:1:in `require'
/var/lib/gems/2.3.0/gems/coffee-rails-4.2.1/lib/coffee-rails.rb:1:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:82:in `require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:82:in `block (2 levels) in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:77:in `each'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:77:in `block in require'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:66:in `each'
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:66:in `require'
/usr/lib/ruby/vendor_ruby/bundler.rb:108:in `require'
/opt/huginn/config/application.rb:7:in `<top (required)>'
/opt/huginn/Rakefile:5:in `require_relative'
/opt/huginn/Rakefile:5:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:687:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:96:in `block in load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:178:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:95:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:79:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:178:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:77:in `run'
/var/lib/gems/2.3.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:22:in `load'
/usr/local/bin/rake:22:in `<main>'
Bundler Error Backtrace:
/opt/huginn/config/application.rb:7:in `<top (required)>'
/opt/huginn/Rakefile:5:in `require_relative'
/opt/huginn/Rakefile:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
TypeError: wrong argument type Class (expected Module)
/var/lib/gems/2.3.0/gems/therubyracer-0.12.3/lib/v8.rb:22:in `require'
/var/lib/gems/2.3.0/gems/therubyracer-0.12.3/lib/v8.rb:22:in `<top (required)>'
/var/lib/gems/2.3.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `require'
/var/lib/gems/2.3.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `require'
/var/lib/gems/2.3.0/gems/coffee-script-2.4.1/lib/coffee-script.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/coffee-rails-4.2.1/lib/coffee-rails.rb:1:in `require'
/var/lib/gems/2.3.0/gems/coffee-rails-4.2.1/lib/coffee-rails.rb:1:in `<top (required)>'
/opt/huginn/config/application.rb:7:in `<top (required)>'
/opt/huginn/Rakefile:5:in `require_relative'
/opt/huginn/Rakefile:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by dsander** [comment]
Hi @TamanShud,

did you follow the [manual installation guide](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md) to install Huginn? 
The error suggests that you need to run [bundle install](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#install-gems) first.

**Comment by TamanShud** [comment]
I did. This is post the pre-requisite dependencies and post issuing the bundle install instruction.

**Comment by dsander** [comment]
I see, did you try running it as the huginn user?
```
sudo -u huginn -H bundle exec rake secret
```

**Comment by TamanShud** [comment]
I did not. I wasn't aware based on the README or instructions a user was built. If a user needs to be created might I recommend you include this in the README?

**Comment by dsander** [comment]
I am not sure that I follow. Didn't you say you followed the manual installation guide? We do have instructions there that create a user.

If you followed the [local installation](https://github.com/huginn/huginn#local-installation) from the README you still need to run `bundle` (or `bundle install` which does the same) to install the ruby gem dependencies.

**Comment by TamanShud** [comment]
I followed these instructions from the [Novice Setup Guide](https://github.com/huginn/huginn/wiki/Novice-setup-guide). Then i went to the [Local Installation](https://github.com/huginn/huginn#local-installation) to continue and where it ceases to function is in the actual .env.example file where it recommends running rake secret to generate a new token. e.g.
"# Replace the following with the output from "rake secret"
APP_SECRET_TOKEN=REPLACE_ME_NOW!

**Comment by dsander** [comment]
Hmm, does it work when you run `bundle exec rake secret`? If that does not help you can try installing nodejs that should prevent `execjs` from loading `therubyracer` which is causing the exception.
