### ISSUE TITLE
bundle install issues on Ubuntu 17

### ISSUE THREAD

**Issue by AmericanGeezus** [huginn/huginn#2191]
I am running into this issue while trying to follow the Install Guide.

root@Huginn:/home/huginn/huginn# sudo -u huginn -H bundle install --deployment --without development test
Fetching gem metadata from https://rubygems.org/......
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/dsl.rb:586:in `parse_line_number_from_description': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/dsl.rb:552:in `to_s'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:17:in `to_s'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:17:in `message'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:17:in `log_error'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:126:in `rescue in with_friendly_errors'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
        from /usr/local/bin/bundle:23:in `load'
        from /usr/local/bin/bundle:23:in `<main>'

I cant tell if it is actually something wrong with the Huginn process or if I need to be looking somewhere else.

**Comment by AmericanGeezus** [comment]
Fix found in issue #1785 worked for me.

**Comment by AmericanGeezus** [comment]
Fix found in issue #1785 worked for me.
