### ISSUE TITLE
SMTP email agent exception during receive. Execution expired.

### ISSUE THREAD

**Issue by WangQiru** [huginn/huginn#2218]
I run huginn in docker but my email never works.
```
-e SMTP_DOMAIN=domain.com \
-e SMTP_USER_NAME=huginn@domain.com \
-e SMTP_PASSWORD=password \
-e SMTP_SERVER=smtp.gmail.com \
-e SMTP_PORT=587 \
-e SMTP_AUTHENTICATION=plain \
-e SMTP_ENABLE_STARTTLS_AUTO=true \
-e EMAIL_FROM_ADDRESS=huginn@domain.com \
```

I also tried with gmail (465 with login and 587 with plain) and zoho, both produced the same log
```
Exception during receive. execution expired: /usr/lib/ruby/2.4.0/net/smtp.rb:539:in `initialize'
/usr/lib/ruby/2.4.0/net/smtp.rb:539:in `open'
/usr/lib/ruby/2.4.0/net/smtp.rb:539:in `tcp_socket'
/usr/lib/ruby/2.4.0/net/smtp.rb:549:in `block in do_start'
/usr/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/usr/lib/ruby/2.4.0/net/smtp.rb:548:in `do_start'
/usr/lib/ruby/2.4.0/net/smtp.rb:518:in `start'
/app/vendor/bundle/ruby/2.4.0/gems/mail-2.6.5/lib/mail/network/delivery_methods/smtp.rb:113:in `deliver!'
/app/vendor/bundle/ruby/2.4.0/gems/mail-2.6.5/lib/mail/message.rb:2149:in `do_delivery'
/app/vendor/bundle/ruby/2.4.0/gems/mail-2.6.5/lib/mail/message.rb:237:in `block in deliver'
/app/vendor/bundle/ruby/2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:558:in `block in deliver_mail'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
/app/vendor/bundle/ruby/2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:556:in `deliver_mail'
/app/vendor/bundle/ruby/2.4.0/gems/mail-2.6.5/lib/mail/message.rb:237:in `deliver'
/app/vendor/bundle/ruby/2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/message_delivery.rb:96:in `block in deliver_now'
/app/vendor/bundle/ruby/2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/rescuable.rb:15:in `handle_exceptions'
/app/vendor/bundle/ruby/2.4.0/gems/actionmailer-5.1.1/lib/action_mailer/message_delivery.rb:95:in `deliver_now'
/app/app/models/agents/email_agent.rb:57:in `block (2 levels) in receive'
/app/app/models/agents/email_agent.rb:47:in `each'
/app/app/models/agents/email_agent.rb:47:in `block in receive'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.1/lib/active_record/relation/delegation.rb:41:in `each'
/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.1/lib/active_record/relation/delegation.rb:41:in `each'
/app/app/models/agents/email_agent.rb:46:in `receive'
/app/app/jobs/agent_receive_job.rb:8:in `perform'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:37:in `block in perform_now'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/i18n-0.8.1/lib/i18n.rb:257:in `with_locale'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `block in tag_logger'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `tag_logger'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:33:in `perform_now'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:22:in `block in execute'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/reloader.rb:68:in `block in wrap'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/reloader.rb:67:in `wrap'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/execution.rb:20:in `execute'
/app/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:36:in `perform'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/backend/base.rb:78:in `invoke_job'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:230:in `block in run'
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:229:in `run'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:213:in `block in work_off'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:212:in `times'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:212:in `work_off'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:172:in `loop'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:172:in `block in start'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:79:in `block in add'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.4.0/bundler/gems/delayed_job-ec16c569ff0a/lib/delayed/worker.rb:171:in `start'
/app/lib/delayed_job_worker.rb:6:in `run'
/app/app/concerns/long_runnable.rb:71:in `block in run!'
```

**Comment by dsander** [comment]
That sounds like the connection from your server to google is either blocked or too slow. You also need to enable access for less secure apps for your GMail account. https://www.google.com/settings/security/lesssecureapps

**Comment by WangQiru** [comment]
@dsander My server can access google and zoho smtp server perfectly.

For gmail, I'm using an application-specific password since my google account has 2-step verification enabled. 
`
This setting is not available for accounts with 2-Step Verification enabled. Such accounts require an application-specific password for less secure apps access.
`

For zoho I used username/password as normal.

**Comment by dsander** [comment]
Can you try opening a connection to the gmail smtp server from your server?

You should see output similar to this one:

```
$ telnet smtp.gmail.com 587
Trying 64.233.167.108...
Connected to gmail-smtp-msa.l.google.com.
Escape character is '^]'.
220 smtp.gmail.com ESMTP 5sm12472975wre.35 - gsmtp
```

Entering `QUIT` will then close the connection again.

**Comment by QiruWang** [comment]
![9ed3809c-9a9c-4682-b90a-c856161cdf38](https://user-images.githubusercontent.com/5896343/36169814-3d80e850-10f5-11e8-9c64-649c46d47ab4.jpeg)
It looks good to me.

**Comment by dsander** [comment]
It does, but it does not explain why the connection is not working from your Huginn container. Other outbound connection like HTTP request work from Huginn?

**Comment by WangQiru** [comment]
Yes everything works as normal, I have 10+ `websiteagent` running with both POST and GET to internal and external addresses.

**Comment by dsander** [comment]
I can't tell you why this is happening on your machine. I started the docker container like this:

```
docker run -it -p 3000:3000 -e SMTP_DOMAIN=domain.com \
                                                -e SMTP_USER_NAME=huginn@domain.com \
                                                -e SMTP_PASSWORD=password \
                                                -e SMTP_SERVER=smtp.gmail.com \
                                                -e SMTP_PORT=587 \
                                                -e SMTP_AUTHENTICATION=plain \
                                                -e SMTP_ENABLE_STARTTLS_AUTO=true \
                                                -e EMAIL_FROM_ADDRESS=huginn@domain.com \
                                                huginn/huginn
```
And get the expected exception about username and password mismatch.
```
        535-5.7.8 Username and Password not accepted. Learn more at

/usr/lib/ruby/2.4.0/net/smtp.rb:981:in `check_auth_response'
/usr/lib/ruby/2.4.0/net/smtp.rb:736:in `auth_plain'
/usr/lib/ruby/2.4.0/net/smtp.rb:728:in `authenticate'
/usr/lib/ruby/2.4.0/net/smtp.rb:565:in `do_start'
/usr/lib/ruby/2.4.0/net/smtp.rb:518:in `start'
```

**Comment by StefanHos** [comment]
Any update here, please? I have the same error on my localhost:


```
Exception during check. 535-5.7.8 Username and Password not accepted. Learn more at : /usr/lib/ruby/2.5.0/net/smtp.rb:981:in `check_auth_response' /usr/lib/ruby/2.5.0/net/smtp.rb:736:in `auth_plain... | <1m ago |  
-- | -- | --
```

Tried with Mailgun SMTP.
note: lost password huginn functionality works correctly.

Thank you.

**Comment by dsander** [comment]
> `` Exception during check. 535-5.7.8 Username and Password not accepted. Learn more at : /usr/lib/ruby/2.5.0/net/smtp.rb:981:in `check_auth_response' /usr/lib/ruby/2.5.0/net/smtp.rb:736:in `auth_plain... | <1m ago |   ``

That just means that the configuration is wrong.



>  note: lost password huginn functionality works correctly.

You are getting an error when sending emails from an Agent but the reset password emails are send out without issues?

**Comment by StefanHos** [comment]
@dsander  exactly. Reset password email works without issues. Just Agent has trouble.

**Comment by dsander** [comment]
@StefanHos Please ensure that you are using the same environment configuration for the application server and the background processes. The only way I can imagine this happening is if the configuration is different for those two processes.

**Comment by mmalind** [comment]
> Please ensure that you are using the same environment configuration for the application server and the background processes. The only way I can imagine this happening is if the configuration is different for those two processes.

@dsander I am having issues with this also, but in my case i cannot send lost password either. What is the meaning of "configuration for the application server and the background processes." 

How do i check that? I am new to using docker and Synology and have tried different smtp servers and settings to no avail.

Everything else seems to be running well but keep getting the same log:
[00:00:00] INFO -- : Dry Run started
[00:00:00] ERROR -- : Error sending mail to xx@xx.com with event : 535-5.7.8 Username and Password not accepted. Learn more at

[00:00:00] INFO -- : Dry Run failed
[00:00:00] ERROR -- : Exception during dry-run. 535-5.7.8 Username and Password not accepted. Learn more at
: /usr/lib/ruby/2.5.0/net/smtp.rb:981:in `check_auth_response'
/usr/lib/ruby/2.5.0/net/smtp.rb:736:in `auth_plain'
/usr/lib/ruby/2.5.0/net/smtp.rb:728:in `authenticate'
/usr/lib/ruby/2.5.0/net/smtp.rb:565:in `do_start'
/usr/lib/ruby/2.5.0/net/smtp.rb:518:in `start'
 
Best regards

**Comment by dsander** [comment]
@mmalind That error reads to me like the configuration is just not correct. Huginn wasn't able to authenticate with your SMTP server using the configuration you provided.

**Comment by starsareintherose** [comment]
I meet a similar problem, see here. https://github.com/huginn/huginn/issues/2953

**Comment by AlfHou** [comment]
I'm experiencing the same problem 
```
Exception during receive. 535-5.7.8 Username and Password not accepted. Learn more at
: /usr/lib/ruby/2.6.0/net/smtp.rb:981:in `check_auth_response'
/usr/lib/ruby/2.6.0/net/smtp.rb:736:in `auth_plain'
/usr/lib/ruby/2.6.0/net/smtp.rb:728:in `authenticate'
/usr/lib/ruby/2.6.0/net/smtp.rb:565:in `do_start'
/usr/lib/ruby/2.6.0/net/smtp.rb:518:in `start'
/app/vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
...
```
What is weird is that it works as expected when I dry run. 
```
[00:00:00] INFO -- : Dry Run started
[00:00:01] INFO -- : Sent mail to <redacted> with event 
[00:00:01] INFO -- : Dry Run finished
```
