### ISSUE TITLE
huginn background job stuck and  no events output

### ISSUE THREAD

**Issue by poonjh** [huginn/huginn#2242]
After the job runs 1 or 2 days, thousands of background jobs stuck in running status no events output.

What I tried:
On OS: Linux Jessie
1, Tried both thread or non-thread version, same issue
2, Remove all jobs and restart the server,  after run 1 or 2 days, get the same issue again
3, Re-install OS / huginn, after running 1 or 2 days, get the same issue again 
On OS: Linux Stretch
4,  Re-install OS, run the docker version yesterday, now I get the same issue again.  

Now I don't know what to do next, no solution.   I'm new to Linux, anyone can help take a look?  I'm Ok to provide the Linux Root Password.     Big thanks...

**Comment by virtadpt** [comment]
How many Website Agents do you have running?

What's the DNS configuration of the box?

**Comment by poonjh** [comment]
Two website agent
My VPS config:   CPU：2 CPUs   Memory：2048 M  Harddisk：15 G

**Comment by dsander** [comment]
Hi @poonjh,

do you have any log output from the time the Agent processing locked up?

I'd recommend giving the separate processes another try, I can not remember if we ever got a bug report about them causing issues. Change your `Procfile` to this:

```
web: bundle exec unicorn -c config/unicorn.rb
agent_runner: bundle exec rails runner bin/agent_runner.rb
dj: bundle exec script/delayed_job run
```

and re-export the services: `sudo bundle exec rake production:export`

**Comment by se7cn** [comment]
这个问题我查阅了所有相关的问题
没有得到答案，没有人能找到原因，也没有解决方法。

但是可能性是：timeout和Python的某些原因导致

**Comment by poonjh** [comment]
Thank you @dsander @se7cn   I'll try to re-install on debian 9 and try again...  

@se7cn  如果重启下服务器， 又能工作一阵子，然后过2天又不行。 找不到方法。。。:(

**Comment by poonjh** [comment]
Did anyone install on Debian 9(stretch)?   When install, get the following error at these two steps:


root@XS1419898:/home/huginn/huginn# sudo -u huginn -H bundle install --deployment --without development test
Fetching gem metadata from https://rubygems.org/......
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/dsl.rb:586:in `parse_line_number_from_description': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/dsl.rb:552:in `to_s'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:17:in `to_s'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:17:in `message'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:17:in `log_error'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:126:in `rescue in with_friendly_errors'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
        from /usr/local/bin/bundle:23:in `load'
        from /usr/local/bin/bundle:23:in `<main>'


root@XS1419898:/home/huginn/huginn# sudo -u huginn -H bundle exec rake db:create RAILS_ENV=production
Could not find rake-12.0.0 in any of the sources
Run `bundle install` to install missing gems.

**Comment by poonjh** [comment]
@se7cn 你在debian 9上装过吗？  解决不了，看来用不了， 不知道是否有其它替代方案， 我只是用来订阅、合并、去重RSS

**Comment by dsander** [comment]
@poonjh Check your locale settings, `LANG` needs to be some unicode variant like `LANG=en_US.UTF-8`.

**Comment by se7cn** [comment]
@poonjh 都试过，之前有人反馈尝试了更换数据库，但是仍然无法说明问题出在哪里了
最后我放弃了
给你个解决思路

1. 如何发现huginn不工作了？ 你发现rss不更新了对吧
2. 那么设定一个定时任务去检查 你的rss，检查某个特定的值，做比较
3. 当满足某种条件，就判定为  huginn 挂了。 自动重启

我做了类似的处理去监控状态，每10分钟保存一次时间，然后再比对时间是不是超出10分钟。如果超出了。意味着huggin挂了，自动重启。 后来我查看了重启日志。
仍然是不规律的重启， 一天两三次，两三天一次。不过至少不用担心卡住了

**Comment by poonjh** [comment]
Thanks @dsander , running on Debian 9 now.

I need process Chinese RSS,  for the "De Duplication Agent", I get the following error 
U+6613 from UTF-8 to US-ASCII /home/huginn/huginn/app/models/agent_log.rb:16:in `write'

any hint how should fix？

**Comment by poonjh** [comment]
@se7cn  谢谢你的建议，  不太会Linux，你那些操作玩不来啊。
真想找个付费的类似服务。 还没有找到哪里有。

**Comment by poonjh** [comment]
I like this great application but get above issue from time to time,  need restart server whenever get issue.   Almost give up now....:(..  Anyone can find a fix, I can buy you coffee or beer.   

Thanks, @se7cn  for your tips... you give up this app?   Any other replacement you get?  

Or Anyone knows alternative paid Service available?     @dsander This is a really great product,  do you have any plan to commercialize this app,  so can get someone to fix the issue?   Thank you.

**Comment by dsander** [comment]
@poonjh Are you using the `Procfile` setup described [here](https://github.com/huginn/huginn/issues/2242#issuecomment-375058575) it is the best solution we have. Sadly a hosted service would not change that.

**Comment by poonjh** [comment]
Yes,  it's @dsander

**Comment by dsander** [comment]
If you can share a scenario of Agents that frequently get stuck I could have a look at it. The problem with this kind of issue was that it is always hard to reproduce on different systems.

**Comment by poonjh** [comment]
Great,  Thank you @dsander   I'll share you my huginn site detail via Twitter.  You can take a look when you get time.    It's OK to make any changes on the VPS as long as it can work normally.

**Comment by poonjh** [comment]
Cannot send you a message, let me know how can send you my huginn site detail @dsander , thanks you

**Comment by dsander** [comment]
I followed you on twitter if your handle is the same as here.

**Comment by malagebidi** [comment]
@se7cn 好办法，我有一个Website Agent也是经常卡住，多开几个worker好像都没用，看来也得脚本来解决了。

**Comment by 10362227** [comment]
> @poonjh 都试过，之前有人反馈尝试了更换数据库，但是仍然无法说明问题出在哪里了
> 最后我放弃了
> 给你个解决思路
> 
> 1. 如何发现huginn不工作了？ 你发现rss不更新了对吧
> 2. 那么设定一个定时任务去检查 你的rss，检查某个特定的值，做比较
> 3. 当满足某种条件，就判定为  huginn 挂了。 自动重启
> 
> 我做了类似的处理去监控状态，每10分钟保存一次时间，然后再比对时间是不是超出10分钟。如果超出了。意味着huggin挂了，自动重启。 后来我查看了重启日志。
> 仍然是不规律的重启， 一天两三次，两三天一次。不过至少不用担心卡住了

能不能说下怎么弄，怎么写命令

**Comment by 10362227** [comment]
> 多开几个worker好像都没用，看来也得脚本来解决了。

怎么搞，急需

**Comment by malagebidi** [comment]
`#!/bin/sh

timestamp() {
    date +"%s"
}

modificationTimeStamp() {
    curl --silent https://WP网站/feed |
        grep -o '<pubDate>.*</pubDate>' | sed 's/\(<pubDate>\|<\/pubDate>\)//g' |
        xargs -I{} date -d {} +"%s"
}

t=$(timestamp)
modt=$(modificationTimeStamp)

diff=$(($(timestamp) - $(modificationTimeStamp)))

if [ $diff -gt 64800 ]; then
    echo "$diff seconds unchange."|mail -s "Huginn Restarting" 你的邮箱 -aFrom:发件邮箱
    cd /home/huginn/huginn && sudo bundle exec rake production:force_stop && sudo bundle exec rake production:export
fi`

这是我用的脚本可以参考下，如果我的wp首页超过18小时没更新，就强制重启huginn。

**Comment by 10362227** [comment]
> > #!/bin/sh
> > timestamp() {
> > date +"%s"
> > }
> > modificationTimeStamp() {
> > curl --silent [https://WP网站/feed](https://WP%E7%BD%91%E7%AB%99/feed) |
> > grep -o '.*' | sed 's/(|</pubDate>)//g' |
> > xargs -I{} date -d {} +"%s"
> > }
> > t=$(timestamp)
> > modt=$(modificationTimeStamp)
> > diff=$(($(timestamp) - $(modificationTimeStamp)))
> > if [ $diff -gt 64800 ]; then
> > echo "$diff seconds unchange."|mail -s "Huginn Restarting" 你的邮箱 -aFrom:发件邮箱
> > cd /home/huginn/huginn && sudo bundle exec rake production:force_stop && sudo bundle exec rake production:export
> > fi
> 
> @10362227 这是我用的脚本可以参考下，如果我的wp首页超过18小时没更新，就强制重启huginn。

谢谢！不过我部署在多个herkou上，用的是api重启dyno命令（curl -n -X DELETE https://api.heroku.com/apps/XXXXX/dynos -H "Content-Type: application/json" -H "Accept: application/vnd.heroku+json; version=3" -H "Authorization: Bearer $token"），不用安装cli，获取token后可以在其它vps上重启，我之前定时重启，过于频繁导致Huginn出严重bug，所以希望写个判断命令，15分钟内feed没有更新就重启dyno。
刚刚我修改了下你的命令，不行，报错如下：
`1.sh: line 2: $'\r': command not found
1.sh: line 3: syntax error near unexpected token `$'{\r''
'.sh: line 3: `timestamp() {`
centos7 x64系统

本人没有学过编程，就是需要，自己摸索的，所以懂一点点很基本的，求改下，另外这个是要丢定时任务运行吧

**Comment by 10362227** [comment]
之前是换行符问题，解决后还是报错
`ed: -e expression #1, char 17: unknown option to `s'
sed: -e expression #1, char 17: unknown option to `s'
2.sh: line 16: 1569893828 - : syntax error: operand expected (error token is "- ")
2.sh: line 18: [: -gt: unary operator expected
`

**Comment by malagebidi** [comment]
[compare_timestamp.sh.txt](https://github.com/huginn/huginn/files/3674078/compare_timestamp.sh.txt)

我把我用的脚本添加注释上传，可能粘贴上来那段换行有问题。

**Comment by 10362227** [comment]
> [compare_timestamp.sh.txt](https://github.com/huginn/huginn/files/3674078/compare_timestamp.sh.txt)
> 
> 我把我用的脚本添加注释上传，可能粘贴上来那段换行有问题，另外还得看看你的feed和wordpress的feed格式是不是不一样。



直接运行，各种错误
3.sh: line 2: $'\r': command not found
3.sh: line 4: syntax error near unexpected token `$'{\r''
'.sh: line 4: `timestamp() 

转换成UNIX格式后（https://blog.csdn.net/violet_echo_0908/article/details/52042137），报了两个错
`3.sh: line 19: 1569897583 - : syntax error: operand expected (error token is "- ")
3.sh: line 20: [: -gt: unary operator expected
`

**Comment by malagebidi** [comment]
feed地址改没有，feed更新时间没获取到。再不行的话你只有自己研究了。

**Comment by 10362227** [comment]
> feed地址改没有，feed更新时间没获取到。再不行的话你只有自己研究了。

能否只匹配第二个<pubDate>.*</pubDate>，huginn自己生成的rss，最开头的描述中也有<pubDate>.*</pubDate>，永远是系统时间，第二个<pubDate>.*</pubDate>一定是最新发布时间（也就是最新feed），后面的<pubDate>.*</pubDate>都可以不用管。

**Comment by gchust** [comment]
I think this PR can fix this issue:
https://github.com/huginn/huginn/pull/1892

I built a docker image after merging this PR in my fork repository, and I did not face this error again now

**Comment by bogorad** [comment]
I have a similar issue - "Dry run" succeeds, and I get a meaningful output of the RSS feed requested. But a proper "run" doesn't do anything, sits in "jobs pending". There are no logs.

Here's the RSS agent:

```{
  "expected_update_period_in_days": "1",
  "clean": "false",
  "url": "https://www.androidpolice.com/feed/"
}```

Here's the logfile from a "Dry run":

```[40d5024c-c36a-45b9-8d75-a1ccd38722f8] Started POST "/agents/15/dry_runs" for ipaddr at 2022-11-06 12:57:51 -0800
[40d5024c-c36a-45b9-8d75-a1ccd38722f8] Processing by Agents::DryRunsController#create as HTML
[40d5024c-c36a-45b9-8d75-a1ccd38722f8]   Parameters: {"agent_id"=>"15"}
ipaddr - - [06/Nov/2022:12:57:52 -0800] "GET /worker_status?since_id=0 HTTP/1.0" 200 124 0.0094
ipaddr - - [06/Nov/2022:12:57:54 -0800] "GET /worker_status?since_id=0 HTTP/1.0" 200 124 0.0090
ipaddr - - [06/Nov/2022:12:57:56 -0800] "GET /worker_status?since_id=0 HTTP/1.0" 200 124 0.0090
ipaddr - - [06/Nov/2022:12:57:58 -0800] "GET /worker_status?since_id=0 HTTP/1.0" 200 124 0.0089
[40d5024c-c36a-45b9-8d75-a1ccd38722f8]   Rendering agents/dry_runs/create.html.erb
[40d5024c-c36a-45b9-8d75-a1ccd38722f8]   Rendered agents/dry_runs/create.html.erb (Duration: 3.0ms | Allocations: 538)
[40d5024c-c36a-45b9-8d75-a1ccd38722f8] Completed 200 OK in 8151ms (Views: 4.1ms | ActiveRecord: 2.7ms | Allocations: 114290)
ipaddr - - [06/Nov/2022:12:57:59 -0800] "POST /agents/15/dry_runs HTTP/1.0" 200 263445 8.1882
ipaddr - - [06/Nov/2022:12:58:00 -0800] "GET /worker_status?since_id=0 HTTP/1.0" 200 124 0.0096
```

When I do "Run" there's nothing in the log and one "queued" job appears.

**Comment by dreamerc** [comment]
You can try this patch for production.

```diff
diff --git a/Procfile b/Procfile
index 266e43a8..f6ea3623 100644
--- a/Procfile
+++ b/Procfile
@@ -3,8 +3,8 @@
 ###############################
 
 # Procfile for development using the new threaded worker (scheduler, twitter stream and delayed job)
-web: bundle exec rails server -p ${PORT-3000} -b ${IP-0.0.0.0}
-jobs: bundle exec rails runner bin/threaded.rb
+#web: bundle exec rails server -p ${PORT-3000} -b ${IP-0.0.0.0}
+#jobs: bundle exec rails runner bin/threaded.rb
 
 # Old version with separate processes (use this if you have issues with the threaded version)
 # web: bundle exec rails server
@@ -21,8 +21,8 @@ jobs: bundle exec rails runner bin/threaded.rb
 # https://github.com/huginn/huginn/doc
 
 # Using the threaded worker (consumes less RAM but can run slower)
-# web: bundle exec unicorn -c config/unicorn.rb
-# jobs: bundle exec rails runner bin/threaded.rb
+web: bundle exec unicorn -c config/unicorn.rb
+jobs: bundle exec rails runner bin/threaded.rb
 
 # Old version with separate processes (use this if you have issues with the threaded version)
 # web: bundle exec unicorn -c config/unicorn.rb
diff --git a/app/concerns/web_request_concern.rb b/app/concerns/web_request_concern.rb
index 331dfea4..ead57151 100644
--- a/app/concerns/web_request_concern.rb
+++ b/app/concerns/web_request_concern.rb
@@ -131,6 +131,8 @@ module WebRequestConcern
         builder.options.params_encoder = DoNotEncoder
       end
 
+      builder.options.timeout = (Delayed::Worker.max_run_time.seconds - 2).to_i
+
       if userinfo = basic_auth_credentials
         builder.request :basic_auth, *userinfo
       end
```

Mostly you can delete some event or reduce **Keep events** to days or hours.
Here is the way to fix Delayed::Job(or Job) Stock.

```bash
$ docker exec -it huginn /bin/bash
Docker$ source .env
Docker$ bundle exec rails console --environment=prod
Rails$ Delayed::Job.where("locked_at IS NOT NULL AND locked_by IS NOT NULL AND failed_at IS NULL").destroy_all
```
