### ISSUE TITLE
Tumblr Publish Agent undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by l1n** [huginn/huginn#2247]
Not sure what would be useful for debugging this, but stack trace below:
```
                        undefined method `[]' for nil:NilClass
/pub/lin/huginn/app/models/agents/tumblr_publish_agent.rb:131:in `publish_post'
/pub/lin/huginn/app/models/agents/tumblr_publish_agent.rb:111:in `block in receive'
/usr/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5/lib/active_record/relation/delegation.rb:39:in `each'
/usr/lib/ruby/gems/2.5.0/gems/activerecord-5.1.5/lib/active_record/relation/delegation.rb:39:in `each'
/pub/lin/huginn/app/models/agents/tumblr_publish_agent.rb:104:in `receive'
/pub/lin/huginn/app/jobs/agent_receive_job.rb:8:in `perform'
/usr/lib/ruby/gems/2.5.0/gems/activejob-5.1.5/lib/active_job/execution.rb:37:in `block in perform_now'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/usr/lib/ruby/gems/2.5.0/gems/i18n-0.9.5/lib/i18n.rb:268:in `with_locale'
/usr/lib/ruby/gems/2.5.0/gems/activejob-5.1.5/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:117:in `instance_exec'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/lib/ruby/gems/2.5.0/gems/activejob-5.1.5/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/notifications.rb:166:in `block in instrument'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/notifications.rb:166:in `instrument'
/usr/lib/ruby/gems/2.5.0/gems/activejob-5.1.5/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/usr/lib/ruby/gems/2.5.0/gems/activejob-5.1.5/lib/active_job/logging.rb:44:in `block in tag_logger'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/tagged_logging.rb:26:in `tagged'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/tagged_logging.rb:69:in `tagged'
/usr/lib/ruby/gems/2.5.0/gems/activejob-5.1.5/lib/active_job/logging.rb:44:in `tag_logger'
/usr/lib/ruby/gems/2.5.0/gems/activejob-5.1.5/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:117:in `instance_exec'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:135:in `run_callbacks'
/usr/lib/ruby/gems/2.5.0/gems/activejob-5.1.5/lib/active_job/execution.rb:33:in `perform_now'
/usr/lib/ruby/gems/2.5.0/gems/activejob-5.1.5/lib/active_job/execution.rb:22:in `block in execute'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/usr/lib/ruby/gems/2.5.0/gems/activejob-5.1.5/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/execution_wrapper.rb:85:in `wrap'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/reloader.rb:68:in `block in wrap'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/execution_wrapper.rb:85:in `wrap'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/reloader.rb:67:in `wrap'
/usr/lib/ruby/gems/2.5.0/gems/activejob-5.1.5/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:117:in `instance_exec'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:135:in `run_callbacks'
/usr/lib/ruby/gems/2.5.0/gems/activejob-5.1.5/lib/active_job/execution.rb:20:in `execute'
/usr/lib/ruby/gems/2.5.0/gems/activejob-5.1.5/lib/active_job/queue_adapters/delayed_job_adapter.rb:36:in `perform'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/backend/base.rb:78:in `invoke_job'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:230:in `block in run'
/usr/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:229:in `run'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:213:in `block in work_off'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:212:in `times'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:212:in `work_off'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:172:in `loop'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:172:in `block in start'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block in add'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:171:in `start'
/pub/lin/huginn/lib/delayed_job_worker.rb:6:in `run'
/pub/lin/huginn/app/concerns/long_runnable.rb:71:in `block in run!'
```

**Comment by dsander** [comment]
That looks like that either the `options` key of the Agent options is empty or gets overridden by the incoming Event. Can you share your Agent configuration and the Event the Agent received?

**Comment by l1n** [comment]
Agent config:
```
{
  "state": "queue",
  "id": "{{tumblr_post_id}}",
  "reblog_key": "{{reblog_key}}",
  "tags": "originaltags, {{ categories | join: ', ' }}",
  "expected_update_period_in_days": "2",
  "blog_name": "ourwitching",
  "post_type": "reblog"
}
```
And the event
```
{
  "id": "tag:rss.noblejury.com,2018-03-22:/1222215",
  "url": "http://cognitohazard.tumblr.com/post/172141195299",
  "urls": [
    "http://cognitohazard.tumblr.com/post/172141195299",
    "http://cognitohazard.tumblr.com/"
  ],
  "links": [
    {
      "href": "http://cognitohazard.tumblr.com/post/172141195299",
      "rel": "alternate",
      "type": "text/html"
    },
    {
      "href": "http://cognitohazard.tumblr.com/",
      "rel": "self"
    }
  ],
  "title": "picsthatmakeyougohmm:\nhmmm",
  "description": "<p>picsthatmakeyougohmm:\nhmmm<\/p>",
  "content": "<img src=\"http://78.media.tumblr.com/bbc347abf87ebf9b8bcc17674d046c47/tumblr_p3a8hhkFbU1wsbn2ao1_500.jpg\" referrerpolicy=\"no-referrer\"><br><br><p><a href=\"https://picsthatmakeyougohmm.tumblr.com/post/170394645293/hmmm\" rel=\"noopener noreferrer\" target=\"_blank\">picsthatmakeyougohmm<\/a>:<\/p>\n<blockquote><p>hmmm<\/p><\/blockquote>",
  "image": null,
  "enclosure": null,
  "authors": [

  ],
  "categories": [
    "hmmm"
  ],
  "date_published": null,
  "last_updated": "2018-03-22T17:36:34+00:00",
  "message": "Its a tumblr link",
  "reblog_key": "55fnHgu8",
  "blog_name": "cognitohazard",
  "tumblr_post_id": 172141195299,
  "tumblr_post_type": "photo",
  "tumblr_source_url": "https://picsthatmakeyougohmm.tumblr.com/post/170394645293/hmmm"
}
```

**Comment by dsander** [comment]
That Agent config will not work, you can change the values of the default configuration, but the key and nested options of the configuration have to be identical to the default configuration.

```json
{
  "expected_update_period_in_days": "10",
  "blog_name": "{{blog_name}}",
  "post_type": "{{post_type}}",
  "options": {
    "state": "{{state}}",
    "tags": "{{tags}}",
    "tweet": "{{tweet}}",
    "date": "{{date}}",
    "format": "{{format}}",
    "slug": "{{slug}}",
    "title": "{{title}}",
    "body": "{{body}}",
    "caption": "{{caption}}",
    "link": "{{link}}",
    "source": "{{source}}",
    "quote": "{{quote}}",
    "url": "{{url}}",
    "description": "{{description}}",
    "conversation": "{{conversation}}",
    "external_url": "{{external_url}}",
    "embed": "{{embed}}",
    "id": "{{id}}",
    "reblog_key": "{{reblog_key}}",
    "comment": "{{comment}}"
  }
}
```

**Comment by l1n** [comment]
GOTCHA. I had some kind of corruption of the config that messed up the web interface and this was how I restored it, thank you so much!!
