### ISSUE TITLE
Webhook agent not working when file is included with JSON

### ISSUE THREAD

**Issue by dgw** [huginn/huginn#2263]
I had the idea of getting Huginn to do the job I currently have assigned to a single-purpose NodeJS webhook handler, processing Plex webhooks and sending Pushover notifications based on them.

Using the sample payloads I have, the webhook agent I wrote works perfectly. However, it chokes on real `media.play` events from Plex because Plex includes a thumbnail with the JSON. From the Plex end, there is no way to disable sending the thumbnail, unfortunately.

This is what the webhook payload looks like in Huginn's log. I removed the majority of the payload for brevity because it's a large JSON object that parses just fine in the absence of an image attachment.

````
I, [2018-04-19T04:31:36.128872 #4476]  INFO -- : [c4751944-8a9d-4c62-9d60-dd0c2e67dc62] Started POST "/users/1/web_requests/10/dgwPlexHook" for 172.68.90.55 at 2018-04-19 04:31:36 -0700
I, [2018-04-19T04:31:36.130660 #4476]  INFO -- : [c4751944-8a9d-4c62-9d60-dd0c2e67dc62] Processing by WebRequestsController#handle_request as */*
I, [2018-04-19T04:31:36.130882 #4476]  INFO -- : [c4751944-8a9d-4c62-9d60-dd0c2e67dc62]   Parameters: {"payload"=>"JSON object as string that Huginn parses fine for other event types", "thumb"=>#<ActionDispatch::Http::UploadedFile:0x0000000b04d7f0 @tempfile=#<Tempfile:/tmp/RackMultipart20180419-4476-rnzd3z.jpg>, @original_filename="thumb.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"thumb\"; filename=\"thumb.jpg\"\r\nContent-Type: image/jpeg\r\n">, "user_id"=>"1", "agent_id"=>"10", "secret"=>"removed"}
I, [2018-04-19T04:31:36.136038 #4476]  INFO -- : [c4751944-8a9d-4c62-9d60-dd0c2e67dc62] Completed 401 Unauthorized in 5ms (ActiveRecord: 0.8ms)
F, [2018-04-19T04:31:36.136651 #4476] FATAL -- : [c4751944-8a9d-4c62-9d60-dd0c2e67dc62]
F, [2018-04-19T04:31:36.136683 #4476] FATAL -- : [c4751944-8a9d-4c62-9d60-dd0c2e67dc62] Encoding::UndefinedConversionError ("\xFF" from ASCII-8BIT to UTF-8):
F, [2018-04-19T04:31:36.136706 #4476] FATAL -- : [c4751944-8a9d-4c62-9d60-dd0c2e67dc62]
F, [2018-04-19T04:31:36.136731 #4476] FATAL -- : [c4751944-8a9d-4c62-9d60-dd0c2e67dc62] lib/utils.rb:90:in `values_at'
[c4751944-8a9d-4c62-9d60-dd0c2e67dc62] lib/utils.rb:79:in `value_at'
[c4751944-8a9d-4c62-9d60-dd0c2e67dc62] app/models/agents/webhook_agent.rb:118:in `payload_for'
[c4751944-8a9d-4c62-9d60-dd0c2e67dc62] app/models/agents/webhook_agent.rb:88:in `receive_web_request'
[c4751944-8a9d-4c62-9d60-dd0c2e67dc62] app/models/agent.rb:167:in `trigger_web_request'
[c4751944-8a9d-4c62-9d60-dd0c2e67dc62] app/controllers/web_requests_controller.rb:29:in `handle_request'
[c4751944-8a9d-4c62-9d60-dd0c2e67dc62] config/initializers/silence_worker_status_logger.rb:3:in `call'
````

When updating Huginn earlier (to 3e50831, the latest `master` commit at fetch time) I set `en_US.UTF-8` as the default locale in `/etc/default/locale` (using all three environment variables, `LC_ALL`, `LANG`, and `LANGUAGE`) to get the upgrade commands working properly. In case it's relevant, this system is running Ruby 2.3.4p301 on Ubuntu 14.04.5.

I figured rather than continue banging my head against this, I should just ask for help from someone who knows the innards of the Webhook Agent and get the sleep I should have started on hours ago. :smile_cat:

**Comment by dsander** [comment]
I think we need to filter the file upload out of the [parameter we use to extract the payload](https://github.com/huginn/huginn/blob/master/app/models/agents/webhook_agent.rb#L118). The exception is happening because we are trying to convert the file upload to a string [here](https://github.com/huginn/huginn/blob/master/lib/utils.rb#L90).
