### ISSUE TITLE
agent not run

### ISSUE THREAD

**Issue by Howard-guo** [huginn/huginn#2317]
i deploy my huginn on heroku,it run normally for a long time.
i changed the config TIMEZONE about 1 hour ago,and it continue normally for half hour,then stoped -- all agent pending at "queued" for not running.
i don't know how to watch logs of heroku application.
----------------------------------------------------------
BTW: i changed the TIMEZONE by command: heroku config:set TIMEZONE="Asia/Shanghai"

**Comment by dsander** [comment]
Not sure what happened, if the background process stopped it should be restarted within a minute. You can watch the logs by running `heroku logs -t` in your local Huginn repository. If the processing stopped again, start watching the logs, restart the app on Heroku and wait until it happens again.

**Comment by Howard-guo** [comment]
@dsander thanks,i type command:heroku logs -a myappid,it output this:
2018-06-20T09:02:06.950658+00:00 app[web.1]: Starting HuginnScheduler
2018-06-20T09:02:06.957413+00:00 app[web.1]: E, [2018-06-20T17:02:06.957330 #4] ERROR -- : reaped #<Process::Status: pid 10637 exit 1> worker=unknown
2018-06-20T09:02:07.469539+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=d5b63cb9-8a69-4579-baae-d09ad74c60d3 fwd="45.124.27.29" dyno=web.1 connect=1ms service=19ms status=200 bytes=1027 protocol=https
2018-06-20T09:02:11.429809+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=f9956703-d391-445d-9343-e64170c28f93 fwd="45.124.27.29" dyno=web.1 connect=0ms service=17ms status=200 bytes=1027 protocol=https
2018-06-20T09:02:15.407034+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=9e713878-0f00-467f-a6de-7b554bb13902 fwd="45.124.27.29" dyno=web.1 connect=2ms service=20ms status=200 bytes=1027 protocol=https
2018-06-20T09:02:19.207009+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=c1ceec42-8f45-4cdf-b56c-126ab5c4405f fwd="45.124.27.29" dyno=web.1 connect=0ms service=25ms status=200 bytes=1027 protocol=https
2018-06-20T09:02:22.366080+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=f41cfab6-bf00-4e2a-8b01-67757c085163 fwd="45.124.27.29" dyno=web.1 connect=0ms service=16ms status=200 bytes=1027 protocol=https
2018-06-20T09:02:26.458166+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=a7fd8b73-8164-44ef-939b-7acde74d4991 fwd="45.124.27.29" dyno=web.1 connect=0ms service=17ms status=200 bytes=1027 protocol=https
2018-06-20T09:02:30.400162+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=2201afc9-e41f-4da2-8636-193615a2d596 fwd="45.124.27.29" dyno=web.1 connect=1ms service=17ms status=200 bytes=1027 protocol=https
2018-06-20T09:02:34.429024+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=9059d1b9-fc68-4c78-b3e0-7aaf573da9c6 fwd="45.124.27.29" dyno=web.1 connect=0ms service=18ms status=200 bytes=1027 protocol=https
2018-06-20T09:02:38.459631+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=bcd81ed2-d643-4780-b134-c9cf8eac3809 fwd="45.124.27.29" dyno=web.1 connect=0ms service=35ms status=200 bytes=1027 protocol=https
2018-06-20T09:02:42.139169+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=366df8e4-0bfc-4be5-b66e-41d3fe6cf05f fwd="45.124.27.29" dyno=web.1 connect=0ms service=18ms status=200 bytes=1027 protocol=https
2018-06-20T09:02:45.098924+00:00 app[web.1]: New threaded worker PID: 10663
2018-06-20T09:02:45.143651+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=9a2a8615-59de-4339-8d88-d6c1f25f6c31 fwd="45.124.27.29" dyno=web.1 connect=1ms service=19ms status=200 bytes=1027 protocol=https
2018-06-20T09:02:45.350874+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2018-06-20T09:02:45.350897+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2018-06-20T09:02:45.358503+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2018-06-20T09:02:45.358506+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2018-06-20T09:02:45.822470+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2018-06-20T09:02:45.822499+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2018-06-20T09:02:45.830931+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2018-06-20T09:02:45.830934+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2018-06-20T09:02:47.899324+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2018-06-20T09:02:47.899352+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2018-06-20T09:02:47.906717+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2018-06-20T09:02:47.906720+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2018-06-20T09:02:48.411977+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=b561a9aa-0c36-4abf-b9e1-2a89351bdab5 fwd="45.124.27.29" dyno=web.1 connect=0ms service=19ms status=200 bytes=1027 protocol=https
2018-06-20T09:02:52.039690+00:00 app[web.1]: /app/lib/huginn_scheduler.rb:141:in `+': no implicit conversion of nil into String (TypeError)
2018-06-20T09:02:52.039709+00:00 app[web.1]: from /app/lib/huginn_scheduler.rb:141:in `block in setup'
2018-06-20T09:02:52.039713+00:00 app[web.1]: from /app/lib/huginn_scheduler.rb:140:in `times'
2018-06-20T09:02:52.039715+00:00 app[web.1]: from /app/lib/huginn_scheduler.rb:140:in `setup'
2018-06-20T09:02:52.039720+00:00 app[web.1]: from /app/lib/agent_runner.rb:82:in `block in run_workers'
2018-06-20T09:02:52.039718+00:00 app[web.1]: from /app/app/concerns/long_runnable.rb:86:in `setup!'
2018-06-20T09:02:52.039722+00:00 app[web.1]: from /app/lib/agent_runner.rb:79:in `each'
2018-06-20T09:02:52.039726+00:00 app[web.1]: from /app/lib/agent_runner.rb:79:in `run_workers'
2018-06-20T09:02:52.039727+00:00 app[web.1]: from /app/lib/agent_runner.rb:39:in `run'
2018-06-20T09:02:52.039729+00:00 app[web.1]: from bin/threaded.rb:13:in `<top (required)>'
2018-06-20T09:02:52.039748+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/commands/runner/runner_command.rb:34:in `load'
2018-06-20T09:02:52.039750+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/commands/runner/runner_command.rb:34:in `perform'
2018-06-20T09:02:52.039751+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
2018-06-20T09:02:52.039753+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
2018-06-20T09:02:52.039758+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
2018-06-20T09:02:52.039759+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
2018-06-20T09:02:52.039761+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
2018-06-20T09:02:52.039763+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
2018-06-20T09:02:52.039765+00:00 app[web.1]: from bin/rails:9:in `require'
2018-06-20T09:02:52.039766+00:00 app[web.1]: from bin/rails:9:in `<main>'
2018-06-20T09:02:52.056842+00:00 app[web.1]: Starting HuginnScheduler
2018-06-20T09:02:52.063820+00:00 app[web.1]: E, [2018-06-20T17:02:52.063721 #4] ERROR -- : reaped #<Process::Status: pid 10663 exit 1> worker=unknown
2018-06-20T09:02:52.431818+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=8bcf8851-0093-479e-a490-225163748509 fwd="45.124.27.29" dyno=web.1 connect=0ms service=15ms status=200 bytes=1027 protocol=https
2018-06-20T09:02:56.410073+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=53ea65b1-788a-47de-a547-ddcd67586682 fwd="45.124.27.29" dyno=web.1 connect=0ms service=18ms status=200 bytes=1027 protocol=https
2018-06-20T09:03:00.389515+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=807cf3e7-eeef-4639-8e1b-1e783132a2dc fwd="45.124.27.29" dyno=web.1 connect=0ms service=16ms status=200 bytes=1027 protocol=https
2018-06-20T09:03:04.120322+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=c43ee60a-1e24-4c75-ac97-2c603641021f fwd="45.124.27.29" dyno=web.1 connect=0ms service=18ms status=200 bytes=1027 protocol=https
2018-06-20T09:03:07.468012+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=577874d8-d3f6-4932-a715-18d86645a673 fwd="45.124.27.29" dyno=web.1 connect=0ms service=16ms status=200 bytes=1027 protocol=https
2018-06-20T09:03:11.452117+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=894a01c0-f80b-4120-a73b-26fed13d0d29 fwd="45.124.27.29" dyno=web.1 connect=0ms service=25ms status=200 bytes=1027 protocol=https
2018-06-20T09:03:15.434169+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=45bae9b6-f97c-4d19-bd37-8bf0e6024c1e fwd="45.124.27.29" dyno=web.1 connect=0ms service=14ms status=200 bytes=1027 protocol=https
2018-06-20T09:03:19.393953+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=1b170c17-7431-4747-955b-fa41c7a6fa3b fwd="45.124.27.29" dyno=web.1 connect=0ms service=24ms status=200 bytes=1027 protocol=https
2018-06-20T09:03:23.445641+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=7b7f5245-7910-42f3-843f-28f4ff7c5e1c fwd="45.124.27.29" dyno=web.1 connect=0ms service=39ms status=200 bytes=1026 protocol=https
2018-06-20T09:03:27.405007+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=cec36960-7c99-4b81-8171-8a69a2d06c40 fwd="45.124.27.29" dyno=web.1 connect=0ms service=18ms status=200 bytes=1027 protocol=https
2018-06-20T09:03:30.099845+00:00 app[web.1]: New threaded worker PID: 10689
2018-06-20T09:03:30.415741+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2018-06-20T09:03:30.415758+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2018-06-20T09:03:30.423608+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2018-06-20T09:03:30.423605+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2018-06-20T09:03:30.839411+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2018-06-20T09:03:30.839430+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2018-06-20T09:03:30.847172+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2018-06-20T09:03:30.847175+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2018-06-20T09:03:31.465620+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=cf4c27aa-b17e-41f1-a5f1-2b0777bb0c3c fwd="45.124.27.29" dyno=web.1 connect=0ms service=15ms status=200 bytes=1027 protocol=https
2018-06-20T09:03:32.653463+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2018-06-20T09:03:32.653470+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2018-06-20T09:03:32.659703+00:00 app[web.1]: fatal: Not a git repository (or any parent up to mount point /app)
2018-06-20T09:03:32.659706+00:00 app[web.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2018-06-20T09:03:36.857134+00:00 app[web.1]: /app/lib/huginn_scheduler.rb:141:in `+': no implicit conversion of nil into String (TypeError)
2018-06-20T09:03:36.857166+00:00 app[web.1]: from /app/lib/huginn_scheduler.rb:141:in `block in setup'
2018-06-20T09:03:36.857167+00:00 app[web.1]: from /app/lib/huginn_scheduler.rb:140:in `times'
2018-06-20T09:03:36.857169+00:00 app[web.1]: from /app/lib/huginn_scheduler.rb:140:in `setup'
2018-06-20T09:03:36.857170+00:00 app[web.1]: from /app/app/concerns/long_runnable.rb:86:in `setup!'
2018-06-20T09:03:36.857172+00:00 app[web.1]: from /app/lib/agent_runner.rb:82:in `block in run_workers'
2018-06-20T09:03:36.857174+00:00 app[web.1]: from /app/lib/agent_runner.rb:79:in `each'
2018-06-20T09:03:36.857175+00:00 app[web.1]: from /app/lib/agent_runner.rb:79:in `run_workers'
2018-06-20T09:03:36.857179+00:00 app[web.1]: from /app/lib/agent_runner.rb:39:in `run'
2018-06-20T09:03:36.857181+00:00 app[web.1]: from bin/threaded.rb:13:in `<top (required)>'
2018-06-20T09:03:36.857192+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/commands/runner/runner_command.rb:34:in `load'
2018-06-20T09:03:36.857193+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/commands/runner/runner_command.rb:34:in `perform'
2018-06-20T09:03:36.857195+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
2018-06-20T09:03:36.857197+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
2018-06-20T09:03:36.857199+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
2018-06-20T09:03:36.857200+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
2018-06-20T09:03:36.857207+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
2018-06-20T09:03:36.857209+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.5.0/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
2018-06-20T09:03:36.857210+00:00 app[web.1]: from bin/rails:9:in `require'
2018-06-20T09:03:36.857212+00:00 app[web.1]: from bin/rails:9:in `<main>'
2018-06-20T09:03:36.877579+00:00 app[web.1]: Starting HuginnScheduler
2018-06-20T09:03:36.890930+00:00 app[web.1]: E, [2018-06-20T17:03:36.890826 #4] ERROR -- : reaped #<Process::Status: pid 10689 exit 1> worker=unknown
2018-06-20T09:03:37.976692+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=b9de3acc-268e-4210-894a-c0d1326c384f fwd="45.124.27.29" dyno=web.1 connect=0ms service=19ms status=200 bytes=1027 protocol=https
2018-06-20T09:03:41.409988+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=fb8ad570-c081-4339-9345-f04d2a1fc648 fwd="45.124.27.29" dyno=web.1 connect=0ms service=20ms status=200 bytes=1027 protocol=https
2018-06-20T09:03:45.138648+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=6a09937d-031e-4d68-a3fc-1d6535a371d3 fwd="45.124.27.29" dyno=web.1 connect=0ms service=16ms status=200 bytes=1027 protocol=https
2018-06-20T09:03:48.402982+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=ee665fea-42fd-4ec5-a159-54911ea67ae6 fwd="45.124.27.29" dyno=web.1 connect=1ms service=22ms status=200 bytes=1027 protocol=https
2018-06-20T09:03:52.445749+00:00 heroku[router]: at=info method=GET path= "/worker_status?since_id=5791" host=huginn-howard.herokuapp.com request_id=801be12b-69dc-421e-8a08-63099efb98d6 fwd="45.124.27.29" dyno=web.1 connect=1ms service=15ms status=200 bytes=1027 protocol=https

**Comment by Howard-guo** [comment]
it's fixed by set my TIMEZONE to correct.
the timezone name can find by
rake time:zones:all

@dsander thanks alot

**Comment by dsander** [comment]
@Howard-guo Good catch, i did not notice the timezone was incorrect.
