### ISSUE TITLE
Worker errors after update

### ISSUE THREAD

**Issue by l1n** [huginn/huginn#2323]
Not sure the best way to debug this, but I'm having some issues launching worker threads after a bundle update:
```Jun 26 09:39:43 noblejury.com systemd[1]: huginn-dj3@3330.service: Failed with result 'exit-code'.
Jun 26 09:39:43 noblejury.com systemd[1]: huginn-dj3@3330.service: Main process exited, code=exited, status=1/FAILURE
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   script/delayed_job:3:in `<top (required)>'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   script/delayed_job:3:in `require'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /pub/lin/huginn/config/environment.rb:5:in `<top (required)>'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `method_missing'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `public_send'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/application/finisher.rb:69:in `each'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:356:in `eager_load!'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:475:in `eager_load!'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:475:in `each'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:477:in `block in eager_load!'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:477:in `each'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:242:in `require_dependency'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `depend_on'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:326:in `depend_on'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:348:in `require_or_load'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:37:in `load_interlock'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:13:in `loading'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:37:in `block in load_interlock'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:370:in `block in require_or_load'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /usr/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]:   /pub/lin/huginn/app/concerns/twitter_concern.rb:58:in `<main>'
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]: NoMethodError: undefined method `merge' for #<Proc:0x000055e96c388168>
Jun 26 09:39:43 noblejury.com huginn-dj3@3330.service[16176]: bundler: failed to load command: script/delayed_job (script/delayed_job)```

**Comment by dsander** [comment]
You ran `bundle update`? The short answer is: don't, revert the `Gemfile.lock` back to the one in the repository and you should be fine. 😄 

We are only testing Huginn with the dependencies specified in the `Gemfile.lock`. `bundle update` updates all gems based on the version constraints in the `Gemfile`, which is never a good idea even when developing and deliberately updating gems we are only using `bundle update <gemname>` to only update one specific gem.
