### ISSUE TITLE
Problem about FtpsiteAgent and ReadfileAgent

### ISSUE THREAD

**Issue by tortoo** [huginn/huginn#2370]
I tested the FtpsiteAgent and found some problems for me.

First, in the description it said `with write (mode) it writes received events to a file on the server`, dose this mean it writes every event it received each time into the specified file and each event a line? But after I sent two events with two time the second recovered the first.

Second, how can I specify the entire data or a part of the received event to write? I tested `"data": {{ data }}` and `"data": {{ event }}` and both failed. After I tested the following:

```
"data": [
    "{{ count }}",
    "{{ time }}",
    "{{ enc_uin }}"
  ]
```
I received error `Exception during receive. no implicit conversion of Array into String: ` in the log.

Third, in `write` mode `events created` number is always `0` but `write` execution is accomplished. Dose this mean there is no `file pointer ` generated? So if I want to use ReadfileAgent to get the content should I use another FtpsiteAgent in `read` mode to generate the `file pointer` first?

**Comment by dsander** [comment]
> But after I sent two events with two time the second covered the first.

Yes I assume the Agent will override the file if you do not change the name with data coming from the Event.



> Second, how can I specify the entire data or a part of the received event to write?

The Agent only supports to write string data, if you need to combine something in the Event you can either use Liquid like `"{{{ a }}{{ b }}{{ c }}"` or a EventFormattingAgent before the FtpSiteAgent.



> Third, in `write` mode `events created` number is always `0` but `write` execution is accomplished. Dose this mean there is no `file pointer` generated? So if I want to use ReadfileAgent to get the content should I use another FtpsiteAgent in `read` mode to generate the `file pointer` first?

Correct in write mode the Agent only receives Events.

**Comment by tortoo** [comment]
> Yes I assume the Agent will override the file if you do not change the name with data coming from the Event.

Do you mean overriding is  the only way to write each event from different time into a specified file? If I want to write each event with increasing way into one file how can I do?

**Comment by dsander** [comment]
Hmm where do you get the data for the FtpSiteAgent from? Increasing a number would probably require a JavaScriptAgent which keeps track of the number and increases it. You could use the [`date`](http://shopify.github.io/liquid/filters/date/) filter to use the current time as the filename: `{{ 'now' | date: '%Y-%m-%d %H:%M:%S' }}`

**Comment by tortoo** [comment]
My data is from an EventFormattingAgent. I'm avoiding to use JavaScriptAgent as much as possible because there is no example for myself to refer and I'm afraid I can't handle this.😹

My purpose is to send every event received to somewhere like a memory and then read them and do some further processing. I tried to use dropbox and reading file was perfect but writing was so hard for me. 

The FtpSiteAgent can only write each event into different single file whose filename is changing by time or something esle, is it right? In `read` mode FtpSiteAgent can read file `after` some time but how to get the `before` function? For example I want get the files in a week how can I do? Dose the `after` function mean it can read all files after that time? If not, what's the purpose of this function?

Another question or recommendation, ReadFileAgent seems to read the `file pointer` from FtpSiteAgent with `on_change` mode or it can only get the newest `file pointer`. Is it possible to read more than one and specify the time of `file pointer`? This may achieve the `all` mode function and becomes something like memory.

**Comment by dsander** [comment]
> The FtpSiteAgent can only write each event into different single file whose filename is changed by time or something esle, is it right?

Yes otherwise the contents of the file are overridden.

 

>  In `read` mode FtpSiteAgent can read file `after` some time but how to get the `before` function? For example I want get the files in a week how can I do? Dose the `after` function mean it can read all files after that time? If not, what's the purpose of this function?

I think the idea behind `after` was to only start processing files after a specific time. For example if you are connecting to a Ftp server that already has a lot of files in it, but you are only interested in files that were modified after the Agent was created.

You can backdate `after` to include the files that were created a week ago. There is no way to only receive events that were created before a specific date, but you can use the `timestamp` event attribute to filter them downstream.



> Another question or recommendation, ReadFileAgent seems to read the `file pointer` from FtpSiteAgent with `on_change` mode or it can only get the newest `file pointer`. Is it possible to read more than one and specify the time of `file pointer`? This may achieve the `all` mode function and becomes something like memory.

Not sure that I understand. The `ReadFileAgent` does not have any logic, it reads the contents of every `file pointer` it receives. The `FtpSiteAgent` keeps a memory of files it already emitted Events for and only re-emites them if the files mtime changed.



> In addition, I find that S3Agent has the fuction `When watch is set to false the agent will emit an event for every file in the bucket on each sheduled run`. Dose this mean different events can be written into a single event?

No I think the `S3Agent` will still emit one Event per file.



> I deeply hope this can be set on FtpSiteAgent because S3 has a limitation of the number of request. Ftp is more common and free than s3.

To do that you need to set `after` either nothing or really far back in past and clear the memory of the `FtpSiteAgent`.

**Comment by tortoo** [comment]
I got it and It's very clear. I just want to combine events in a period such as a week or a month and creating file isn't my purpose. After some research I find that **DigestAgent** is what I'm looking for. I'm leaving off the right path for a long time.😹

In the memory of **DigestAgent** there are only one number of six digits for every event. Dose this mean thousands of events a day is no problem? But the output can only merge the original event and if the original has many fields it'll be very huge. I think it's better to set an option to choose merge or not.

**Comment by dsander** [comment]
> In the memory of **DigestAgent** there are only one number of six digits for every event. Dose this mean thousands of events a day is no problem? But the output can only merge the original event and if the original has many fields it'll be very huge. I think it's better to set an option to choose merge or not.

Adding an option to not include the original should be doable. Having thousands of big events would probably require a lot of memory. If you want to test it on your instance you could [remove that limit](https://github.com/huginn/huginn/blob/master/app/models/agents/digest_agent.rb#L41) and see how it goes.

**Comment by tortoo** [comment]
@dsander Sorry I never did the test like modifying something in the url you provided in the past and don't know how to start. From now on I've only done the updating huginn operation. Maybe I can only do this step by step as your instruction.🙈

**Comment by dsander** [comment]
If you want to store more than 999 Events you only need to remove [that line](https://github.com/huginn/huginn/blob/master/app/models/agents/digest_agent.rb#L41) in `/home/huginn/huginn/app/models/agents/digest_agent.rb` and restart Huginn afterwards.

**Comment by tortoo** [comment]
I deleted that line and set 9999 Events, and then my edit was saved successfully.

Next, what can I do to add an option to not to include the original?

If there are 10000 events and one field which I'm going to combine has 23 alphabets or symbols each and it's only 230000B (224.6KB) with no orginal. The other field has about 200 alphabets or symbols each and 1953.1KB in all. I really need a test.

**Comment by dsander** [comment]
Add the following [between those two lines](https://github.com/huginn/huginn/blob/master/app/models/agents/digest_agent.rb#L62-L63)
```ruby
 payload.delete["events"] if !boolify(interpolated["merge"])
```
And set the `merge` option to `false`.

**Comment by tortoo** [comment]
I've done the processing but the `merge` option doesn't appear.

![image](https://user-images.githubusercontent.com/28673736/45743817-84a9b780-bc2f-11e8-9ade-8ae4bddaa02b.png)

![image](https://user-images.githubusercontent.com/28673736/45743945-d3575180-bc2f-11e8-9d69-748c9c680afc.png)

**Comment by tortoo** [comment]
And the events created are including the orginal events.

**Comment by tortoo** [comment]
Now input:
`"message": "{{ events | map: 'time' | join: '|' }}-{{ events.time }}"
`

And output:
`"message": "1537349037|1537348859-"`

The `{{ event.time }}`  outputs nothing. I also tested `{{ time }}` and it output nothing either. I think `{{ events | map: 'time' | join: '|' }}` comes from the memory and `{{ event.time }}` comes from the original events. After adding the sentence you given  the original events should have been excluded so `{{ events.time }}` or `{{ time }}` outputs nothing. But the the events created are still including the original events with many fields and the `message` field.

In my opinion, the right output should be opposite. `{{ events.time }}` or `{{ time }}` should output time and the events created should only contain the `message` field with no original events.

**Comment by tortoo** [comment]
I just solved the problem about `{{ events.time }}` with `{{ events | map: 'time' | last }}`. The rest problem is how to set the merge to false.

**Comment by dsander** [comment]
> I've done the processing but the `merge` option doesn't appear.

Sorry I forgot the Agent is form_configurable. To make the `merge` option show up in the UI add a line [after this one](https://github.com/huginn/huginn/blob/master/app/models/agents/digest_agent.rb#L38):
```ruby
 form_configurable :merge, type: :boolean
```

> I just solved the problem about `{{ events.time }}` with `{{ events | map: 'time' | last }}`. The rest problem is how to set the merge to false.

Nice, `events` is an array so you always have to use one of the array filters.

**Comment by tortoo** [comment]
I added that line and set the merge to false. But it caused an error.

```
Exception during check. wrong number of arguments (given 0, expected 1): /app/app/models/agents/digest_agent.rb:63:in `delete'
/app/app/models/agents/digest_agent.rb:63:in `check'
/app/app/jobs/agent_check_job.rb:7:in `perform'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.0/lib/active_job/execution.rb:39:in `block in perform_now'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/i18n-1.0.1/lib/i18n.rb:284:in `with_locale'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.0/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `instance_exec'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
```

And it's the option:
![image](https://user-images.githubusercontent.com/28673736/45806203-0878a800-bcf3-11e8-9e44-d3c0054b6758.png)

**Comment by tortoo** [comment]
After setting `merge` to `true` it comes back to normal. And I find there are two fields exist after saving and both are the same `true` or `false`.

```
{
  "message": "{{ events | map: 'time' | join: ',' }}",
  "expected_receive_period_in_days": "2",
  "retained_events": "10000",
  "merge_radio": "true",
  "merge": "true"
}
```

**Comment by dsander** [comment]
Oh wow I am blind the brackets around 'events' must not be square:
```ruby
 payload.delete("events") if boolify(interpolated["merge"]) == false
```

**Comment by tortoo** [comment]
It's just a small mistake and you are always our bright light! 🤓

I modified that sentence and now all the original events are gone! It's running perfectly!

After my testing I'll report here.

**Comment by tortoo** [comment]
@dsander I tested the 10000 events in **DigestAgent**.

I saved an event page in `html` format whose size was 2.2 MB. 
Each event was created every 2 minutes. 
Heroku data size was 56 MB before testing and now it's 76.9 MB.

Finally, my Heroku app crashed two times and restored after the restart. My Heroku only has 512M memory. Except this everything looks good.

The **DigestAgent** receives events from an **EventFormattingAgent** and keeps events for 1 hour. 
The merge option is false and the events created only have `message` field. 

And then the problem comes out.
If I delete the events of **EventFormattingAgent** the `message` field of the events created by **DigestAgent** becomes empty. If I keep the events of **EventFormattingAgent** for 1 hour the `message` field of the events created by DigestAgent only gets content created in 1 hour and others all gone. 

After clicking the memory `show` on the bottom of **DigestAgent** the `queue` field has 10000 seven digits number all the time no matter the `keep events` setting of **EventFormattingAgent** is `1 hour` or `forever`.
And the data size of Heroku is always 76.9 MB or more.

My question is where are the events needed by **DigestAgent** stored? It seems they are stored in last agent. I think they should be called the real memory instead of the `Memory` on the bottom of **DigestAgent** with seven digits each.  If those events needed by **DigestAgent** can only be stored in last agent such as **EventFormattingAgent** the rows limit by Heroku will be a trouble.

 I don't know whether I understand right or not and is there a way to store the events instead of the `queue` field with the ordinal number in the Memory of DigestAgent?

**Comment by dsander** [comment]
> I don't know whether I understand right or not and is there a way to store the events instead of the `queue` field with the ordinal number in the Memory of **DigestAgent**?

That would not be practical in most use cases. The `DigestAgent` stores the ids of the Events it will emit the next time it's run in memory. When running it then fetches the Events from the database, thats why you saw an empty Event after deleting the FormattingAgents Events. When `retained_events` is reached it only needs to drop a few ids from it's memory. Storing the whole Event in the memory would create one massive row in the database which could work for PostgreSQL (not sure if Heroku has a limit there) but for mysql would probably reach the column size limit pretty quickly.

I think the "hobby" Heroku database tier is only suited for testing purposes. 10k rows can be reached rather quickly.
