### ISSUE TITLE
while dry run showing below error

### ISSUE THREAD

**Issue by thummaprem** [huginn/huginn#2380]
xception during check. LOGIN failed.: /usr/local/lib/ruby/2.5.0/net/imap.rb:1217:in `get_tagged_response'
/usr/local/lib/ruby/2.5.0/net/imap.rb:1271:in `block in send_command'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/local/lib/ruby/2.5.0/net/imap.rb:1253:in `send_command'
/usr/local/lib/ruby/2.5.0/net/imap.rb:441:in `login'
/root/huginn/app/models/agents/imap_folder_agent.rb:311:in `block in each_unread_mail'
/root/huginn/app/models/agents/imap_folder_agent.rb:426:in `open'
/root/huginn/app/models/agents/imap_folder_agent.rb:309:in `each_unread_mail'
/root/huginn/app/models/agents/imap_folder_agent.rb:202:in `check'
/root/huginn/app/jobs/agent_check_job.rb:7:in `perform'
/usr/local/lib/ruby/gems/2.5.0/gems/activejob-5.2.0/lib/active_job/execution.rb:39:in `block in perform_now'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/usr/local/lib/ruby/gems/2.5.0/gems/i18n-1.0.1/lib/i18n.rb:284:in `with_locale'
/usr/local/lib/ruby/gems/2.5.0/gems/activejob-5.2.0/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `instance_exec'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/lib/ruby/gems/2.5.0/gems/activejob-5.2.0/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/lib/ruby/gems/2.5.0/gems/activejob-5.2.0/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/usr/local/lib/ruby/gems/2.5.0/gems/activejob-5.2.0/lib/active_job/logging.rb:46:in `block in tag_logger'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:28:in `tagged'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `tagged'
/usr/local/lib/ruby/gems/2.5.0/gems/activejob-5.2.0/lib/active_job/logging.rb:46:in `tag_logger'
/usr/local/lib/ruby/gems/2.5.0/gems/activejob-5.2.0/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `instance_exec'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/local/lib/ruby/gems/2.5.0/gems/activejob-5.2.0/lib/active_job/execution.rb:35:in `perform_now'
/usr/local/lib/ruby/gems/2.5.0/gems/activejob-5.2.0/lib/active_job/execution.rb:24:in `block in execute'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/usr/local/lib/ruby/gems/2.5.0/gems/activejob-5.2.0/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/reloader.rb:73:in `block in wrap'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/execution_wrapper.rb:87:in `wrap'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/reloader.rb:72:in `wrap'
/usr/local/lib/ruby/gems/2.5.0/gems/activejob-5.2.0/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `instance_exec'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:136:in `run_callbacks'
/usr/local/lib/ruby/gems/2.5.0/gems/activejob-5.2.0/lib/active_job/execution.rb:22:in `execute'
/usr/local/lib/ruby/gems/2.5.0/gems/activejob-5.2.0/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:78:in `invoke_job'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/local/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block in run'
/usr/local/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:229:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:213:in `block in work_off'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `times'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `work_off'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/local/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `loop'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `block in start'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block in add'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/usr/local/lib/ruby/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:171:in `start'
/root/huginn/lib/delayed_job_worker.rb:6:in `run'
/root/huginn/app/concerns/long_runnable.rb:71:in `block in run!'

**Comment by dsander** [comment]
You are probably sending the wrong login credentials.
