### ISSUE TITLE
Website Agent Parse error

### ISSUE THREAD

**Issue by lindabutlerDS** [huginn/huginn#2393]
I'm trying to get (my first) Website Agent to handle data from an event. Sample event data looks like so:
```
{
  "data": {
    "expand": "schema,names",
    "startAt": 0,
    "maxResults": 2,
    "total": 12,
    "issues": [
      {
        "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
        "id": "123456",
        "self": "https://jira.corp.company.com/rest/api/2/issue/123456",
        "key": "AOS-1448",
        "fields": {
          "summary": "kill A with fire"
        }
      },
      {
        "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
        "id": "1234567",
        "self": "https://jira.corp.company.com/rest/api/2/issue/1234567",
        "key": "AOS-1447",
        "fields": {
          "summary": "Fix problemB"
        }
      }
    ]
  }
}
```

The code for the Website Agent: (I tried to make it as simple as possible for debugging. Once the full JSON is returned I'll worry about correct extract path settings):
```
{
  "expected_update_period_in_days": "8",
  "type": "json",
  "data_from_event": "{{data}}"
}
```

Returned error:
```
[00:00:00] INFO -- : Dry Run started
[00:00:00] ERROR -- : Error when handling event data: 784: unexpected token at '{"expand"=>"schema,names", "startAt"=>0, "maxResults"=>2, "total"=>12, "issues"=>[{"expand"=>"operations,versionedRepresentations,editmeta,changelog,renderedFields", "id"=>"123456", "self"=>"https://jira.corp.company.com/rest/api/2/issue/123456", "key"=>"AOS-1448", "fields"=>{"summary"=>"kill A with fire"}}, {"expand"=>"operations,versionedRepresentations,editmeta,changelog,renderedFields", "id"=>"1234567", "self"=>"https://jira.corp.company.com/rest/api/2/issue/1234567", "key"=>"AOS-1447", "fields"=>{"summary"=>"Fix problemB"}}]}'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
/home/huginn/huginn/app/models/agents/website_agent.rb:640:in `parse'
/home/huginn/huginn/app/models/agents/website_agent.rb:415:in `handle_data'
/home/huginn/huginn/app/models/agents/website_agent.rb:492:in `block in handle_event_data'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/liquid-4.0.0/lib/liquid/context.rb:123:in `stack'
/home/huginn/huginn/app/models/agents/website_agent.rb:490:in `handle_event_data'
/home/huginn/huginn/app/models/agents/website_agent.rb:464:in `block (2 levels) in receive'
/home/huginn/huginn/app/concerns/liquid_interpolatable.rb:62:in `interpolate_with'
/home/huginn/huginn/app/models/agents/website_agent.rb:458:in `block in receive'
/home/huginn/huginn/app/models/agents/website_agent.rb:457:in `each'
/home/huginn/huginn/app/models/agents/website_agent.rb:457:in `receive'
/home/huginn/huginn/app/concerns/sortable_events.rb:99:in `receive'
/home/huginn/huginn/app/concerns/dry_runnable.rb:29:in `dry_run!'
/home/huginn/huginn/app/controllers/agents/dry_runs_controller.rb:41:in `create'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/abstract_controller/base.rb:186:in `process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal/rescue.rb:20:in `process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.1/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/abstract_controller/base.rb:124:in `process'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.1/lib/action_view/rendering.rb:30:in `process'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal.rb:189:in `dispatch'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal.rb:253:in `dispatch'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:31:in `serve'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/journey/router.rb:46:in `block in serve'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/journey/router.rb:33:in `each'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/journey/router.rb:33:in `serve'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:832:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:38:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:97:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/rack/logger.rb:36:in `call_app'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/rack/logger.rb:24:in `block in call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/rack/logger.rb:24:in `call'
/home/huginn/huginn/config/initializers/silence_worker_status_logger.rb:3:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/ssl.rb:66:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/engine.rb:522:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/railtie.rb:185:in `public_send'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/railtie.rb:185:in `method_missing'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/tempfile_reaper.rb:15:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/lint.rb:49:in `_call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/lint.rb:37:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/show_exceptions.rb:23:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/chunked.rb:54:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/content_length.rb:15:in `call'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:562:in `process_client'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:658:in `worker_loop'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:132:in `start'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/bin/unicorn:126:in `<top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bin/unicorn:23:in `load'
/home/huginn/huginn/vendor/bundle/ruby/2.4.0/bin/unicorn:23:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
[00:00:00] INFO -- : Dry Run finished
```

I tried it with and without "extract" settings. I tried all possible "mode" settings. If the type is "text" it extracts the entire content when using the "match all" regex, so the agent itself is functioning. I validated the supplied event data is valid JSON.  For that matter, I get the same 'unexpected token' error just dry running the agent on the sample event:
```
{
  "data": "extractThis"
}
```

Anyone have any ideas what I'm doing wrong? I'm new to Huginn, but I've vainly gone through every possible Google search result that seemed even vaguely likely to be related to this error.

**Comment by lindabutlerDS** [comment]
nm, figured it out. In case anyone else ran into something similar and was puzzled, I had to change my data_from_event line from 
```
 "data_from_event": "{{data}}"
```
to

```
  "data_from_event": "{{data | replace: '=>', ':'}}",
```
after which I could perform extractions on it.

**Comment by dsander** [comment]
Nice! Sorry for the late response [`{{ data | as_object }}`](https://github.com/huginn/huginn/wiki/Formatting-Events-using-Liquid#filters-added-by-huginn) should work as well.

**Comment by GChester** [comment]
Also for another solution @dsander also recommended {{ data | json }} [in another post](https://github.com/huginn/huginn/issues/2529#issuecomment-486551535) and that helped my situation more.
