### ISSUE TITLE
always got timeout error

### ISSUE THREAD

**Issue by Howard-guo** [huginn/huginn#2401]
my website agent always get a timeout error,i don't know what's wrong with it,or can i set timeout value to larger?
>/app/app/models/agents/website_agent.rb:399:in `check_url'
/app/app/models/agents/website_agent.rb:386:in `block in check_urls'
/app/app/models/agents/website_agent.rb:385:in `each'
/app/app/models/agents/website_agent.rb:385:in `check_urls'
/app/app/models/agents/website_agent.rb:483:in `block (2 levels) in receive'
/app/app/concerns/liquid_interpolatable.rb:64:in `interpolate_with'
/app/app/models/agents/website_agent.rb:466:in `block in receive'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/relation/delegation.rb:41:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.1.1/lib/active_record/relation/delegation.rb:41:in `each'
/app/app/models/agents/website_agent.rb:465:in `receive'
/app/app/concerns/sortable_events.rb:99:in `receive'
/app/app/jobs/agent_receive_job.rb:8:in `perform'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.1.1/lib/active_job/execution.rb:37:in `block in perform_now'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/i18n-0.8.1/lib/i18n.rb:257:in `with_locale'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.1.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.1.1/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.1.1/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `block in tag_logger'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.1.1/lib/active_job/logging.rb:44:in `tag_logger'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.1.1/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.1.1/lib/active_job/execution.rb:33:in `perform_now'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.1.1/lib/active_job/execution.rb:22:in `block in execute'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.1.1/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/reloader.rb:68:in `block in wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/reloader.rb:67:in `wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.1.1/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `instance_exec'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.1.1/lib/active_job/execution.rb:20:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.1.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:36:in `perform'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/backend/base.rb:78:in `invoke_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:230:in `block in run'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:229:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:213:in `block in work_off'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:212:in `times'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:212:in `work_off'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/app/vendor/ruby-2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:172:in `loop'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:172:in `block in start'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:79:in `block in add'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.4/lib/delayed/worker.rb:171:in `start'
/app/lib/delayed_job_worker.rb:6:in `run'
/app/app/concerns/long_runnable.rb:71:in `block in run!'

**Comment by Howard-guo** [comment]
@dsander help~~

**Comment by dsander** [comment]
You can set `-e DELAYED_JOB_MAX_RUNTIME=2` to a larger value when creating the docker container. But a webserver taking longer than 2 minutes to complete sounds more like a network connection issue or a problem with the request.

**Comment by Howard-guo** [comment]
> You can set `-e DELAYED_JOB_MAX_RUNTIME=2` to a larger value when creating the docker container. But a webserver taking longer than 2 minutes to complete sounds more like a network connection issue or a problem with the request.

i attempt  modify the website_agent.rb as this:
'''ruby
      log "Fetching #{uri}"
      #response = faraday.get(uri)
      response = faraday.get do |req|
                req.url  uri
                req.options.timeout = 15           # open/read timeout in seconds
                req.options.open_timeout = 5       # connection open timeout in seconds
      end
      log "response: #{response.body}"
'''
and set the DELAYED_JOB_MAX_RUNTIME with command:
`heroku config:set DELAYED_JOB_MAX_RUNTIME=5`

and all this have no effect

**Comment by dsander** [comment]
>  req.options.timeout = 15 # open/read timeout in seconds req.options.open_timeout = 5 # connection open timeout in seconds

Setting those will actually reduce the timeout, per default the WebsiteAgent does not have a timeout (it is only controlled by `DELAYED_JOB_MAX_RUNTIME` which is in minutes), your settings are in seconds. So the request will timeout in 5 or 15 seconds instead of 2 minutes.
