### ISSUE TITLE
Install fails on `bundle install` in NixOS

### ISSUE THREAD

**Issue by UncoveredBulb** [huginn/huginn#2403]
tried following the instructions in https://github.com/huginn/huginn/blob/master/README.md and got up to the instruction bundle install before it failed. When running `bundle install` I get the error message:

```
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32`.                                                                                              
Fetching gem metadata from https://rubygems.org/......
Using rake 12.3.1
Using ace-rails-ap 2.0.1
Using concurrent-ruby 1.0.5
Using i18n 1.0.1
Using minitest 5.11.3
Using thread_safe 0.3.6
Using tzinfo 1.2.5
Using activesupport 5.2.0
Using builder 3.2.3
Using erubi 1.7.1
Using mini_portile2 2.3.0
Fetching nokogiri 1.8.2
Installing nokogiri 1.8.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/mj/huginn/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.8.2/ext/nokogiri
/nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/bin/ruby -r ./siteconf20181027-25065-14hc7ya.rb extconf.rb
--use-system-libraries
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/bin/$(RUBY_BASE_NAME)
        --help
        --clean
/nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an
executable file. (RuntimeError)
You have to install development tools first.
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/mkmf.rb:574:in `block in try_compile'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/mkmf.rb:521:in `with_werror'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/mkmf.rb:574:in `try_compile'
        from extconf.rb:138:in `nokogiri_try_compile'
        from extconf.rb:162:in `block in add_cflags'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/mkmf.rb:632:in `with_cflags'
        from extconf.rb:161:in `add_cflags'
        from extconf.rb:410:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/mj/huginn/vendor/bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0/nokogiri-1.8.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/mj/huginn/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.8.2 for inspection.
Results logged to /home/mj/huginn/vendor/bundle/ruby/2.5.0/extensions/x86_64-linux/2.5.0/nokogiri-1.8.2/gem_make.out

An error occurred while installing nokogiri (1.8.2), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.8.2' --source 'https://rubygems.org/'` succeeds before bundling.                           

In Gemfile:
  bootstrap-kaminari-views was resolved to 0.0.5, which depends on
    rails was resolved to 5.2.0, which depends on
      actioncable was resolved to 5.2.0, which depends on
        actionpack was resolved to 5.2.0, which depends on
          actionview was resolved to 5.2.0, which depends on
            rails-dom-testing was resolved to 2.0.3, which depends on
              nokogiri
```

I tried (as per instruction) `gem install nokogiri -v '1.8.2' --source 'https://rubygems.org/'`

which returned:

```
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: /home/mj/.gem/ruby/2.5.0/gems/nokogiri-1.8.2/ext/nokogiri
/nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/bin/ruby -r ./siteconf20181027-25531-1a68507.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/bin/$(RUBY_BASE_NAME)
        --help
        --clean
/nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/mkmf.rb:574:in `block in try_compile'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/mkmf.rb:521:in `with_werror'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/mkmf.rb:574:in `try_compile'
        from extconf.rb:138:in `nokogiri_try_compile'
        from extconf.rb:162:in `block in add_cflags'
        from /nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib/ruby/2.5.0/mkmf.rb:632:in `with_cflags'
        from extconf.rb:161:in `add_cflags'
        from extconf.rb:410:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/mj/.gem/ruby/2.5.0/extensions/x86_64-linux/2.5.0/nokogiri-1.8.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/mj/.gem/ruby/2.5.0/gems/nokogiri-1.8.2 for inspection.
Results logged to /home/mj/.gem/ruby/2.5.0/extensions/x86_64-linux/2.5.0/nokogiri-1.8.2/gem_make.out
```
The log files report:
/home/mj/.gem/ruby/2.5.0/extensions/x86_64-linux/2.5.0/nokogiri-1.8.2/mkmf.log

```
"gcc -o conftest -I/nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/include/ruby-2.5.0/x86_64-linux -I/nix/store/whp7b9fdn8z4iwn
48w8fhlqjdnj1p9pl-ruby-2.5.1/include/ruby-2.5.0/ruby/backward -I/nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/include/ruby-2.
5.0 -I.    -O3 -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wno-tautolo
gical-compare -Wno-parentheses-equality -Wno-constant-logical-operand -Wno-self-assign -Wunused-variable -Wimplicit-int -Wpointer-arit
h -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wmisleading-indentation -Wn
o-packed-bitfield-compat -Wsuggest-attribute=noreturn -Wsuggest-attribute=format -Wimplicit-fallthrough=0 -Wduplicated-cond -Wrestrict
  -fPIC  conftest.c  -L. -L/nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib -Wl,-rpath,/nix/store/whp7b9fdn8z4iwn48w8fhlqjdn
j1p9pl-ruby-2.5.1/lib -L. -fstack-protector -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-r
uby-2.5.1/lib -L/nix/store/whp7b9fdn8z4iwn48w8fhlqjdnj1p9pl-ruby-2.5.1/lib -lruby  -lpthread -ldl -lcrypt -lm   -lc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

The operating system is NixOS 18.09

Any ideas?

Thanks!

**Comment by dsander** [comment]
I think it is missing the ruby header files. On other distributions the package would be called `ruby-dev` or something similar, not sure about nixos though.

**Comment by Taffer** [comment]
@dsander is correct, that's exactly what I had to do yesterday on Ubuntu:

`sudo apt-get install ruby-dev`

and try again.
