### ISSUE TITLE
problem： can't find gem bundler (>= 0.a) with executable bundle ；Please help solve this problem，thank you

### ISSUE THREAD

**Issue by txj347** [huginn/huginn#2458]
After completing the official steps provided, the system prompts the following questions:
the office steps is:https://github.com/huginn/huginn/blob/master/doc/manual/installation.md
root@vultr:/home/huginn/huginn# sudo -u huginn -H bundle install --deployment --without development test
Traceback (most recent call last):
	2: from /usr/local/bin/bundle:23:in `<main>'
	1: from /usr/local/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/local/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle 
(Gem::GemNotFoundException)

root@vultr:~/ruby-2.5.1# ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
root@vultr:~/ruby-2.5.1# gem -v
2.7.6
root@vultr:~/ruby-2.5.1# bundler -v
Bundler version 2.0.1

**Comment by dsander** [comment]
Hi,

I think you are hit by a bug in rubygems: https://bundler.io/blog/2019/01/04/an-update-on-the-bundler-2-release.html

Can you try if running `sudo gem update --system` fixes the issue?

If it doesn't try

```
sudo gem uninstall bundler
sudo gem install bundler -v '1.17.3'
```

**Comment by txj347** [comment]
I am a beginner of linux, but I am very interested in the project huginn. Thank you for your last reply, but the next step has problems, as shown below:

Initialize Database
sudo -u huginn -H bundle exec rake db:create RAILS_ENV=production
Could not find nokogiri-1.8.5 in any of the sources
Run `bundle install` to install missing gems.

root@vultr:/home/huginn/huginn# nokogiri -v
# Nokogiri (1.8.5)                                                               
root@vultr:/home/huginn/huginn# bundler -v
Bundler version 1.17.3
root@vultr:/home/huginn/huginn# ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
root@vultr:/home/huginn/huginn# gem -v
2.7.6

**Comment by dsander** [comment]
Did you re-run `sudo -u huginn -H bundle install --deployment --without development test` after installing bundler?

**Comment by txj347** [comment]
I tried to follow the official steps, using Huginn on pre-deployed Docker containers（https://github.com/huginn/huginn/blob/master/doc/docker/install.Md）。 the following problems also occurred:
  The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32`.
  Bundle complete! 110 Gemfile dependencies, 184 gems now installed.
Gems in the groups test and development were not installed.
Bundled gems are installed into `./vendor/bundle`

**Comment by txj347** [comment]
Dear dsander:
I am Chinese and I am very eager to know how to install huginn in two ways that from source code installation and using Huginn on pre-deployed Docker containers. Their address is https://github.com/huginn/huginn/blob/master/doc/manual/installation.md and https://github.com/huginn/huginn/blob/master/doc/docker/install. Md. I tried both of these installation methods, but both failed.

Limited by my level of knowledge and communication costs. Maybe you can install huginn for me in the above two ways. I installed huginn through the vultr.com server and the installation tool is xshell5. I will tell you the address and password of the two servers which does not have any huginn installed. After installing huginn for me, please send me the complete code of the installation process. After comparison,I may be able to find out why I did not install successfully.

  If you agree with my suggestion, Please send me your email address or other contact information.I will email you the IP address and password. My email address is wupingping347@gmail.com.
  Best wishes

**Comment by dsander** [comment]
> Using builder 3.2.3
> Using erubi 1.7.1
> Using mini_portile2 2.3.0
> Fetching nokogiri 1.8.5
> Installing nokogiri 1.8.5 with native extensions
> Killed

That reads like the server is running out of memory. If your server has less than 2GB of RAM follow these steps and set up at least 1GB of swap: https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-18-04

**Comment by M-Younes** [comment]
Hi,
I was facing the same issue. Running `sudo gem update --system` solved it for me.

here is me `gem emv` for reference.

```RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 2.5.1 (2018-03-29 patchlevel 57) [x86_64-darwin18]
  - INSTALLATION DIRECTORY: /Users/younes/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0
  - USER INSTALLATION DIRECTORY: /Users/younes/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /Users/younes/.rbenv/versions/2.5.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/younes/.rbenv/versions/2.5.1/bin
  - SPEC CACHE DIRECTORY: /Users/younes/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/younes/.rbenv/versions/2.5.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-18
  - GEM PATHS:
     - /Users/younes/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0
     - /Users/younes/.gem/ruby/2.5.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/younes/.rbenv/versions/2.5.1/bin
     - /usr/local/Cellar/rbenv/1.1.1/libexec
     - /Users/younes/.rbenv/shims
     - /Users/younes/bin
     - /usr/local/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin```

**Comment by huy9903098** [comment]
Hi,
I also solved it by running sudo gem update --system too
