### ISSUE TITLE
Problems with step "Install Gems" on Raspberry Pi 3 Model B+

### ISSUE THREAD

**Issue by IAMEVANHE** [huginn/huginn#2459]
I am trying to install Huginn following the manual installation guide on my Pi, and I am stuck at "Install Gem". Here is what I got from bash shell:

```
root@pi:/home/huginn/huginn# bundle -v
Traceback (most recent call last):
        2: from /usr/local/bin/bundle:23:in `<main>'
        1: from /usr/local/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/local/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
root@pi:/home/huginn/huginn# sudo -u huginn -H bundle install --deployment --without development test
Traceback (most recent call last):
        2: from /usr/local/bin/bundle:23:in `<main>'
        1: from /usr/local/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/local/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
root@pi:/home/huginn/huginn# cd .. && bundle -v
Bundler version 2.0.1
```
The bundle / bundler seems to be working fine outside of the path "/home/huginn/huginn". Could anyone kindly suggest?

**Comment by IAMEVANHE** [comment]
It's problem with Ruby. I have removed the ruby-2.5.1 installed by make as per "2. Ruby" from the maual instalation guide, and use Ruby from "`apt install ruby-dev`"
