### ISSUE TITLE
Issue with formatter agent and boolean expressions

### ISSUE THREAD

**Issue by dobseh** [huginn/huginn#2479]
Hi

I have the following lines in an Event Formatting Agent that takes it's input from the Weather Agent using the Dark Sky api. I'm trying to convert the numerical value of degrees that are returned into North, South, East and West. I've tried using simple IF statements with operators like

```
{% if avewind.degrees >= '316' OR avewind.degrees <= '45' %}north{% endif %}
{% if avewind.degrees >= '46' and avewind.degrees <= '125' %}east{% endif %}
{% if avewind.degrees >= '126' and avewind.degrees <= '230' %}south{% endif %}
{% if avewind.degrees >= '231' and avewind.degrees <= '315' %}west{% endif %}
```
I've also tried using ELSE IF's, changing the order of IF statements and breaking up the numbers less than 100 into their own statements.
```
{% if avewind.degrees >= '316' %}north{% else if avewind.degrees >= '46' and avewind.degrees <= '99' %}east{% else if avewind.degrees >= '100' and avewind.degrees <= '125' %}east{% else if avewind.degrees >= '126' and avewind.degrees <= '230' %}south{% else if avewind.degrees >= '231' and avewind.degrees <= '315' %}west{% else if avewind.degrees >= '0' AND avewind.degrees <= '45' %}north{% endif %}
```
Coding isn't my subject area at all, so I have probably overlooked something blindingly obvious, but any help would be greatfully received!

**Comment by dsander** [comment]
Hi,

try removing the `'` quotes around the numbers. If that does not help please post the whole json configuration of your Agent.

**Comment by dobseh** [comment]
Thanks for responding, if I remove the quotes the dry run errors with the following:

```
[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Dry Run failed
[00:00:00] ERROR -- : Exception during dry-run. Liquid error: comparison of String with 360 failed: /app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/condition.rb:117:in `rescue in interpret_condition'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/condition.rb:114:in `interpret_condition'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/condition.rb:44:in `evaluate'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/tags/if.rb:43:in `block (2 levels) in render'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/tags/if.rb:42:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/tags/if.rb:42:in `block in render'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/context.rb:123:in `stack'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/tags/if.rb:41:in `render'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:109:in `render_node'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:88:in `block in render'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
/app/vendor/bundle/ruby/2.5.0/gems/liquid-4.0.0/lib/liquid/template.rb:220:in `render!'
/app/app/concerns/liquid_interpolatable.rb:106:in `block (2 levels) in interpolate_string'
/app/app/concerns/liquid_interpolatable.rb:105:in `catch'
/app/app/concerns/liquid_interpolatable.rb:105:in `block in interpolate_string'
/app/app/concerns/liquid_interpolatable.rb:59:in `interpolate_with'
/app/app/concerns/liquid_interpolatable.rb:104:in `interpolate_string'
/app/app/concerns/liquid_interpolatable.rb:83:in `block in interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:59:in `interpolate_with'
/app/app/concerns/liquid_interpolatable.rb:80:in `interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:86:in `block (2 levels) in interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:85:in `each'
/app/app/concerns/liquid_interpolatable.rb:85:in `each_with_object'
/app/app/concerns/liquid_interpolatable.rb:85:in `block in interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:59:in `interpolate_with'
/app/app/concerns/liquid_interpolatable.rb:80:in `interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:86:in `block (2 levels) in interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:85:in `each'
/app/app/concerns/liquid_interpolatable.rb:85:in `each_with_object'
/app/app/concerns/liquid_interpolatable.rb:85:in `block in interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:59:in `interpolate_with'
/app/app/concerns/liquid_interpolatable.rb:80:in `interpolate_options'
/app/app/concerns/liquid_interpolatable.rb:99:in `block in interpolated'
/app/app/concerns/liquid_interpolatable.rb:59:in `interpolate_with'
/app/app/concerns/liquid_interpolatable.rb:97:in `interpolated'
/app/app/models/agents/event_formatting_agent.rb:130:in `block (3 levels) in receive'
/app/app/concerns/liquid_interpolatable.rb:64:in `interpolate_with'
/app/app/models/agents/event_formatting_agent.rb:212:in `apply_compiled_matchers'
/app/app/models/agents/event_formatting_agent.rb:129:in `block (2 levels) in receive'
/app/app/concerns/liquid_interpolatable.rb:64:in `interpolate_with'
/app/app/models/agents/event_formatting_agent.rb:128:in `block in receive'
/app/app/models/agents/event_formatting_agent.rb:127:in `each'
/app/app/models/agents/event_formatting_agent.rb:127:in `receive'
/app/app/concerns/dry_runnable.rb:29:in `dry_run!'
/app/app/controllers/agents/dry_runs_controller.rb:41:in `create'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/abstract_controller/base.rb:194:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/notifications.rb:168:in `block in instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/notifications.rb:168:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1.1/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/abstract_controller/base.rb:134:in `process'
/app/vendor/bundle/ruby/2.5.0/gems/actionview-5.2.1.1/lib/action_view/rendering.rb:32:in `process'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal.rb:191:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_controller/metal.rb:252:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/journey/router.rb:35:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/journey/router.rb:35:in `serve'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/routing/route_set.rb:840:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/tempfile_reaper.rb:15:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/etag.rb:25:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/conditional_get.rb:38:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1.1/lib/rails/rack/logger.rb:38:in `call_app'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1.1/lib/rails/rack/logger.rb:26:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/tagged_logging.rb:71:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1.1/lib/rails/rack/logger.rb:26:in `call'
/app/config/initializers/silence_worker_status_logger.rb:3:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.1.1/lib/action_dispatch/middleware/static.rb:127:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.1.1/lib/rails/engine.rb:524:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/handler/webrick.rb:86:in `service'
/usr/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
/usr/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
/usr/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'

```

I thought maybe that the issue was a string to integer one, given the error near the top, so I tried adding `{% assign avewind.degrees = avewind.degrees | plus: 0 %} ` prior to the wind direction section, but that didn't appear to help. 

This is my first attempt at an agent, so there are likely better ways of doing this, but the current itteration looks like:

```
{
  "instructions": {
    "message": "The weather for tomorrow {{date.day}}/{{date.month}}/{{date.year}},  will be; {{conditions}}.<br />&nbsp;<br />The forecast high is {{high.celsius}}°C at around {{high.epoch_apparent | date: '%H:%M'}} with a low of {{low.celsius}}°C at around {{low.epoch_apparent | date: '%H:%M'}}. <br />&nbsp;<br />There is a {{precip.probability | times: 100 | remove: '.0'}}% chance of {{ precip.type | regex_replace: '^$', 'precipitation' }}, with a peak likelihood at {{precip.intensity_max_epoch | date: '%H:%M'}} <br />&nbsp;<br /> Visibility will be approximately {{visibility}} miles, there will be {{cloudCover | times: 100 | remove: '.0'}}% cloud cover and the average wind speed will be {{avewind.mph}} mph blowing from the {% if avewind.degrees <= 360 and avewind.degrees >= 316 %}north{% endif %}{% if avewind.degrees <= 45 and avewind.degrees >= 0 %}north{% endif %}{% if avewind.degrees <= 99 and avewind.degrees >= 46 %}east{% endif %}{% if avewind.degrees <= 125 and avewind.degrees >= 100 %}east{% endif %}{% if avewind.degrees <= 230 and avewind.degrees >= 126 %}south{% endif %}{% if avewind.degrees <= 315 and avewind.degrees >= 231 %}west{% endif %}. <br />&nbsp;<br /> Sunrise time is {{sunriseTime | date: '%H:%M'}} and sunset will be {{sunsetTime | date: '%H:%M'}}",
    "subject": "The weather for {{date.day}}/{{date.month}}/{{date.year}}",
    "agent": "{{agent.type}}"
  },
  "matchers": [],
  "mode": "clean"
}
```

This is the JSON for the dry run as well, I've changed the location tag  to zero's, but it's actually my home location in the real one.

```
{
  "date": {
    "epoch": "1548633600",
    "pretty": "12:00 AM GMT on January 28, 2019",
    "day": 28,
    "month": 1,
    "year": 2019,
    "yday": 28,
    "hour": 0,
    "min": "00",
    "sec": 0,
    "isdst": 0,
    "monthname": "January",
    "monthname_short": "Jan",
    "weekday_short": "Mon",
    "weekday": "Monday",
    "ampm": "AM",
    "tz_short": "GMT"
  },
  "period": 1,
  "high": {
    "fahrenheit": "43",
    "epoch": "1548684000",
    "fahrenheit_apparent": "36",
    "epoch_apparent": "1548684000",
    "celsius": "6"
  },
  "low": {
    "fahrenheit": "33",
    "epoch": "1548716400",
    "fahrenheit_apparent": "24",
    "epoch_apparent": "1548662400",
    "celsius": "1"
  },
  "conditions": "Mostly cloudy overnight.",
  "icon": "partly-cloudy-night",
  "avehumidity": 70,
  "sunriseTime": "1548661495",
  "sunsetTime": "1548693943",
  "moonPhase": "0.77",
  "precip": {
    "intensity": "0",
    "intensity_max": "0.0002",
    "intensity_max_epoch": "1548680400",
    "probability": "0",
    "type": null
  },
  "dewPoint": "27.86",
  "avewind": {
    "mph": "14",
    "kph": "22",
    "degrees": "111"
  },
  "visibility": "10",
  "cloudCover": "0.03",
  "pressure": "1005.49",
  "ozone": "342.73",
  "location": "00.000000,-00.000"
}

**Comment by dsander** [comment]
> Liquid error: comparison of String with 360 failed

That is annoying. The only work around I could find was `{% assign var1 = var1 | plus: 0 %}` which basically converts `var1` into a number. I think you will need to do that for every variable you are using in a comparison.

**Comment by dobseh** [comment]
> > Liquid error: comparison of String with 360 failed
> 
> That is annoying. The only work around I could find was `{% assign var1 = var1 | plus: 0 %}` which basically converts `var1` into a number. I think you will need to do that for every variable you are using in a comparison.

Yeah, as mentioned above, I already tried that and it doesn't make any difference, it still produces the `comparison with string` error. I'll ask the same question on the Liquid Github.

**Comment by dsander** [comment]
Sorry I have over read that. It is possible that `assign` only works with "top level" variables. Can you try to assign the nested data to new variables? `{% assign degrees = avewind.degrees | plus: 0 %}` and then use `degrees` in your comparisons.

**Comment by dobseh** [comment]
> 
> 
> Sorry I have over read that. It is possible that `assign` only works with "top level" variables. Can you try to assign the nested data to new variables? `{% assign degrees = avewind.degrees | plus: 0 %}` and then use `degrees` in your comparisons.

That's got it working, thank you for the help! Is the fact that it works this way something that should be on the Huginn and/or Liquid wiki? I did a load of googling and the information on how these statements are meant to function is really limited and often contradictory.

Will close the issue now.
