### ISSUE TITLE
db:create fails during database initialization with syntaxerror

### ISSUE THREAD

**Issue by ch40s** [huginn/huginn#2481]
Hi all, following the installation guide I'm getting the following error when I'm attempting to initialize the database, any idea how to resolve this?

```
# sudo -u huginn -H bundle exec rake db:create RAILS_ENV=production
rake aborted!
SyntaxError: /huginn/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/constants.rb:1: syntax error, unexpected tFID, expecting keyword_do or '{' or '('
er-voltage detected! (0x00050005)
           ^~~~~~~~~
/huginn/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/constants.rb:2: syntax error, unexpected tINTEGER, expecting end-of-input
Dec 19 00:48:42 HP kernel: [2276084.05...
       ^~
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/huginn/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/map.rb:2:in `<top (required)>'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:5:in `<top (required)>'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache.rb:39:in `setup'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap.rb:24:in `setup'
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/setup.rb:33:in `<top (required)>'
/huginn/config/boot.rb:7:in `require'
/huginn/config/boot.rb:7:in `<top (required)>'
/huginn/config/application.rb:1:in `require_relative'
/huginn/config/application.rb:1:in `<top (required)>'
/huginn/Rakefile:5:in `require_relative'
/huginn/Rakefile:5:in `<top (required)>'
/huginn/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)

```

**Comment by ch40s** [comment]
My system details can be found below:
```
# uname -a
Linux HP 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
# cat /etc/debian_version
9.6
# bundle -v
Bundler version 1.17.3
# mysql --version
mysql  Ver 15.1 Distrib 10.1.37-MariaDB, for debian-linux-gnueabihf (armv8l) using readline 5.2
# ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [armv7l-linux-eabihf]
```

**Comment by dsander** [comment]
Please check the contents of `/huginn/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/constants.rb`, the error messages reads like something wrong with your system.

You can try to delete `/huginn/vendor/bundle` and rerun [`sudo -u huginn -H bundle install --deployment --without development test`](https://github.com/huginn/huginn/blob/master/doc/manual/installation.md#install-gems)

**Comment by ch40s** [comment]
Thanks @dsander , I deleted the bundle directory and reran the command you mentioned.

The process was aborted again because of the following:
```
# sudo -u huginn -H bundle exec rake db:create RAILS_ENV=production
/huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:18: [BUG] Bus Error at 0x028a73a2
ruby 2.5.1p57 (2018-03-29 revision 63029) [armv7l-linux-eabihf]

-- Control frame information -----------------------------------------------
c:0124 p:---- s:0653 e:000652 CFUNC  :load_from_binary
c:0123 p:0014 s:0648 e:000647 METHOD /huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:18 [FINISH]
c:0122 p:---- s:0642 e:000641 CFUNC  :fetch
c:0121 p:0069 s:0635 e:000634 METHOD /huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/compile_cache/iseq.rb:37 [FINISH]
c:0120 p:---- s:0629 e:000628 CFUNC  :require
c:0119 p:0013 s:0624 e:000623 BLOCK  /huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21
c:0118 p:0005 s:0621 e:000620 METHOD /huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65
c:0117 p:0023 s:0612 e:000611 METHOD /huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20
c:0116 p:0052 s:0606 e:000605 METHOD /huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29
c:0115 p:0009 s:0600 e:000599 BLOCK  /huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:287
c:0114 p:0049 s:0597 e:000596 METHOD /huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:253
c:0113 p:0011 s:0591 e:000590 METHOD /huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:287
c:0112 p:0013 s:0585 e:000584 TOP    /huginn/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/thread_pool_executor.rb:2 [FINISH]
c:0111 p:---- s:0582 e:000581 CFUNC  :require
c:0110 p:0013 s:0577 e:000576 BLOCK  /huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21
c:0109 p:0005 s:0574 e:000573 METHOD /huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65
c:0108 p:0023 s:0565 e:000564 METHOD /huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20
c:0107 p:0052 s:0559 e:000558 METHOD /huginn/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29
c:0106 p:0009 s:0553 e:000552 BLOCK  /huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:287
c:0105 p:0049 s:0550 e:000549 METHOD /huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:253
c:0104 p:0011 s:0544 e:000543 METHOD /huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.1.1/lib/active_support/dependencies.rb:287
c:0103 p:0013 s:0538 e:000537 TOP    /huginn/vendor/bundle/ruby/2.5.0/gems/concurrent-ruby-1.1.3/lib/concurrent/executor/cached_thread_pool.rb:2 [FINISH]
...
[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Aborted
```

**Comment by ch40s** [comment]
I resolved the bus error above by editing `huginn/config/boot.rb` and commenting out the following line:
```
#require 'bootsnap/setup' if Process.euid != 0 # Speed up boot time by caching expensive operations.
```

**Comment by dsander** [comment]
It seems to be a bug in Ruby on arm https://github.com/Shopify/bootsnap/issues/67
