### ISSUE TITLE
"\xE7" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by lecooliver** [huginn/huginn#2538]
I have an IMAP agent that receives the emails and another that sends to my Rocket Chat.

**IMAP agent:**
```ruby
{
  "expected_update_period_in_days": "1",
  "host": "imap.bol.com.br",
  "ssl": true,
  "username": "login@bol.com.br",
  "password": "password",
  "folders": [
    "INBOX"
  ],
  "mark_as_read": true,
  "force_encoding": "utf-8",
  "conditions": {}
}
```

**Slack agent:**
```ruby
{
  "webhook_url": "https://chat.domain.com/hooks/token-url",
  "channel": "#channel",
  "username": "user",
  "message": "{{body}}",
  "icon": "",
  "force_encoding": "utf-8"
}
```

The agents are working (and I receiving the messages on Rocket Chat), but sometimes I'm getting the following error message (on Huginn):
```
E, [2019-05-21T04:01:06.420013 #1151] ERROR -- : [ActiveJob] [AgentCheckJob] [91f52a63-22fe-4612-86e8-a5a4628a4079] Error performing AgentCheckJob (Job ID: 91f52a63-22fe-4612-86e8-a5a4628a4079) from DelayedJob(default) in 55709.01ms: Encoding::UndefinedConversionError ("\xE7" from ASCII-8BIT to UTF-8):
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/core_ext/object/json.rb:38:in `encode'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/core_ext/object/json.rb:38:in `to_json'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/core_ext/object/json.rb:38:in `to_json'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/json-1.8.6/lib/json/common.rb:394:in `dump'
/home/huginn/huginn/lib/json_with_indifferent_access.rb:10:in `dump'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/type/serialized.rb:29:in `serialize'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/type/helpers/mutable.rb:8:in `cast'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute.rb:175:in `type_cast'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute.rb:42:in `value'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute.rb:156:in `changed_from_assignment?'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute.rb:59:in `changed?'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute_mutation_tracker.rb:49:in `changed?'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute_mutation_tracker.rb:15:in `block in changed_attribute_names'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute_mutation_tracker.rb:15:in `select'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute_mutation_tracker.rb:15:in `changed_attribute_names'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/attribute_methods/dirty.rb:114:in `changed_attribute_names_to_save'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/associations/association.rb:182:in `initialize_attributes'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/associations/association.rb:285:in `block in build_record'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/core.rb:316:in `initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/inheritance.rb:66:in `new'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/inheritance.rb:66:in `new'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/reflection.rb:154:in `build_association'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/associations/association.rb:284:in `build_record'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/associations/collection_association.rb:108:in `build'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/associations/collection_proxy.rb:319:in `build'
/home/huginn/huginn/app/models/agent.rb:112:in `build_event'
/home/huginn/huginn/app/models/agent.rb:121:in `create_event'
/home/huginn/huginn/app/concerns/dry_runnable.rb:88:in `create_event'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:310:in `block in check'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:392:in `block (3 levels) in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:391:in `each'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:391:in `block (2 levels) in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:344:in `each'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:344:in `block in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:448:in `open'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:333:in `each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:213:in `check'
/home/huginn/huginn/app/jobs/agent_check_job.rb:7:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:39:in `block in perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/i18n-1.6.0/lib/i18n.rb:297:in `with_locale'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:46:in `block in tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:46:in `tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:38:in `perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:24:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/reloader.rb:73:in `block in wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/reloader.rb:72:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:22:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:78:in `invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/local/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block in run'
/usr/local/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:229:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:213:in `block in work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `times'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/local/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `loop'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `block in start'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block in add'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:171:in `start'
/home/huginn/huginn/lib/delayed_job_worker.rb:6:in `run'
/home/huginn/huginn/app/concerns/long_runnable.rb:71:in `block in run!'
```

**Comment by dsander** [comment]
Is the locale on your server configure to utf-8? `locale` should output something like this:

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=en_US.UTF-8
```

**Comment by lecooliver** [comment]
```
ubuntu@Huginn:~$ sudo -u huginn -H locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=pt_BR.UTF-8
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME=pt_BR.UTF-8
LC_ADDRESS=pt_BR.UTF-8
LC_TELEPHONE=pt_BR.UTF-8
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION=pt_BR.UTF-8
LC_ALL=
```

**Comment by dsander** [comment]
That looks good to me. I wonder if the issue comes from a malformatted email, the imap server not properly encoding the data or a bug in one of the dependencies we are using. As I don't see any encoding related code in the ImapFolderAgent I think we completely rely on our dependencies to parse the mails.

@knu Have you ever noticed encoding issues with your IMAP Agents? I have never used the Agent myself.

**Comment by derd3000** [comment]
This bug is still present I think. I also got this bug when checking an imap account and sending events to telegram.

This is my locale output:
````
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
````


This is the log entry:
````
Exception during check. "\xE2" from ASCII-8BIT to UTF-8: /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/core_ext/object/json.rb:39:in `to_json'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/core_ext/object/json.rb:39:in `to_json'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/json-2.3.0/lib/json/common.rb:224:in `generate'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/json-2.3.0/lib/json/common.rb:224:in `generate'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/json-2.3.0/lib/json/common.rb:394:in `dump'
/home/huginn/huginn/lib/json_with_indifferent_access.rb:10:in `dump'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/type/serialized.rb:29:in `serialize'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/type/helpers/mutable.rb:8:in `cast'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute.rb:174:in `type_cast'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute.rb:42:in `value'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute.rb:155:in `changed_from_assignment?'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute.rb:59:in `changed?'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute_mutation_tracker.rb:76:in `attribute_changed?'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute_mutation_tracker.rb:46:in `changed?'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute_mutation_tracker.rb:16:in `block in changed_attribute_names'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute_mutation_tracker.rb:16:in `select'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute_mutation_tracker.rb:16:in `changed_attribute_names'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/attribute_methods/dirty.rb:145:in `changed_attribute_names_to_save'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/associations/association.rb:187:in `initialize_attributes'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/associations/association.rb:322:in `block in build_record'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/core.rb:327:in `initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/inheritance.rb:70:in `new'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/inheritance.rb:70:in `new'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/reflection.rb:158:in `build_association'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/associations/association.rb:321:in `build_record'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/associations/collection_association.rb:108:in `build'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/associations/collection_proxy.rb:316:in `build'
/home/huginn/huginn/app/models/agent.rb:112:in `build_event'
/home/huginn/huginn/app/models/agent.rb:121:in `create_event'
/home/huginn/huginn/app/concerns/dry_runnable.rb:88:in `create_event'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:310:in `block in check'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:392:in `block (3 levels) in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:391:in `each'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:391:in `block (2 levels) in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:344:in `each'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:344:in `block in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:448:in `open'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:333:in `each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:213:in `check'
/home/huginn/huginn/app/jobs/agent_check_job.rb:7:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:40:in `block in perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.2/lib/i18n.rb:313:in `with_locale'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:25:in `block (4 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:24:in `block (3 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:45:in `block in tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:45:in `tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:21:in `block (2 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:39:in `perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:25:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/railtie.rb:43:in `block (4 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/reloader.rb:72:in `block in wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/reloader.rb:71:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/railtie.rb:42:in `block (3 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:23:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:78:in `invoke_job'
/home/hug
````
