### ISSUE TITLE
Exception during check. end of file reached: /usr/local/lib/ruby/2.5.0/net/imap.rb:1211:in `get_tagged_response'

### ISSUE THREAD

**Issue by lecooliver** [huginn/huginn#2540]
I'm getting the following error message:
```
Agent#8: Connecting to imap.bol.com.br via SSL
Agent#8: Logging in as mailaccount@bol.com.br
Agent#8: Selecting the folder: INBOX
Agent#8: 1527 new mails
Agent#8: Connection closed
Agent#8: Exception during check. end of file reached: /usr/local/lib/ruby/2.5.0/net/imap.rb:1211:in `get_tagged_response'
/usr/local/lib/ruby/2.5.0/net/imap.rb:1271:in `block in send_command'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/local/lib/ruby/2.5.0/net/imap.rb:1253:in `send_command'
/usr/local/lib/ruby/2.5.0/net/imap.rb:1439:in `block in fetch_internal'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/local/lib/ruby/2.5.0/net/imap.rb:1434:in `fetch_internal'
/usr/local/lib/ruby/2.5.0/net/imap.rb:823:in `uid_fetch'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:467:in `uid_fetch'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:471:in `uid_fetch_mails'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:391:in `block (2 levels) in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:344:in `each'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:344:in `block in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:448:in `open'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:333:in `each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:213:in `check'
/home/huginn/huginn/app/jobs/agent_check_job.rb:7:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:39:in `block in perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/i18n-1.6.0/lib/i18n.rb:297:in `with_locale'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:46:in `block in tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:46:in `tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:38:in `perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:24:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/reloader.rb:73:in `block in wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/reloader.rb:72:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:22:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:78:in `invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/local/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block in run'
/usr/local/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:229:in `run'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:213:in `block in work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `times'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `work_off'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/local/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `loop'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `block in start'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block in add'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:171:in `start'
/home/huginn/huginn/lib/delayed_job_worker.rb:6:in `run'
/home/huginn/huginn/app/concerns/long_runnable.rb:71:in `block in run!'
```

**Comment by dsander** [comment]
It looks like the exception happens while the Agent fetches the uids of unread mails. It is possible that that request is taking too long either for the IMAP server or the Agent. Can you try to run the Agent in a way that reduces the amount of unread mails to a smaller number?

**Comment by lecooliver** [comment]
I decreased the number of messages and worked for a moment, but I got the message again: ["\xE7" from ASCII-8BIT to UTF-8](https://github.com/huginn/huginn/issues/2538)
