### ISSUE TITLE
Error when trying to send from Post Agent to Google Analytics

### ISSUE THREAD

**Issue by ygdar** [huginn/huginn#2550]
When i trying to send any simple request to google analytics, like this
```
{
  "post_url": "https://www.google-analytics.com/collect",
  "content_type": "form",
  "expected_receive_period_in_days": "1",
  "method": "post",
  "payload": {},
  "headers": {},
  "emit_events": "true",
  "no_merge": "true",
  "output_mode": "merge",
  "keep_event": "true"
}
```
i'm getting an error
Can i ignore response body and read only header status, and second question -- can i use ruby language in my agents?

Log

```
Exception during receive. "\x80" from ASCII-8BIT to UTF-8: /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/core_ext/object/json.rb:38:in `encode'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/core_ext/object/json.rb:38:in `to_json'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/core_ext/object/json.rb:38:in `to_json'
/app/vendor/bundle/ruby/2.5.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
/app/vendor/bundle/ruby/2.5.0/gems/json-1.8.6/lib/json/common.rb:223:in `generate'
/app/vendor/bundle/ruby/2.5.0/gems/json-1.8.6/lib/json/common.rb:394:in `dump'
/app/lib/json_with_indifferent_access.rb:10:in `dump'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/type/serialized.rb:29:in `serialize'
/app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/type/helpers/mutable.rb:8:in `cast'
/app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute.rb:175:in `type_cast'
/app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute.rb:42:in `value'
/app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute.rb:156:in `changed_from_assignment?'
/app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute.rb:59:in `changed?'
/app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute_mutation_tracker.rb:49:in `changed?'
/app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute_mutation_tracker.rb:15:in `block in changed_attribute_names'
/app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute_mutation_tracker.rb:15:in `select'
/app/vendor/bundle/ruby/2.5.0/gems/activemodel-5.2.2.1/lib/active_model/attribute_mutation_tracker.rb:15:in `changed_attribute_names'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/attribute_methods/dirty.rb:114:in `changed_attribute_names_to_save'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/associations/association.rb:182:in `initialize_attributes'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/associations/association.rb:285:in `block in build_record'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/core.rb:316:in `initialize'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/inheritance.rb:66:in `new'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/inheritance.rb:66:in `new'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/reflection.rb:154:in `build_association'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/associations/association.rb:284:in `build_record'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/associations/collection_association.rb:108:in `build'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/associations/collection_proxy.rb:319:in `build'
/app/app/models/agent.rb:112:in `build_event'
/app/app/models/agent.rb:121:in `create_event'
/app/app/concerns/dry_runnable.rb:88:in `create_event'
/app/app/models/agents/post_agent.rb:211:in `handle'
/app/app/models/agents/post_agent.rb:159:in `block (2 levels) in receive'
/app/app/concerns/liquid_interpolatable.rb:64:in `interpolate_with'
/app/app/models/agents/post_agent.rb:154:in `block in receive'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/relation/delegation.rb:71:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/relation/delegation.rb:71:in `each'
/app/app/models/agents/post_agent.rb:153:in `receive'
/app/app/jobs/agent_receive_job.rb:8:in `perform'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:39:in `block in perform_now'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/i18n-1.6.0/lib/i18n.rb:297:in `with_locale'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:46:in `block in tag_logger'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:46:in `tag_logger'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:38:in `perform_now'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:24:in `block in execute'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/reloader.rb:73:in `block in wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/reloader.rb:72:in `wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:22:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-5.2.2.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:78:in `invoke_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block in run'
/usr/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:229:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:213:in `block in work_off'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `times'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `work_off'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vend

```

**Comment by dsander** [comment]
The exception happens because the server respons with a GIF image, Huginn does not handle binary data well in most cases:

```
$ curl -i -X POST https://www.google-analytics.com/collect
HTTP/2 200
access-control-allow-origin: *
date: Sat, 22 Jun 2019 09:08:34 GMT
pragma: no-cache
expires: Fri, 01 Jan 1990 00:00:00 GMT
cache-control: no-cache, no-store, must-revalidate
last-modified: Sun, 17 May 1998 03:00:00 GMT
x-content-type-options: nosniff
content-type: image/gif
server: Golfe2
content-length: 35
alt-svc: quic=":443"; ma=2592000; v="46,44,43,39"

GIF89a�����,D;%
```

If you only need to POST the data, switching `emit_events` to `false` should work.


> Can i ignore response body and read only header status, 

Not at the moment, but adding a new `skip_body` option would be reasonable to add.

> and second question -- can i use ruby language in my agents?

Not in the build in Agents, you can create your own Agent gems though: https://github.com/huginn/huginn_agent

**Comment by smithjoelt** [comment]
Has this issue been solved? Can we close it? I feel like the questions have been answered.
