### ISSUE TITLE
Same docker-compose traefik works on localhost but fails on server?

### ISSUE THREAD

**Issue by thepenguinthatwants** [huginn/huginn#2555]
```
app_1  | bootstrap stdout | DATABASE_HOST=db
app_1  | foreman stderr | FATAL:  password authentication failed for user "huginn"
app_1  | foreman stderr | Couldn't create 'huginn_development' database. Please check your configuration.
app_1  | foreman stderr | rake aborted!
app_1  | foreman stderr | PG::ConnectionBad: FATAL:  password authentication failed for user "huginn"
app_1  | foreman stderr | /app/vendor/bundle/ruby/2.5.0/gems/pg-1.1.3/lib/pg.rb:56:in `initialize'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/pg-1.1.3/lib/pg.rb:56:in `new'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/pg-1.1.3/lib/pg.rb:56:in `connect'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:811:in `new_connection'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:855:in `checkout_new_connection'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:834:in `try_to_checkout_new_connection'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `acquire_connection'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1010:in `retrieve_connection'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_handling.rb:90:in `connection'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:119:in `create'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:313:in `each'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:138:in `create_current'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <main>'
app_1  | /app/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
app_1  | foreman stderr | Tasks: TOP => db:create
app_1  | foreman stderr | (See full trace by running task with --trace)
app_1  | 2019-07-01 13:53:01,061 INFO exited: foreman (exit status 1; not expected)
```

**Comment by dsander** [comment]
Hi,

you need to start a private conversation with the username you chose for your bot when you created it using the botfather. After creating the bot you need to put the `auth_token` in the Agent configuration to be able to send messages.
