### ISSUE TITLE
sql env variables docker not working 

### ISSUE THREAD

**Issue by jucajuca** [huginn/huginn#2604]
Hi I ran huginn with docker. I wanted it to connect to an external mysql server. It always failed. I noticed that the container _did_ read the ENV variables but then it tried to connect to other address anyway. 

steps to reproduce: 
wget https://raw.githubusercontent.com/huginn/huginn/master/.env.example
configure an external database
run with docker and --env-file=.env 

the container logs will show the problem.

**Comment by dsander** [comment]
Hi!

What do you mean by i read the the ENV variables but connected to other address? Can you post the output of the docker container?

**Comment by jucajuca** [comment]
docker run -d --name huginn -p 13080:3000 --env-file=.env -v huginn-mysql:/var/lib/mysql huginn/huginn

for example with this .env file:


```
############################
#      Database Setup      #
############################


DATABASE_ADAPTER=mysql2
DATABASE_ENCODING=utf8
DATABASE_RECONNECT=true
DATABASE_NAME=huginn
DATABASE_POOL=20
DATABASE_USERNAME=myusername
DATABASE_PASSWORD=zsdsdsdsdsds 
DATABASE_HOST="194.60.201.92"
DATABASE_PORT=3306
#DATABASE_SOCKET=/tmp/mysql.sock
```

will cause the following error. See especially the lines

bootstrap stdout | DATABASE_HOST=194.60.201.92,
foreman stderr | Access denied for user 'myusername'@'172.17.0.14' (using password: YES),
Couldn't create 'hugin' database. Please check your configuration.,
foreman stderr | rake aborted!,


it means that the env variable was read but then ignored and replaced with '172.17.0.14' 

At the end I mapped /var/lib/mysql/ to a container... is actually a good solution.  But for the people that has a db server it would be good to get this working

```
Using hypdf 1.0.10,
Using jquery-rails 4.2.2,
Using json 1.8.6,
....
Using xmpp4r 0.5.6,
Bundle complete! 109 Gemfile dependencies, 182 gems now installed.,
Gems in the groups test and development were not installed.,
Bundled gems are installed into `./vendor/bundle`,
2019-10-07 18:58:08,435 WARN Included extra file "/etc/supervisor/conf.d/mysqld.conf" during parsing,
2019-10-07 18:58:08,435 WARN Included extra file "/etc/supervisor/conf.d/foreman.conf" during parsing,
...
2019-10-07 18:58:10,567 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
bootstrap stdout | DATABASE_HOST=194.60.201.92,
foreman stderr | Access denied for user 'myusername'@'172.17.0.14' (using password: YES),
Couldn't create 'huginn' database. Please check your configuration.,
foreman stderr | rake aborted!,
Mysql2::Error::ConnectionError: Access denied for user 'jccbsql9'@'172.17.0.14' (using password: YES),
/app/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `connect',
/app/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `initialize',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `new',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `mysql2_connection',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:811:in `new_connection',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:855:in `checkout_new_connection',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:834:in `try_to_checkout_new_connection',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `acquire_connection',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1010:in `retrieve_connection',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_handling.rb:90:in `connection',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/mysql_database_tasks.rb:6:in `connection',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/mysql_database_tasks.rb:14:in `create',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:119:in `create',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:313:in `each',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/tasks/database_tasks.rb:138:in `create_current',
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <main>',
/app/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>',
Tasks: TOP => db:create,
(See full trace by running task with --trace),
2019-10-07 18:58:18,370 INFO exited: foreman (exit status 1; not expected),
```

**Comment by dsander** [comment]
When I run this, the docker container just hangs because it tries to connect to the IP which is not used in my network. I think one would get the output you posted if the `huginn` container is linked to a database container (in which case it does not make sense to provide the IP).

I created your `.env` file in an empty directory and ran `docker run -d --name huginn -p 13080:3000 --env-file=.env -v huginn-mysql:/var/lib/mysql huginn/huginn`

After a while the connection attempt times out and I get the following output:

```
....
2019-10-09 22:17:57,400 INFO success: bootstrap entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2019-10-09 22:17:57,458 INFO spawned: 'foreman' with pid 367
2019-10-09 22:17:57,459 INFO success: foreman entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2019-10-09 22:17:57,464 INFO exited: bootstrap (exit status 0; expected)
2019-10-09 22:17:58,467 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bootstrap stdout | DATABASE_HOST=194.60.201.92
foreman stderr | Can't connect to MySQL server on '194.60.201.92' (111)
Couldn't create 'huginn' database. Please check your configuration.
rake aborted!
Mysql2::Error::ConnectionError: Can't connect to MySQL server on '194.60.201.92' (111)
foreman stderr | /app/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `connect'
/app/vendor/bundle/ruby/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:90:in `initialize'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters
...
````

**Comment by yetio** [comment]
I met the same issue as  jucajuca said. I found it's not due to  the HOST, but to the USERNAME. It will be always add the ip of the docker at the end of the USERNAME. 

For example, the huginn had connect to the DB server 194.60.201.92, but with wrong username `'myusername'@'172.17.0.14'` (the correct one should be ` 'myusername'@'194.60.201.92'`). Therefore, you got an "access denied" message instead of "cannot connect" message.

```
2019-10-07 18:58:10,567 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
bootstrap stdout | DATABASE_HOST=194.60.201.92,
foreman stderr | Access denied for user 'myusername'@'172.17.0.14' (using password: YES),
```
