### ISSUE TITLE
Trigger Agent -  character ' ' not supported in query

### ISSUE THREAD

**Issue by MattiaFailla** [huginn/huginn#2649]
Hi, I've created a **Twitter User Agent** that extract timeline for a given user. I'm using the **Trigger Agent** to check that the message contains several terms in this way:
```
{
  "expected_receive_period_in_days": "1",
  "keep_event": "true",
  "rules": [
    {
      "type": "regex",
      "value": [
        "hello",
        "jack",
        "test"
      ],
      "path": "{{full_text}}",
      "must_match": "1"
    }
  ],
  "message": "The user said {{value}} in {{full_text}}!"
}
```

But the agent fails with this message:
```

character ' ' not supported in query
/var/lib/gems/2.5.0/gems/jsonpath-1.0.1/lib/jsonpath.rb:40:in `rescue in initialize'
/var/lib/gems/2.5.0/gems/jsonpath-1.0.1/lib/jsonpath.rb:37:in `initialize'
/home/pc/huginn/lib/utils.rb:96:in `new'
/home/pc/huginn/lib/utils.rb:96:in `values_at'
/home/pc/huginn/lib/utils.rb:85:in `value_at'
/home/pc/huginn/app/models/agents/trigger_agent.rb:100:in `block (2 levels) in receive'
/home/pc/huginn/app/models/agents/trigger_agent.rb:95:in `map'
/home/pc/huginn/app/models/agents/trigger_agent.rb:95:in `block in receive'
/var/lib/gems/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/relation/delegation.rb:71:in `each'
/var/lib/gems/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/relation/delegation.rb:71:in `each'
/home/storage/huginn/app/models/agents/trigger_agent.rb:91:in `receive'
/home/storage/huginn/app/jobs/agent_receive_job.rb:8:in `perform'
/var/lib/gems/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:39:in `block in perform_now'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/var/lib/gems/2.5.0/gems/i18n-1.6.0/lib/i18n.rb:297:in `with_locale'
/var/lib/gems/2.5.0/gems/activejob-5.2.2.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/var/lib/gems/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `instrument'
/var/lib/gems/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/var/lib/gems/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:46:in `block in tag_logger'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'
/var/lib/gems/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:46:in `tag_logger'
/var/lib/gems/2.5.0/gems/activejob-5.2.2.1/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/var/lib/gems/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:38:in `perform_now'
/var/lib/gems/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:24:in `block in execute'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/var/lib/gems/2.5.0/gems/activejob-5.2.2.1/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/reloader.rb:73:in `block in wrap'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/reloader.rb:72:in `wrap'
/var/lib/gems/2.5.0/gems/activejob-5.2.2.1/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/var/lib/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'
/var/lib/gems/2.5.0/gems/activejob-5.2.2.1/lib/active_job/execution.rb:22:in `execute'
/var/lib/gems/2.5.0/gems/activejob-5.2.2.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/backend/base.rb:78:in `invoke_job'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:230:in `block in run'
/usr/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:229:in `run'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:213:in `block in work_off'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `times'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:212:in `work_off'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `loop'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:172:in `block in start'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:61:in `block in initialize'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:79:in `block in add'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:66:in `execute'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/var/lib/gems/2.5.0/gems/delayed_job-4.1.5/lib/delayed/worker.rb:171:in `start'
/home/pc/huginn/lib/delayed_job_worker.rb:6:in `run'
/home/pc/huginn/app/concerns/long_runnable.rb:71:in `block in run!'
```
I don't understand what query it refers to and why it fails. Do I have to clean the payload that comes to me from twitter (_full_text_)?

**Comment by dsander** [comment]
Hi!

I am pretty sure it fails because `value` is an array and not a regular expression. `value: "hello|jack|test"` should work.

**Comment by MattiaFailla** [comment]
Something changed: `character '’' not supported in query`

**Comment by MattiaFailla** [comment]
Ok I suspect that the problem is the ` "path": "{{full_text}}",` because changing that line with this one: `$.full_text.[*]` does not produce any errors, but simply does not find the words in the text it receives. 

I suspect the problem at this point is accessing full_text in the Twitter agent payload with the method described in [JsonPat](https://goessner.net/articles/JsonPath/) that I currently do not know

**Comment by MattiaFailla** [comment]
Ok guys, I did it.

You need to use _path_ in this way: `"path": "$.full_text"`

You can find the definition of the [Twitter payload here](https://github.com/huginn/huginn/blob/master/app/models/agents/twitter_user_agent.rb#L27) and you can test your JsonPath with [this tool](https://jsonpath.com/).

**Comment by dsander** [comment]
Nice, glad you figured it out! Sorry I missed that the Agent expects an actual JSONPath and not Liquid.
