### ISSUE TITLE
HuginnScheduler restarting, scheduled jobs failing

### ISSUE THREAD

**Issue by l1n** [huginn/huginn#2717]
Hi all! I finally bit the bullet and transitioned to `runit` from `systemd`, and I'm testing the `end-of-2019-rollup` (because those sweet sweet upgrades). Unfortunately, when I `sv start huginn-jobs-1`, I get the following in my logs:
```
Starting HuginnScheduler
`/` is not writable.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
/pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler/jobs.rb:667:in `check_frequency': job frequency (min ~0s) is higher than scheduler frequency (3s) (ArgumentError)
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler.rb:621:in `do_schedule'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/rufus-scheduler-3.6.0/lib/rufus/scheduler.rb:227:in `cron'
	from /pub/lin/huginn/app/concerns/long_runnable.rb:135:in `schedule'
	from /pub/lin/huginn/app/concerns/long_runnable.rb:121:in `cron'
	from /pub/lin/huginn/lib/huginn_scheduler.rb:134:in `block in setup'
	from /pub/lin/huginn/lib/huginn_scheduler.rb:133:in `each'
	from /pub/lin/huginn/lib/huginn_scheduler.rb:133:in `setup'
	from /pub/lin/huginn/app/concerns/long_runnable.rb:86:in `setup!'
	from /pub/lin/huginn/lib/agent_runner.rb:82:in `block in run_workers'
	from /pub/lin/huginn/lib/agent_runner.rb:79:in `each'
	from /pub/lin/huginn/lib/agent_runner.rb:79:in `run_workers'
	from /pub/lin/huginn/lib/agent_runner.rb:39:in `run'
	from /pub/lin/huginn/bin/threaded.rb:13:in `<main>'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/railties-6.0.2.1/lib/rails/commands/runner/runner_command.rb:42:in `perform'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/railties-6.0.2.1/lib/rails/command/base.rb:69:in `perform'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/railties-6.0.2.1/lib/rails/command.rb:46:in `invoke'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /pub/lin/huginn/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
	from bin/rails:9:in `<main>'
```
and no scheduled jobs running. On-demand job runs work in the interface, and I'm using the threaded main process. How should I debug this?

**Comment by dsander** [comment]
Hi!

Sorry for the late response and thanks for testing the branch! It seems to be an issue in a dependency we are using: https://github.com/jmettraux/rufus-scheduler/issues/301

To work around it you can change the `SCHEDULER_FREQUENCY` in your `.env` file to something below one second like this: `SCHEDULER_FREQUENCY=0.9` or remove it which will make Huginn fall back to it's default of `0.3` seconds.

**Comment by dsander** [comment]
This should be fixed now.
