### ISSUE TITLE
EOF Error Afternoon Digest Agent

### ISSUE THREAD

**Issue by Malpraktis** [huginn/huginn#2782]
Hi all, new Huginn user here!  In fact new to the whole thing; coding, etc.  So I'm hoping this is easy and something I'm just too newbie and overlooked, ha.  I've worked through most of the minor issues, but this one has stumped me.

I seem to be encountering an error that I'm having trouble finding things to try in order to correct it.  When I run the default agent for Afternoon Digest, I'm getting an error during the process.  It is:

end of file reached /usr/local/lib/ruby/2.6.0/net/protocol.rb:225:in `rbuf_fill'

The longer version:

`end of file reached/usr/local/lib/ruby/2.6.0/net/protocol.rb:225:in `rbuf_fill'/usr/local/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'/usr/local/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'/usr/local/lib/ruby/2.6.0/net/smtp.rb:950:in `recv_response'/usr/local/lib/ruby/2.6.0/net/smtp.rb:553:in `block in `do_start'/usr/local/lib/ruby/2.6.0/net/smtp.rb:960:in `critical'/usr/local/lib/ruby/2.6.0/net/smtp.rb:553:in `do_start'/usr/local/lib/ruby/2.6.0/net/smtp.rb:518:in `start'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/mail-`2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/mail-`2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/mail-`2.7.1/lib/mail/message.rb:2159:in `do_delivery'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/mail-`2.7.1/lib/mail/message.rb:260:in `block in `deliver'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/actionmailer-`5.2.2.1/lib/action_mailer/base.rb:560:in `block in `deliver_mail'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/notifications.rb:168:in `block in `instrument'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/notifications.rb:168:in `instrument'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/actionmailer-`5.2.2.1/lib/action_mailer/base.rb:558:in `deliver_mail'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/mail-`2.7.1/lib/mail/message.rb:260:in `deliver'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/actionmailer-`5.2.2.1/lib/action_mailer/message_delivery.rb:114:in `block in `deliver_now'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/actionmailer-`5.2.2.1/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/actionmailer-`5.2.2.1/lib/action_mailer/message_delivery.rb:113:in `deliver_now'/home/huginn/huginn/app/models/agents/email_digest_agent.rb:61:in `block in `check'/home/huginn/huginn/app/models/agents/email_digest_agent.rb:52:in `each'/home/huginn/huginn/app/models/agents/email_digest_agent.rb:52:in `check'/home/huginn/huginn/app/jobs/agent_check_job.rb:7:in `perform'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-`5.2.2.1/lib/active_job/execution.rb:39:in `block in `perform_now'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/callbacks.rb:109:in `block in `run_callbacks'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/i18n-1.6.0/lib/i18n.rb:297:in `with_locale'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-`5.2.2.1/lib/active_job/translation.rb:9:in `block (2 levels) in `<module:Translation>'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/callbacks.rb:118:in `block in `run_callbacks'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-`5.2.2.1/lib/active_job/logging.rb:26:in `block (4 levels) in `<module:Logging>'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/notifications.rb:168:in `block in `instrument'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/notifications.rb:168:in `instrument'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-`5.2.2.1/lib/active_job/logging.rb:25:in `block (3 levels) in `<module:Logging>'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-`5.2.2.1/lib/active_job/logging.rb:46:in `block in `tag_logger'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/tagged_logging.rb:71:in `block in `tagged'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-`5.2.2.1/lib/active_job/logging.rb:46:in `tag_logger'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-`5.2.2.1/lib/active_job/logging.rb:22:in `block (2 levels) in `<module:Logging>'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/callbacks.rb:118:in `block in `run_callbacks'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-`5.2.2.1/lib/active_job/execution.rb:38:in `perform_now'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-`5.2.2.1/lib/active_job/execution.rb:24:in `block in `execute'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/callbacks.rb:109:in `block in `run_callbacks'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-`5.2.2.1/lib/active_job/railtie.rb:28:in `block (4 levels) in `<class:Railtie>'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/reloader.rb:73:in `block in `wrap'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/execution_wrapper.rb:87:in `wrap'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/reloader.rb:72:in `wrap'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-`5.2.2.1/lib/active_job/railtie.rb:27:in `block (3 levels) in `<class:Railtie>'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/callbacks.rb:118:in `instance_exec'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/callbacks.rb:118:in `block in `run_callbacks'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-`5.2.2.1/lib/active_support/callbacks.rb:136:in `run_callbacks'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-`5.2.2.1/lib/active_job/execution.rb:22:in `execute'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-`5.2.2.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/backend/base.rb:81:in `block in `invoke_job'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/lifecycle.rb:61:in `block in `initialize'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/lifecycle.rb:66:in `execute'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/backend/base.rb:78:in `invoke_job'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/worker.rb:230:in `block (2 levels) in run'/usr/local/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'/usr/local/lib/ruby/2.6.0/timeout.rb:103:in `timeout'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/worker.rb:230:in `block in run'/usr/local/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/worker.rb:229:in `run'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/worker.rb:312:in `block in `reserve_and_run_one_job'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/lifecycle.rb:61:in `block in `initialize'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/lifecycle.rb:66:in `execute'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/worker.rb:213:in `block in `work_off'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/worker.rb:212:in `times'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/worker.rb:212:in `work_off'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/worker.rb:175:in `block (4 levels) in `start'/usr/local/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/worker.rb:174:in `block (3 levels) in `start'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/lifecycle.rb:61:in `block in `initialize'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/lifecycle.rb:66:in `execute'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/worker.rb:173:in `block (2 levels) in `start'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/worker.rb:172:in `loop'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/worker.rb:172:in `block in `start'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in `<class:ClearLocks>'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/lifecycle.rb:79:in `block (2 levels) in `add'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/lifecycle.rb:61:in `block in `initialize'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/lifecycle.rb:79:in `block in `add'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/lifecycle.rb:66:in `execute'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/lifecycle.rb:40:in `run_callbacks'/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-`4.1.5/lib/delayed/worker.rb:171:in `start'/home/huginn/huginn/lib/delayed_job_worker.rb:6:in `run'/home/huginn/huginn/app/concerns/long_runnable.rb:71:in `block in run!' | Run nowDelete
`-- | --
`failed | Afternoon Digest | ~2h ago for malpraktis |   | 5 | end of file reached `/usr/local/lib/ruby/2.6.0/net/protocol.rb:225:in `rbuf_fill' | Run nowDelete

`

Any help would be appreciated!

Thanks in advance

**Comment by Malpraktis** [comment]
i was able to fix this by changing the gmail smtp from 465 to 587... im not sure why that worked
