### ISSUE TITLE
Email agent not sending emails

### ISSUE THREAD

**Issue by Taomyn** [huginn/huginn#2846]
Since about 3 days ago my installation stopped sending emails. One of the two logged messages is `Error sending mail to me@mydomain.com with event 1556: Broken pipe`

When I try some dry runs, I get two different results depending on which of the recent alerts to send. One is:

```
[00:00:00] INFO -- : Dry Run started
[00:00:00] ERROR -- : Error sending mail to me@mydomain.com with event : Broken pipe
[00:00:00] INFO -- : Dry Run failed
[00:00:00] ERROR -- : Exception during dry-run. Broken pipe: /app/vendor/bundle/ruby/2.5.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/sendmail.rb:64:in `write'
/app/vendor/bundle/ruby/2.5.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/sendmail.rb:64:in `puts'
/app/vendor/bundle/ruby/2.5.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/sendmail.rb:64:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/sendmail.rb:75:in `popen'
/app/vendor/bundle/ruby/2.5.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/sendmail.rb:75:in `popen'
/app/vendor/bundle/ruby/2.5.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/sendmail.rb:63:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/sendmail.rb:59:in `deliver!'
/app/vendor/bundle/ruby/2.5.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
/app/vendor/bundle/ruby/2.5.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
/app/vendor/bundle/ruby/2.5.0/gems/actionmailer-6.0.3.1/lib/action_mailer/base.rb:589:in `block in deliver_mail'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/actionmailer-6.0.3.1/lib/action_mailer/base.rb:587:in `deliver_mail'
/app/vendor/bundle/ruby/2.5.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
/app/vendor/bundle/ruby/2.5.0/gems/actionmailer-6.0.3.1/lib/action_mailer/message_delivery.rb:115:in `block in deliver_now'
/app/vendor/bundle/ruby/2.5.0/gems/actionmailer-6.0.3.1/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/app/vendor/bundle/ruby/2.5.0/gems/actionmailer-6.0.3.1/lib/action_mailer/message_delivery.rb:114:in `deliver_now'
/app/app/models/agents/email_agent.rb:58:in `block (2 levels) in receive'
/app/app/models/agents/email_agent.rb:48:in `each'
/app/app/models/agents/email_agent.rb:48:in `block in receive'
/app/app/models/agents/email_agent.rb:47:in `each'
/app/app/models/agents/email_agent.rb:47:in `receive'
/app/app/concerns/dry_runnable.rb:29:in `dry_run!'
/app/app/controllers/agents/dry_runs_controller.rb:41:in `create'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/abstract_controller/base.rb:195:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/abstract_controller/base.rb:136:in `process'
/app/vendor/bundle/ruby/2.5.0/gems/actionview-6.0.3.1/lib/action_view/rendering.rb:39:in `process'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal.rb:190:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal.rb:254:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:32:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:32:in `serve'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:834:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/conditional_get.rb:40:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/cookies.rb:648:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:101:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:37:in `call_app'
/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:26:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:26:in `call'
/app/config/initializers/silence_worker_status_logger.rb:3:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/static.rb:126:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/engine.rb:527:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/railtie.rb:190:in `public_send'
/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/railtie.rb:190:in `method_missing'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/handler/webrick.rb:95:in `service'
/usr/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
/usr/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
/usr/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'

```

Another is just:

```
[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Sent mail to me@mydomain.com with event 
[00:00:00] INFO -- : Dry Run finished
```

But nothing arrives at my external mail server, not even a connection.

Looking at the docker log for this I see:

```
10:07:21 web.1  | https://huginn.mydomain.com/agents/16?return=%2Fagents -> /worker_status?since_id=1562
foreman stdout | 10:07:23 jobs.1 | 2020-07-20T03:04:23-0700: [Worker(host:Huginn pid:424)] 1 jobs processed at 12.5997 j/s, 0 failed
10:07:23 jobs.1 | Queuing schedule for every_5m
10:07:23 jobs.1 | [ActiveJob] Enqueued AgentRunScheduleJob (Job ID: 59546f4c-6427-4d37-ae5b-958e08d383ae) to DelayedJob(default) with arguments: "every_5m"
10:07:23 jobs.1 | Queuing schedule for every_1m
10:07:23 jobs.1 | [ActiveJob] Enqueued AgentRunScheduleJob (Job ID: 6c8229b2-2b54-4fd6-a5be-99cc58351e61) to DelayedJob(default) with arguments: "every_1m"
10:07:23 jobs.1 | 2020-07-20T03:05:03-0700: [Worker(host:Huginn pid:424)] Job AgentRunScheduleJob [59546f4c-6427-4d37-ae5b-958e08d383ae] from DelayedJob(default) with arguments
: ["every_5m"] (id=1490400) (queue=default) RUNNING
10:07:23 jobs.1 | [ActiveJob] [AgentRunScheduleJob] [59546f4c-6427-4d37-ae5b-958e08d383ae] Performing AgentRunScheduleJob (Job ID: 59546f4c-6427-4d37-ae5b-958e08d383ae) from De
layedJob(default) enqueued at 2020-07-20T10:05:00Z with arguments: "every_5m"
10:07:23 jobs.1 | [ActiveJob] [AgentRunScheduleJob] [59546f4c-6427-4d37-ae5b-958e08d383ae] Performed AgentRunScheduleJob (Job ID: 59546f4c-6427-4d37-ae5b-958e08d383ae) from Del
ayedJob(default) in 0.83ms
10:07:23 jobs.1 | 2020-07-20T03:05:03-0700: [Worker(host:Huginn pid:424)] Job AgentRunScheduleJob [59546f4c-6427-4d37-ae5b-958e08d383ae] from DelayedJob(default) with arguments
: ["every_5m"] (id=1490400) (queue=default) COMPLETED after 0.0902
10:07:23 jobs.1 | 2020-07-20T03:05:03-0700: [Worker(host:Huginn pid:424)] Job AgentRunScheduleJob [6c8229b2-2b54-4fd6-a5be-99cc58351e61] from DelayedJob(default) with arguments
: ["every_1m"] (id=1490401) (queue=default) RUNNING
10:07:23 jobs.1 | [ActiveJob] [AgentRunScheduleJob] [6c8229b2-2b54-4fd6-a5be-99cc58351e61] Performing AgentRunScheduleJob (Job ID: 6c8229b2-2b54-4fd6-a5be-99cc58351e61) from De
layedJob(default) enqueued at 2020-07-20T10:05:00Z with arguments: "every_1m"
10:07:23 jobs.1 | [ActiveJob] [AgentRunScheduleJob] [6c8229b2-2b54-4fd6-a5be-99cc58351e61] Performed AgentRunScheduleJob (Job ID: 6c8229b2-2b54-4fd6-a5be-99cc58351e61) from Del
ayedJob(default) in 0.65ms
10:07:23 jobs.1 | 2020-07-20T03:05:03-0700: [Worker(host:Huginn pid:424)] Job AgentRunScheduleJob [6c8229b2-2b54-4fd6-a5be-99cc58351e61] from DelayedJob(default) with arguments
: ["every_1m"] (id=1490401) (queue=default) COMPLETED after 0.0061
10:07:23 jobs.1 | 2020-07-20T03:05:03-0700: [Worker(host:Huginn pid:424)] 2 jobs processed at 17.2750 j/s, 0 failed
10:07:23 jobs.1 | Queuing event propagation
10:07:23 jobs.1 | [ActiveJob] Enqueued AgentPropagateJob (Job ID: a769597b-0a72-4f4b-bbd1-a42e633cc66f) to DelayedJob(propagation)
10:07:23 jobs.1 | 2020-07-20T03:05:23-0700: [Worker(host:Huginn pid:424)] Job AgentPropagateJob [a769597b-0a72-4f4b-bbd1-a42e633cc66f] from DelayedJob(propagation) with argumen
ts: [] (id=1490402) (queue=propagation) RUNNING
10:07:23 jobs.1 | [ActiveJob] [AgentPropagateJob] [a769597b-0a72-4f4b-bbd1-a42e633cc66f] Performing AgentPropagateJob (Job ID: a769597b-0a72-4f4b-bbd1-a42e633cc66f) from Delaye
dJob(propagation) enqueued at 2020-07-20T10:05:22Z
10:07:23 jobs.1 | [ActiveJob] [AgentPropagateJob] [a769597b-0a72-4f4b-bbd1-a42e633cc66f] Performed AgentPropagateJob (Job ID: a769597b-0a72-4f4b-bbd1-a42e633cc66f) from Delayed
Job(propagation) in 1.91ms
10:07:23 jobs.1 | 2020-07-20T03:05:23-0700: [Worker(host:Huginn pid:424)] Job AgentPropagateJob [a769597b-0a72-4f4b-bbd1-a42e633cc66f] from DelayedJob(propagation) with argumen
ts: [] (id=1490402) (queue=propagation) COMPLETED after 0.0095
10:07:23 jobs.1 | 2020-07-20T03:05:23-0700: [Worker(host:Huginn pid:424)] 1 jobs processed at 56.8837 j/s, 0 failed
10:07:23 jobs.1 | Queuing schedule for every_1m
10:07:23 jobs.1 | [ActiveJob] Enqueued AgentRunScheduleJob (Job ID: 5f7e7761-1a67-47ca-8279-5813d1214c19) to DelayedJob(default) with arguments: "every_1m"
10:07:23 jobs.1 | Queuing schedule for every_2m
10:07:23 jobs.1 | [ActiveJob] Enqueued AgentRunScheduleJob (Job ID: 0deb4495-47f0-4240-b762-4f19c3e6f77e) to DelayedJob(default) with arguments: "every_2m"
10:07:23 jobs.1 | 2020-07-20T03:06:03-0700: [Worker(host:Huginn pid:424)] Job AgentRunScheduleJob [5f7e7761-1a67-47ca-8279-5813d1214c19] from DelayedJob(default) with arguments
: ["every_1m"] (id=1490403) (queue=default) RUNNING
10:07:23 jobs.1 | [ActiveJob] [AgentRunScheduleJob] [5f7e7761-1a67-47ca-8279-5813d1214c19] Performing AgentRunScheduleJob (Job ID: 5f7e7761-1a67-47ca-8279-5813d1214c19) from De
layedJob(default) enqueued at 2020-07-20T10:06:00Z with arguments: "every_1m"
10:07:23 jobs.1 | [ActiveJob] [AgentRunScheduleJob] [5f7e7761-1a67-47ca-8279-5813d1214c19] Performed AgentRunScheduleJob (Job ID: 5f7e7761-1a67-47ca-8279-5813d1214c19) from Del
ayedJob(default) in 0.73ms
10:07:23 jobs.1 | 2020-07-20T03:06:03-0700: [Worker(host:Huginn pid:424)] Job AgentRunScheduleJob [5f7e7761-1a67-47ca-8279-5813d1214c19] from DelayedJob(default) with arguments
: ["every_1m"] (id=1490403) (queue=default) COMPLETED after 0.0055
10:07:23 jobs.1 | 2020-07-20T03:06:03-0700: [Worker(host:Huginn pid:424)] Job AgentRunScheduleJob [0deb4495-47f0-4240-b762-4f19c3e6f77e] from DelayedJob(default) with arguments
: ["every_2m"] (id=1490404) (queue=default) RUNNING
10:07:23 jobs.1 | [ActiveJob] [AgentRunScheduleJob] [0deb4495-47f0-4240-b762-4f19c3e6f77e] Performing AgentRunScheduleJob (Job ID: 0deb4495-47f0-4240-b762-4f19c3e6f77e) from De
layedJob(default) enqueued at 2020-07-20T10:06:00Z with arguments: "every_2m"
10:07:23 jobs.1 | [ActiveJob] [AgentRunScheduleJob] [0deb4495-47f0-4240-b762-4f19c3e6f77e] Performed AgentRunScheduleJob (Job ID: 0deb4495-47f0-4240-b762-4f19c3e6f77e) from Del
ayedJob(default) in 0.64ms
10:07:23 jobs.1 | 2020-07-20T03:06:03-0700: [Worker(host:Huginn pid:424)] Job AgentRunScheduleJob [0deb4495-47f0-4240-b762-4f19c3e6f77e] from DelayedJob(default) with arguments
: ["every_2m"] (id=1490404) (queue=default) COMPLETED after 0.0057
foreman stdout | 10:07:23 jobs.1 | 2020-07-20T03:06:03-0700: [Worker(host:Huginn pid:424)] 2 jobs processed at 56.3851 j/s, 0 failed
foreman stdout | 10:07:23 jobs.1 | Queuing event propagation
10:07:23 jobs.1 | [ActiveJob] Enqueued AgentPropagateJob (Job ID: 5c490c83-07a0-4a13-a526-40a4a247b079) to DelayedJob(propagation)
10:07:23 jobs.1 | 2020-07-20T03:06:23-0700: [Worker(host:Huginn pid:424)] Job AgentPropagateJob [5c490c83-07a0-4a13-a526-40a4a247b079] from DelayedJob(propagation) with argumen
ts: [] (id=1490405) (queue=propagation) RUNNING
foreman stdout | 10:07:23 jobs.1 | [ActiveJob] [AgentPropagateJob] [5c490c83-07a0-4a13-a526-40a4a247b079] Performing AgentPropagateJob (Job ID: 5c490c83-07a0-4a13-a526-40a4a247
b079) from DelayedJob(propagation) enqueued at 2020-07-20T10:06:22Z
10:07:23 jobs.1 | [ActiveJob] [AgentPropagateJob] [5c490c83-07a0-4a13-a526-40a4a247b079] Performed AgentPropagateJob (Job ID: 5c490c83-07a0-4a13-a526-40a4a247b079) from Delayed
Job(propagation) in 2.32ms
foreman stdout | 10:07:23 jobs.1 | 2020-07-20T03:06:23-0700: [Worker(host:Huginn pid:424)] Job AgentPropagateJob [5c490c83-07a0-4a13-a526-40a4a247b079] from DelayedJob(propagat
ion) with arguments: [] (id=1490405) (queue=propagation) COMPLETED after 0.0158
10:07:23 jobs.1 | 2020-07-20T03:06:23-0700: [Worker(host:Huginn pid:424)] 1 jobs processed at 37.9902 j/s, 0 failed
foreman stdout | 10:07:23 jobs.1 | Queuing schedule for every_1m
10:07:23 jobs.1 | [ActiveJob] Enqueued AgentRunScheduleJob (Job ID: e49111f1-5de7-4e39-b08d-251719cb90e2) to DelayedJob(default) with arguments: "every_1m"
foreman stdout | 10:07:23 jobs.1 | 2020-07-20T03:07:03-0700: [Worker(host:Huginn pid:424)] Job AgentRunScheduleJob [e49111f1-5de7-4e39-b08d-251719cb90e2] from DelayedJob(defaul
t) with arguments: ["every_1m"] (id=1490406) (queue=default) RUNNING
10:07:23 jobs.1 | [ActiveJob] [AgentRunScheduleJob] [e49111f1-5de7-4e39-b08d-251719cb90e2] Performing AgentRunScheduleJob (Job ID: e49111f1-5de7-4e39-b08d-251719cb90e2) from De
layedJob(default) enqueued at 2020-07-20T10:07:00Z with arguments: "every_1m"
10:07:23 jobs.1 | [ActiveJob] [AgentRunScheduleJob] [e49111f1-5de7-4e39-b08d-251719cb90e2] Performed AgentRunScheduleJob (Job ID: e49111f1-5de7-4e39-b08d-251719cb90e2) from Del
ayedJob(default) in 0.81ms
foreman stdout | 10:07:23 jobs.1 | 2020-07-20T03:07:03-0700: [Worker(host:Huginn pid:424)] Job AgentRunScheduleJob [e49111f1-5de7-4e39-b08d-251719cb90e2] from DelayedJob(defaul
t) with arguments: ["every_1m"] (id=1490406) (queue=default) COMPLETED after 0.0059
10:07:23 jobs.1 | 2020-07-20T03:07:03-0700: [Worker(host:Huginn pid:424)] 1 jobs processed at 79.1379 j/s, 0 failed
foreman stdout | 10:07:23 jobs.1 | Queuing event propagation
10:07:23 jobs.1 | [ActiveJob] Enqueued AgentPropagateJob (Job ID: 5dc493ee-26a4-4026-b8ce-939d97fb1f09) to DelayedJob(propagation)
foreman stdout | 10:07:23 jobs.1 | 2020-07-20T03:07:23-0700: [Worker(host:Huginn pid:424)] Job AgentPropagateJob [5dc493ee-26a4-4026-b8ce-939d97fb1f09] from DelayedJob(propagat
ion) with arguments: [] (id=1490407) (queue=propagation) RUNNING
10:07:23 jobs.1 | [ActiveJob] [AgentPropagateJob] [5dc493ee-26a4-4026-b8ce-939d97fb1f09] Performing AgentPropagateJob (Job ID: 5dc493ee-26a4-4026-b8ce-939d97fb1f09) from Delaye
dJob(propagation) enqueued at 2020-07-20T10:07:22Z
foreman stdout | 10:07:23 jobs.1 | [ActiveJob] [AgentPropagateJob] [5dc493ee-26a4-4026-b8ce-939d97fb1f09] Performed AgentPropagateJob (Job ID: 5dc493ee-26a4-4026-b8ce-939d97fb1
f09) from DelayedJob(propagation) in 1.77ms
foreman stdout | 10:07:23 web.1  | 192.168.1.1 - - [20/Jul/2020:03:07:23 PDT] "GET /worker_status?since_id=1562 HTTP/1.1" 200 124
10:07:23 web.1  | https://huginn.mydomain.com/agents/16?return=%2Fagents -> /worker_status?since_id=1562
foreman stdout | 10:07:25 web.1  | [f8cc5d96-259d-42ee-8a55-0f61a48de553] Delivered mail 5f156c73c34c1_1a72acdce64dcfc4444d@Huginn.mail (7.7ms)
10:07:25 web.1  | [f8cc5d96-259d-42ee-8a55-0f61a48de553]   Rendering agents/dry_runs/create.html.erb
10:07:25 web.1  | [f8cc5d96-259d-42ee-8a55-0f61a48de553]   Rendered agents/dry_runs/create.html.erb (Duration: 0.1ms | Allocations: 20)
10:07:25 web.1  | [f8cc5d96-259d-42ee-8a55-0f61a48de553] Completed 200 OK in 109ms (Views: 0.5ms | ActiveRecord: 2.3ms | Allocations: 105527)
10:07:25 web.1  | [3d57cc42-5dbb-4a33-bbe4-2b3872b417f5] Started GET "/agents/16/dry_runs?with_event_mode=yes" for 193.91.41.227 at 2020-07-20 03:07:21 -0700
10:07:25 web.1  | [3d57cc42-5dbb-4a33-bbe4-2b3872b417f5] Processing by Agents::DryRunsController#index as */*
10:07:25 web.1  | [3d57cc42-5dbb-4a33-bbe4-2b3872b417f5]   Parameters: {"with_event_mode"=>"yes", "agent_id"=>"16"}
10:07:25 web.1  | [3d57cc42-5dbb-4a33-bbe4-2b3872b417f5]   Rendering agents/dry_runs/index.html.erb
10:07:25 web.1  | [3d57cc42-5dbb-4a33-bbe4-2b3872b417f5]   Rendered agents/dry_runs/index.html.erb (Duration: 23.7ms | Allocations: 17724)
10:07:25 web.1  | [3d57cc42-5dbb-4a33-bbe4-2b3872b417f5] Completed 200 OK in 28ms (Views: 20.6ms | ActiveRecord: 4.1ms | Allocations: 19836)
10:07:25 web.1  | [054e09ee-3ae9-4137-9f63-af03c9cb60e8] Started POST "/agents/16/dry_runs" for 193.91.41.227 at 2020-07-20 03:07:25 -0700
10:07:25 web.1  | [054e09ee-3ae9-4137-9f63-af03c9cb60e8] Processing by Agents::DryRunsController#create as HTML
10:07:25 web.1  | [054e09ee-3ae9-4137-9f63-af03c9cb60e8]   Parameters: {"event"=>"{\"OneDrive release notes\":\"<i class=\\\"ocpItalic\\\">Last updated: July 17, 2020</i>\",\"s
ubject\":\"OneDrive Release Notes\"}", "agent_id"=>"16"}
10:07:25 web.1  | [054e09ee-3ae9-4137-9f63-af03c9cb60e8]   Rendering system_mailer/send_message.html.erb
10:07:25 web.1  | [054e09ee-3ae9-4137-9f63-af03c9cb60e8]   Rendered system_mailer/send_message.html.erb (Duration: 0.9ms | Allocations: 520)
10:07:25 web.1  | [054e09ee-3ae9-4137-9f63-af03c9cb60e8]   Rendering system_mailer/send_message.text.erb
10:07:25 web.1  | [054e09ee-3ae9-4137-9f63-af03c9cb60e8]   Rendered system_mailer/send_message.text.erb (Duration: 0.0ms | Allocations: 4)
foreman stdout | 10:07:25 web.1  | sh: 1: /usr/sbin/sendmail: not found
foreman stdout | 10:07:25 web.1  | 192.168.1.1 - - [20/Jul/2020:03:07:25 PDT] "POST /agents/16/dry_runs HTTP/1.1" 200 1016
10:07:25 web.1  | https://huginn.mydomain.com/agents/16?return=%2Fagents -> /agents/16/dry_runs
foreman stdout | 10:07:25 web.1  | 192.168.1.1 - - [20/Jul/2020:03:07:25 PDT] "GET /worker_status?since_id=1562 HTTP/1.1" 200 124
10:07:25 web.1  | https://huginn.mydomain.com/agents/16?return=%2Fagents -> /worker_status?since_id=1562
foreman stdout | 10:07:28 web.1  | 192.168.1.1 - - [20/Jul/2020:03:07:28 PDT] "GET /worker_status?since_id=1562 HTTP/1.1" 200 124
10:07:28 web.1  | https://huginn.mydomain.com/agents/16?return=%2Fagents -> /worker_status?since_id=1562
foreman stdout | 10:07:30 web.1  | 192.168.1.1 - - [20/Jul/2020:03:07:30 PDT] "GET /worker_status?since_id=1562 HTTP/1.1" 200 124

```

I saw there was a slightly newer version of the docker image, ironically it's one of the email alerts that did not come through, and this is how I rebuild it using Podman on Fedora Server 32:

`podman create --name huginn --pod Huginn --restart on-failure:5 --env DATABASE_HOST=10.88.0.1 --env DATABASE_PORT=3306 --env DATABASE_ADAPTER=mysql2 --env DATABASE_ENCODING=utf8mb4 --env DATABASE_RECONNECT=true --env DO_NOT_CREATE_DATABASE=true --env DATABASE_NAME=huginn --env DATABASE_USERNAME=huginn --env DATABASE_PASSWORD=password --env SMTP_DOMAIN=huginn.mydomain.com --env SMTP_SERVER=mail.mydomain.com --env SMTP_PORT=25 --env SMTP_USER_NAME=none --env SMTP_PASSWORD= --env SMTP_AUTHENTICATION=none --env SEND_EMAIL_IN_DEVELOPMENT=true --env SMTP_ENABLE_STARTTLS_AUTO=false --env EMAIL_FROM_ADDRESS=huginn@mydomain.com --detach huginn/huginn`

Any suggestions, is there a simple test from within the container I can execute to check that SMTP is actually still ok? Apart from weekly updates to Fedora 32, nothing else has changed recently.

**Comment by JonasPf** [comment]
Same here. I'm using the Docker images and tried to roll back to the previous version. The last image that worked for me is tagged `856a0294c7f5b4e4bb6ff1137cfd8bca01488c91`.

**Comment by dsander** [comment]
Sorry for that, it should be fixed in the latest build.

**Comment by Taomyn** [comment]
No worries, thanks very much for the quick fix - confirmed working my end.
