### ISSUE TITLE
Error while parsing JSON with Website Agent when data is null: "undefined method `size' for nil:NilClass"

### ISSUE THREAD

**Issue by stevenirby** [huginn/huginn#2871]
I'm using the website agent to fetch JSON and it works until suddenly a field with an array in is `null`. 

When this happens I get this exception:

```
[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Fetching https://hnrss.org/newest.jsonfeed?q=notreal111
[00:00:01] INFO -- : Extracting json at $.items[*].content_html
[00:00:01] ERROR -- : Error when fetching url: undefined method `size' for nil:NilClass
/app/vendor/bundle/ruby/2.5.0/gems/jsonpath-1.0.1/lib/jsonpath/enumerable.rb:55:in `block in handle_wildecard'
/app/vendor/bundle/ruby/2.5.0/gems/jsonpath-1.0.1/lib/jsonpath/enumerable.rb:39:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/jsonpath-1.0.1/lib/jsonpath/enumerable.rb:39:in `handle_wildecard'
/app/vendor/bundle/ruby/2.5.0/gems/jsonpath-1.0.1/lib/jsonpath/enumerable.rb:25:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/jsonpath-1.0.1/lib/jsonpath/enumerable.rb:45:in `block in handle_wildecard'
/app/vendor/bundle/ruby/2.5.0/gems/jsonpath-1.0.1/lib/jsonpath/enumerable.rb:39:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/jsonpath-1.0.1/lib/jsonpath/enumerable.rb:39:in `handle_wildecard'
/app/vendor/bundle/ruby/2.5.0/gems/jsonpath-1.0.1/lib/jsonpath/enumerable.rb:25:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/jsonpath-1.0.1/lib/jsonpath/enumerable.rb:23:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/jsonpath-1.0.1/lib/jsonpath.rb:71:in `to_a'
/app/vendor/bundle/ruby/2.5.0/gems/jsonpath-1.0.1/lib/jsonpath.rb:71:in `on'
/app/lib/utils.rb:96:in `values_at'
```

Here is the JSON for the agent:

```
{
  "expected_update_period_in_days": "365",
  "url": "https://hnrss.org/newest.jsonfeed?q=notreal1111",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "description": {
      "path": "$.items[*].content_html"
    },
    "url": {
      "path": "$.items[*].url"
    }
  },
  "template": {
    "url": "<a href=\"{{ url }}\" target=\"_blank\">{{ url }}</a>"
  }
}
```

You can use this to see it populated with data (for testing):

```
{
  "expected_update_period_in_days": "365",
  "url": "https://hnrss.org/newest.jsonfeed?q=dang",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "description": {
      "path": "$.items[*].content_html"
    },
    "url": {
      "path": "$.items[*].url"
    }
  },
  "template": {
    "url": "<a href=\"{{ url }}\" target=\"_blank\">{{ url }}</a>"
  }
}
```

Here is the JSON that returned when there's data:

```
{
  "version": "https://jsonfeed.org/version/1",
  "title": "Hacker News - Newest: \"dang\"",
  "description": "Hacker News RSS",
  "home_page_url": "https://news.ycombinator.com/newest",
  "items": [
    {
      "id": "1234",
      "title": "some text",
      "content_html": "<p>some html/p>\n",
      "url": "https://example.com",
      "external_url": "https://example.com",
      "date_published": "2020-05-20T17:32:19Z",
      "author": "foobar"
    }
  ]
}
```

Here is the JSON response when there is no data:

```
{
  "version": "https://jsonfeed.org/version/1",
  "title": "Hacker News - Newest: \"notreal111\"",
  "description": "Hacker News RSS",
  "home_page_url": "https://news.ycombinator.com/newest",
  "items": null
}
```

Is there some magic workaround for dealing with JSON fields that are suddenly missing or null? Or maybe this is a bug?

**Comment by degan6** [comment]
Hello! It might be better to just capture the entire item as a separate event.

Try:
`{
  "expected_update_period_in_days": "365",
  "url": "https://hnrss.org/newest.jsonfeed?q=notreal1111",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "description": {
      "path": "$.items[*].content_html"
    },
    "url": {
      "path": "$.items[*].url"
    }
  },
  "template": {
    "url": "<a href=\"{{ url }}\" target=\"_blank\">{{ url }}</a>"
  }
}`

**Comment by stevenirby** [comment]
@degan6 I was going to do that but it's so much more work. Here's what I came up with.

For anyone else stuck on this like I was was. Here is a solution that I figured out which appears to work. You have to put all the fields as optional like this:

```
{
  ...
  "extract": {
    "url": {
      "path": "$.items[?(@.url)].url"
    },
    "description": {
      "path": "$.items[?(@.content_html)].content_html"
    },
    "title": {
      "path": "$.items[?(@.title)].title"
    }
  }
}
