### ISSUE TITLE
Question: how to format a list? 

### ISSUE THREAD

**Issue by zblesk** [huginn/huginn#2878]
I use a lot of RSS feed sources. For now it's starting to look like #2099, but I don't want to get that far, partly because of the way the diagram is laid out. 

The docs for the RSS source say: 

> url - The URL of the RSS feed (an array of URLs can also be used; items with identical guids across feeds will be considered duplicates). 

So maybe that could help. But I can't seem to figure out how to _format_ that list of URLs. I tried various permutations (with or without brackets, quotes, as a liquid expression) but nothing worked. I assume I'm missing something obvious. Any help appreciated!

**Comment by dsander** [comment]
Hi,

sorry for the late response, I don't understand how you want to format the list/array of URLs that are used in the RSSAgent. If you are trying to fetch multiple feeds this should work:

```json
{
  "expected_update_period_in_days": "5",
  "clean": "false",
  "url": [
    "https://github.com/huginn/huginn/commits/master.atom",
    "https://github.com/huginn/huginn/commits/master.atom"
  ]
}
```

**Comment by zblesk** [comment]
How do I do that? 
I tried copying those two URLs into the URL field, ended up with this: 

```
{
  "expected_update_period_in_days": "500",
  "clean": "false",
  "url": "[\"https://github.com/huginn/huginn/commits/master.atom\",     \"https://github.com/huginn/huginn/commits/master.atom\"]"
}
```

(i.e. if nothing else, the  brackets/newline/quotes got escaped) 

When trying to dry run, it seems to just treat that as a single URL and throws a huge error msg:

```
[00:00:00] INFO -- : Dry Run started
[00:00:00] ERROR -- : Failed to fetch ["https://github.com/huginn/huginn/commits/master.atom",     "https://github.com/huginn/huginn/commits/master.atom"] with message 'bad URI(is not URI?): ["https://github.com/huginn/huginn/commits/master.atom",     "https://github.com/huginn/huginn/commits/master.atom"]': ["/usr/lib/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split'", "/usr/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'", "/usr/lib/ruby/2.5.0/uri/rfc3986_parser.rb:117:in `convert_to_uri'", "/usr/lib/ruby/2.5.0/uri/generic.rb:1101:in `merge'", "/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.1/lib/faraday/connection.rb:415:in `build_exclusive_url'", "/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:192:in `build_env'", "/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'", "/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'", "/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.1/lib/faraday/connection.rb:149:in `get'", "/app/app/models/agents/rss_agent.rb:165:in `block in check_urls'", "/app/app/models/agents/rss_agent.rb:163:in `each'", "/app/app/models/agents/rss_agent.rb:163:in `check_urls'", "/app/app/models/agents/rss_agent.rb:154:in `check'", "/app/app/concerns/dry_runnable.rb:31:in `dry_run!'", "/app/app/controllers/agents/dry_runs_controller.rb:41:in `create'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/abstract_controller/base.rb:195:in `process_action'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/rendering.rb:30:in `process_action'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:135:in `run_callbacks'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/abstract_controller/callbacks.rb:41:in `process_action'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/rescue.rb:22:in `process_action'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'", "/app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/abstract_controller/base.rb:136:in `process'", "/app/vendor/bundle/ruby/2.5.0/gems/actionview-6.0.3.1/lib/action_view/rendering.rb:39:in `process'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal.rb:190:in `dispatch'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal.rb:254:in `dispatch'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:49:in `block in serve'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:32:in `each'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:32:in `serve'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:834:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'", "/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'", "/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/conditional_get.rb:40:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'", "/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/cookies.rb:648:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:101:in `run_callbacks'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:37:in `call_app'", "/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:26:in `block in call'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:28:in `tagged'", "/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `tagged'", "/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:26:in `call'", "/app/config/initializers/silence_worker_status_logger.rb:3:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/executor.rb:14:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/static.rb:126:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/engine.rb:527:in `call'", "/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/railtie.rb:190:in `public_send'", "/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/railtie.rb:190:in `method_missing'", "/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/handler/webrick.rb:95:in `service'", "/usr/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'", "/usr/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'", "/usr/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'"]
```

What am I doing wrong?

**Comment by zblesk** [comment]
Wow ok, my bad. 
Only after posting that previous question have I noticed the 'toggle view' button and edited the JSON directly. 
Then upon saving noticed there actually is a button to add a new array in the editor component... 

No wonder you were unsure what I'm asking about - it's _right there_. I've been using Huginn for 2 years and never noticed either of those. 🤦🏻‍♀️ 

Sorry about that. 😟

**Comment by dsander** [comment]
No worries, there is always something new to learn 😄
