### ISSUE TITLE
Dropbox Watch Agent fails on folders with subfolders

### ISSUE THREAD

**Issue by genem2** [huginn/huginn#2888]
My agent was working great until a sub-folder was created in the folder I was monitoring.  
I'm **_not_** looking for recursive monitoring.  Can folders found in the monitored dir only be checked for existence, or ignored?
If I move the sub-folder out, all's good.

```
undefined method `rev' for #<Dropbox::API::Dir:0x000014df91c25288>
/app/app/models/agents/dropbox_watch_agent.rb:55:in `block in ls'
/app/app/models/agents/dropbox_watch_agent.rb:55:in `map'
/app/app/models/agents/dropbox_watch_agent.rb:55:in `ls'
/app/app/models/agents/dropbox_watch_agent.rb:45:in `check'
/app/app/jobs/agent_check_job.rb:7:in `perform'
```
Running the docker from huginn/huginn.
```
{
  "dir_to_watch": "/newsletter production/NewsletterPrep/2011/Final Files",
  "expected_update_period_in_days": 60
}
```
_Tha**n**k you...._
_(Edit: typo)_

**Comment by genem2** [comment]
It appears this is no longer an issue.

I run the huginn/huginn from docker.hub, and I suspect some update to that docker resolved something that is now feeding dropbox_watch_agent.rb properly.  

Pays to wait!

**Comment by genem2** [comment]
Well, I guess I was too quick to close this issue. 
When it appeared to be fixed, there was no subfolder in the folder being monitored. Once a user created a subfolder, the error returned. 

I'll reopen incase anyone knows how to ignore directory entries inside the folder being watched.
