### ISSUE TITLE
"End of file reached" error when running example Afternoon Digest agent

### ISSUE THREAD

**Issue by sinewave** [huginn/huginn#2922]
Hi, just came across Huginn and it looks awesomee!

 1. I set it up on Unraid using this [docker container](https://github.com/selfhosters/unRAID-CA-templates/blob/master/templates/huginn.xml)
 2. Also created/updated the .env.example with my email settings

However I'm running into errors when trying to send out the example Afternoon Digest agent.

Here are my email settings:

```
# Uncomment if you want to use `/usr/sbin/sendmail` to send email instead of SMTP.
# This option is ignored unless RAILS_ENV=production, and setting it to `sendmail` causes the settings in the rest of this section (except EMAIL_FROM_ADDRESS) to be ignored.
# SMTP_DELIVERY_METHOD=sendmail

SMTP_DOMAIN=gmail.com
SMTP_USER_NAME=username
SMTP_PASSWORD="password"
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_SSL=false

# Set to true to send real emails via SMTP when running in the development Rails environment.
# Set to false to have emails intercepted in development and displayed at http://localhost:3000/letter_opener
SEND_EMAIL_IN_DEVELOPMENT=true
```

Here’s the error I'm getting:

```
end of file reached
/usr/lib/ruby/2.5.0/net/protocol.rb:189:in `rbuf_fill'
/usr/lib/ruby/2.5.0/net/protocol.rb:157:in `readuntil'
/usr/lib/ruby/2.5.0/net/protocol.rb:167:in `readline'
/usr/lib/ruby/2.5.0/net/smtp.rb:950:in `recv_response'
/usr/lib/ruby/2.5.0/net/smtp.rb:553:in `block in do_start'
/usr/lib/ruby/2.5.0/net/smtp.rb:960:in `critical'
/usr/lib/ruby/2.5.0/net/smtp.rb:553:in `do_start'
/usr/lib/ruby/2.5.0/net/smtp.rb:518:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/app/vendor/bundle/ruby/2.5.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/app/vendor/bundle/ruby/2.5.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
/app/vendor/bundle/ruby/2.5.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
/app/vendor/bundle/ruby/2.5.0/gems/actionmailer-6.0.3.1/lib/action_mailer/base.rb:589:in `block in deliver_mail'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/actionmailer-6.0.3.1/lib/action_mailer/base.rb:587:in `deliver_mail'
/app/vendor/bundle/ruby/2.5.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
/app/vendor/bundle/ruby/2.5.0/gems/actionmailer-6.0.3.1/lib/action_mailer/message_delivery.rb:115:in `block in deliver_now'
/app/vendor/bundle/ruby/2.5.0/gems/actionmailer-6.0.3.1/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/app/vendor/bundle/ruby/2.5.0/gems/actionmailer-6.0.3.1/lib/action_mailer/message_delivery.rb:114:in `deliver_now'
/app/app/models/agents/email_digest_agent.rb:61:in `block in check'
/app/app/models/agents/email_digest_agent.rb:52:in `each'
/app/app/models/agents/email_digest_agent.rb:52:in `check'
/app/app/jobs/agent_check_job.rb:7:in `perform'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:40:in `block in perform_now'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/i18n-1.8.2/lib/i18n.rb:313:in `with_locale'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:25:in `block (4 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:24:in `block (3 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:45:in `block in tag_logger'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:45:in `tag_logger'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:21:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:39:in `perform_now'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:25:in `block in execute'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/railtie.rb:43:in `block (4 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/reloader.rb:72:in `block in wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/reloader.rb:71:in `wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/railtie.rb:42:in `block (3 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:23:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:78:in `invoke_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:230:in `block in run'
/usr/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:229:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:213:in `block in work_off'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:212:in `times'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:212:in `work_off'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:172:in `loop'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:172:in `block in start'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:79:in `block in add'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:171:in `start'
/app/lib/delayed_job_worker.rb:6:in `run'
/app/app/concerns/long_runnable.rb:71:in `block in run!'`
```

**Comment by sinewave** [comment]
Update: I created a sendgrid account to try and get this going but ran into the same issue which leads me to believe that there could be another issue?
