### ISSUE TITLE
All jobs stuck hanging in the queue

### ISSUE THREAD

**Issue by spencerskinner99** [huginn/huginn#2928]
Hi, 

I have run into an issue during testing getting my tasks to run, currently I am attempting to simply run the basic default scenario tasks but they get stuck in a queue and never get run, I can only assume that some other task ahead of them is stuck and cant be cancelled. I have done a fresh install of huginn with a clean db on docker and the issue still persists.

```
version: '2'
services:
  huginn:
    image: huginn/huginn
    container_name: huginn
    hostname: huginn
    #network_mode: "service:vpn-huginn"
    network_mode: le_bridge
    restart: unless-stopped
    ports:
       - "3004:3004"
    depends_on:
      - mariadb-huginn
      #- vpn-huginn
    environment:
      PUID: 1001
      PGID: 1001
      PORT: 3004
      HUGINN_DATABASE_NAME: "huginn" 
      HUGINN_DATABASE_USERNAME: "huginn" 
      HUGINN_DATABASE_PASSWORD: "huginn" 
      DATABASE_HOST: 192.168.2.13
      DATABASE_PORT: 3308
      INVITATION_CODE: huginn
      TIMEZONE: Europe/London
    
  mariadb-huginn:
    image: mariadb
    container_name: mariadb-huginn
    hostname: mariadb-huggin
    network_mode: le_bridge
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: huginn
      MYSQL_DATABASE: huginn
      MYSQL_USER: huginn
      MYSQL_PASSWORD: huginn
    ports:
    - 3308:3306
    volumes:
    - /Docker_Configs/webmonitor/mariadb_huggin/db:/var/lib/mysql
```

I started to see this issue about 2 weeks ago but hadnt taken the time to look into it.

Below are my portainer logs from start up to my forcing a webagent to run, as far as I can see nothing appears asides the normal start up logs.

Is this simply an issue of poor configuration on my part here?

```
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32`.,
Using rake 13.0.1,
Using ace-rails-ap 2.0.1,
Using concurrent-ruby 1.1.6,
Using i18n 1.8.2,
Using minitest 5.14.1,
Using thread_safe 0.3.6,
Using tzinfo 1.2.7,
Using zeitwerk 2.3.0,
Using activesupport 6.0.3.1,
Using builder 3.2.4,
Using erubi 1.9.0,
Using mini_portile2 2.4.0,
Using nokogiri 1.10.9,
Using rails-dom-testing 2.0.3,
Using crass 1.0.6,
Using loofah 2.5.0,
Using rails-html-sanitizer 1.3.0,
Using actionview 6.0.3.1,
Using rack 2.2.2,
Using rack-test 1.1.0,
Using actionpack 6.0.3.1,
Using nio4r 2.5.2,
Using websocket-extensions 0.1.4,
Using websocket-driver 0.7.2,
Using actioncable 6.0.3.1,
Using globalid 0.4.2,
Using activejob 6.0.3.1,
Using activemodel 6.0.3.1,
Using activerecord 6.0.3.1,
Using mimemagic 0.3.5,
Using marcel 0.3.3,
Using activestorage 6.0.3.1,
Using mini_mime 1.0.2,
Using mail 2.7.1,
Using actionmailbox 6.0.3.1,
Using actionmailer 6.0.3.1,
Using actiontext 6.0.3.1,
Using public_suffix 3.0.2,
Using addressable 2.5.2,
Using jmespath 1.1.3,
Using aws-sdk-core 2.2.15,
Using bcrypt 3.1.13,
Using msgpack 1.3.1,
Using bootsnap 1.4.5,
Using kaminari-core 1.1.1,
Using kaminari-actionview 1.1.1,
Using kaminari-activerecord 1.1.1,
Using kaminari 1.1.1,
Using bundler 1.17.3,
Using method_source 0.9.2,
Using thor 0.20.3,
Using railties 6.0.3.1,
Using sprockets 3.7.2,
Using sprockets-rails 3.2.1,
Using rails 6.0.3.1,
Using bootstrap-kaminari-views 0.0.5,
Using buftok 0.2.0,
Using coffee-script-source 1.12.2,
Using execjs 2.7.0,
Using coffee-script 2.4.1,
Using coffee-rails 5.0.0,
Using cookiejar 0.3.2,
Using daemons 1.1.9,
Using declarative 0.0.9,
Using declarative-option 0.1.0,
Using delayed_job 4.1.8,
Using delayed_job_active_record 4.1.4 from https://github.com/dsander/delayed_job_active_record.git (at rails6-zeitwerk@ac2dfef),
Using orm_adapter 0.5.0,
Using responders 3.0.0,
Using warden 1.2.8,
Using devise 4.7.1,
Using unf_ext 0.0.7.4,
Using unf 0.1.4,
Using domain_name 0.5.20170404,
Using dotenv 2.0.1 from source at `vendor/gems/dotenv-2.0.1`,
Using dotenv-rails 2.0.1 from source at `vendor/gems/dotenv-2.0.1`,
Using hashie 3.5.6,
Using multi_json 1.13.1,
Using multipart-post 2.0.0,
Using faraday 0.12.1,
Using jwt 1.5.6,
Using multi_xml 0.6.0,
Using oauth2 1.4.0,
Using dropbox-api 0.5.0 from https://github.com/dsander/dropbox-api.git (at 86cb7b5@86cb7b5),
Using eventmachine 1.2.7,
Using em-socksify 0.3.0,
Using http_parser.rb 0.6.0,
Using em-http-request 1.1.2,
Using equalizer 0.0.11,
Using polyglot 0.3.5,
Using treetop 1.6.10,
Using erector 0.10.0 from https://github.com/dsander/erector.git (at rails6@821c2fa),
Using et-orbi 1.0.9,
Using ffi 1.12.2,
Using ethon 0.12.0,
Using evernote-thrift 1.25.1,
Using oauth 0.4.7,
Using evernote_oauth 0.2.3,
Using faraday_middleware 0.12.2,
Using sax-machine 1.3.2,
Using feedjira 3.1.0,
Using rb-fsevent 0.10.2,
Using rb-inotify 0.9.10,
Using sass-listen 4.0.0,
Using sass 3.7.4,
Using font-awesome-sass 4.7.0,
Using forecast_io 2.0.1,
Using foreman 0.63.0,
Using geokit 1.8.5,
Using geokit-rails 2.2.0,
Using little-plugger 1.1.4,
Using logging 2.2.2,
Using memoist 0.16.0,
Using os 0.9.6,
Using signet 0.7.3,
Using googleauth 0.5.1,
Using httpclient 2.8.3,
Using mime-types-data 3.2016.0521,
Using mime-types 3.1,
Using uber 0.1.0,
Using representable 3.0.4,
Using retriable 3.0.2,
Using google-api-client 0.13.0,
Using google-cloud-env 1.0.0,
Using google-cloud-core 1.0.0,
Using google-cloud-translate 1.0.0,
Using haversine 0.3.0,
Using httparty 0.14.0,
Using hipchat 1.2.0,
Using httmultiparty 0.3.16,
Using http-cookie 1.0.3,
Using http-form_data 1.0.1,
Using http 2.1.0,
Using huginn_agent 0.4.0,
Using hypdf 1.0.10,
Using jquery-rails 4.2.2,
Using json 2.3.0,
Using to_regexp 0.2.1,
Using jsonpath 1.0.1,
Using kgio 2.10.0,
Using kramdown 1.3.3,
Using libv8 7.3.492.27.1 (x86_64-linux),
Using liquid 4.0.3,
Using listen 3.0.8,
Using systemu 2.6.4,
Using macaddr 1.7.1,
Using memoizable 0.4.2,
Using mini_magick 4.9.5,
Using mini_racer 0.2.9,
Using mqtt 0.3.1,
Using mysql2 0.5.2,
Using naught 1.1.0,
Using net-ftp-list 3.2.8,
Using netrc 0.11.0,
Using omniauth 1.6.1,
Using omniauth-oauth2 1.3.1,
Using omniauth-37signals 1.0.5,
Using omniauth-dropbox-oauth2 0.3.0 from https://github.com/bamorim/omniauth-dropbox-oauth2.git (at 3504670@3504670),
Using omniauth-oauth 1.1.0,
Using omniauth-evernote 1.2.1,
Using omniauth-tumblr 1.2,
Using omniauth-twitter 1.3.0,
Using omniauth-wunderlist 0.0.2,
Using raindrops 0.17.0,
Using rb-kqueue 0.2.4,
Using rest-client 2.0.2,
Using rturk 2.12.1,
Using uuid 2.3.7,
Using ruby-growl 4.1,
Using rufus-scheduler 3.4.2,
Using sassc 2.3.0,
Using tilt 2.0.10,
Using sassc-rails 2.1.2,
Using sass-rails 6.0.0,
Using select2-rails 3.5.9.3,
Using simple_oauth 0.3.1,
Using slack-notifier 1.0.0,
Using spectrum-rails 1.3.4,
Using tumblr_client 0.8.5 from https://github.com/albertsun/tumblr_client.git (at e046fe6@e046fe6),
Using twilio-ruby 3.11.6,
Using twitter 5.15.0 from https://github.com/sferik/twitter.git (at master@d11707e),
Using twitter-stream 0.1.15 from https://github.com/cantino/twitter-stream.git (at huginn@a80822d),
Using typhoeus 1.3.1,
Using uglifier 2.7.2,
Using unicorn 5.1.0,
Using weibo_2 0.1.7 from https://github.com/albertsun/weibo_2.git (at master@ac38d04),
Using xmpp4r 0.5.6,
Bundle complete! 109 Gemfile dependencies, 187 gems now installed.,
Gems in the groups test and development were not installed.,
Bundled gems are installed into `./vendor/bundle`,
2021-01-03 18:08:16,869 INFO Included extra file "/etc/supervisor/conf.d/bootstrap.conf" during parsing,
2021-01-03 18:08:16,869 INFO Included extra file "/etc/supervisor/conf.d/foreman.conf" during parsing,
2021-01-03 18:08:16,869 INFO Included extra file "/etc/supervisor/conf.d/mysqld.conf" during parsing,
2021-01-03 18:08:16,877 INFO RPC interface 'supervisor' initialized,
2021-01-03 18:08:16,877 CRIT Server 'unix_http_server' running without any HTTP authentication checking,
2021-01-03 18:08:16,877 INFO supervisord started with pid 1,
2021-01-03 18:08:17,879 INFO spawned: 'stdout' with pid 578,
2021-01-03 18:08:17,882 INFO spawned: 'bootstrap' with pid 579,
2021-01-03 18:08:17,887 INFO success: bootstrap entered RUNNING state, process has stayed up for > than 0 seconds (startsecs),
2021-01-03 18:08:18,039 INFO spawned: 'mysqld' with pid 581,
2021-01-03 18:08:19,280 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2021-01-03 18:08:19,281 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
bootstrap stdout | DATABASE_HOST=192.168.2.13,
bootstrap stdout | Starting mysql server...,
mysqld stdout | 2021-01-03T18:08:18.236738Z mysqld_safe Logging to syslog.,
mysqld stdout | 2021-01-03T18:08:18.242269Z mysqld_safe Logging to '/var/log/mysql/error.log'.,
mysqld stdout | 2021-01-03T18:08:18.279386Z mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql,
2021-01-03 18:08:19,434 INFO spawned: 'foreman' with pid 983,
2021-01-03 18:08:19,434 INFO success: foreman entered RUNNING state, process has stayed up for > than 0 seconds (startsecs),
2021-01-03 18:08:19,451 INFO exited: bootstrap (exit status 0; expected),
foreman stderr | Database 'huginn' already exists,
foreman stdout | At least one User already exists, not seeding.,
foreman stdout | 18:08:32 web.1  | started with pid 1049,
18:08:32 jobs.1 | started with pid 1050,
foreman stdout | 18:08:35 web.1  | => Booting WEBrick,
18:08:35 web.1  | => Rails 6.0.3.1 application starting in production http://0.0.0.0:3004,
foreman stdout | 18:08:35 web.1  | => Run `rails server --help` for more startup options,
foreman stdout | 18:08:37 web.1  | [2021-01-03 18:08:37] INFO  WEBrick 1.4.2,
foreman stdout | 18:08:37 web.1  | [2021-01-03 18:08:37] INFO  ruby 2.5.8 (2020-03-31) [x86_64-linux-gnu],
foreman stdout | 18:08:37 web.1  | [2021-01-03 18:08:37] INFO  WEBrick::HTTPServer#start: pid=1051 port=3004,
foreman stdout | 18:08:37 jobs.1 | /app/lib/huginn_scheduler.rb:141:in `+': no implicit conversion of nil into String (TypeError),
18:08:37 jobs.1 | 	from /app/lib/huginn_scheduler.rb:141:in `block in setup',
18:08:37 jobs.1 | 	from /app/lib/huginn_scheduler.rb:140:in `times',
18:08:37 jobs.1 | 	from /app/lib/huginn_scheduler.rb:140:in `setup',
18:08:37 jobs.1 | 	from /app/app/concerns/long_runnable.rb:86:in `setup!',
18:08:37 jobs.1 | 	from /app/lib/agent_runner.rb:82:in `block in run_workers',
18:08:37 jobs.1 | 	from /app/lib/agent_runner.rb:79:in `each',
18:08:37 jobs.1 | 	from /app/lib/agent_runner.rb:79:in `run_workers',
18:08:37 jobs.1 | 	from /app/lib/agent_runner.rb:39:in `run',
18:08:37 jobs.1 | 	from /app/bin/threaded.rb:13:in `<top (required)>',
18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load',
18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/commands/runner/runner_command.rb:42:in `perform',
18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run',
18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command',
18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch',
18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/command/base.rb:69:in `perform',
18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/command.rb:46:in `invoke',
18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/commands.rb:18:in `<top (required)>',
foreman stdout | 18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require',
18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi',
18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register',
18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi',
18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require',
18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `block in require',
18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:291:in `load_dependency',
18:08:37 jobs.1 | 	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `require',
18:08:37 jobs.1 | 	from bin/rails:9:in `<main>',
foreman stdout | 18:08:37 jobs.1 | Starting HuginnScheduler,
foreman stdout | 18:08:37 jobs.1 | exited with code 1,
foreman stdout | 18:08:37 system | sending SIGTERM to all processes,
foreman stdout | 18:08:37 web.1  | terminated by SIGTERM,
2021-01-03 18:08:37,305 INFO exited: foreman (exit status 0; expected)
```

Thanks

**Comment by pcaro90** [comment]
I'm facing the same situation, with the same `foreman` error. In my case, it apparently started when I set the `TIMEZONE` env variable. It works without said variable.

**Comment by SebastianKoenig1** [comment]
Duplicate of #https://github.com/huginn/huginn/issues/3098

**Comment by spencerskinner99** [comment]
Completely forgot I made this ticket, so sorry
