### ISSUE TITLE
IMAP Folder Agent can't handle this symbol: ’    -  stops working after retrieval 

### ISSUE THREAD

**Issue by derd3000** [huginn/huginn#2936]
The IMAP Folder agent cannot handle emails which include this symbol:

````
’
````

When a mail comes in and it's text content contains the symbol the following error is displayed in logs:
````
Exception during check. "\xE2" from ASCII-8BIT to UTF-8
````

I think it is a quite easy to handle code bug, but I can not find the problem by myself.

Having read other topics about familiar problems it seems that the emails have for be force-encoded.
This is the complete log:

````
Exception during check. "\xE2" from ASCII-8BIT to UTF-8: /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/core_ext/object/json.rb:39:in `to_json'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/core_ext/object/json.rb:39:in `to_json'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/json-2.3.0/lib/json/common.rb:224:in `generate'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/json-2.3.0/lib/json/common.rb:224:in `generate'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/json-2.3.0/lib/json/common.rb:394:in `dump'
/home/huginn/huginn/lib/json_with_indifferent_access.rb:10:in `dump'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/type/serialized.rb:29:in `serialize'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/type/helpers/mutable.rb:8:in `cast'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute.rb:174:in `type_cast'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute.rb:42:in `value'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute.rb:155:in `changed_from_assignment?'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute.rb:59:in `changed?'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute_mutation_tracker.rb:76:in `attribute_changed?'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute_mutation_tracker.rb:46:in `changed?'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute_mutation_tracker.rb:16:in `block in changed_attribute_names'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute_mutation_tracker.rb:16:in `select'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activemodel-6.0.3.1/lib/active_model/attribute_mutation_tracker.rb:16:in `changed_attribute_names'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/attribute_methods/dirty.rb:145:in `changed_attribute_names_to_save'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/associations/association.rb:187:in `initialize_attributes'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/associations/association.rb:322:in `block in build_record'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/core.rb:327:in `initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/inheritance.rb:70:in `new'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/inheritance.rb:70:in `new'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/reflection.rb:158:in `build_association'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/associations/association.rb:321:in `build_record'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/associations/collection_association.rb:108:in `build'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/associations/collection_proxy.rb:316:in `build'
/home/huginn/huginn/app/models/agent.rb:112:in `build_event'
/home/huginn/huginn/app/models/agent.rb:121:in `create_event'
/home/huginn/huginn/app/concerns/dry_runnable.rb:88:in `create_event'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:310:in `block in check'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:392:in `block (3 levels) in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:391:in `each'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:391:in `block (2 levels) in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:344:in `each'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:344:in `block in each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:448:in `open'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:333:in `each_unread_mail'
/home/huginn/huginn/app/models/agents/imap_folder_agent.rb:213:in `check'
/home/huginn/huginn/app/jobs/agent_check_job.rb:7:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:40:in `block in perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/i18n-1.8.2/lib/i18n.rb:313:in `with_locale'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:25:in `block (4 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:24:in `block (3 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:45:in `block in tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:45:in `tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:21:in `block (2 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:39:in `perform_now'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:25:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/railtie.rb:43:in `block (4 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/reloader.rb:72:in `block in wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/reloader.rb:71:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/railtie.rb:42:in `block (3 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:23:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activejob-6.0.3.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:78:in `invoke_job'
/home/hug
````

**Comment by derd3000** [comment]
This is the same/related to these issues:

CLOSED: Issue with IMAP, hugginn on heroku "\xB7" from ASCII-8BIT to UTF-8
https://github.com/huginn/huginn/issues/733
The bugfix which was build after this issue did not fix the problem :(

OPEN: ImapFolderAgent error "\x92" from ASCII-8BIT to UTF-8
https://github.com/huginn/huginn/issues/2758

OPEN: "\xE7" from ASCII-8BIT to UTF-8
https://github.com/huginn/huginn/issues/2538

CLOSED: IMAP Agent causing strange UTF errors
https://github.com/huginn/huginn/issues/613

**Comment by derd3000** [comment]
Okay. I found the solution. It is a tiny thing in the imap_folder_agent.rb file.
At line 293:

`            'body' => mail`

has to be changed to:

`            'body' => mail.scrubbed(:body),`

After that you have to 
`sudo bundle exec rake production:export`

Now it is working. The patch which was used 5 years ago only encoded the subject, not the body...
@knu Could you add this patch?

**Comment by derd3000** [comment]
Problem with this solution seems to be, that conditions, which scan subject or body do not work anymore which makes the IMAP Agent nearly useless. It's a pitty. the from condition is working... My IMAP Agent which ignores every mail after is set a condition like this:

```
{
  "expected_update_period_in_days": "1",
  "host": "imap.gmail.com",
  "ssl": true,
  "username": "xxxxxx@gmail.com",
  "password": "xxxxxx",
  "folders": [
    "INBOX"
  ],
  "mark_as_read": "true",
  "conditions": {
    "body": "important",
    "from": "lalala@gmail.com"
  }
}
````
