### ISSUE TITLE
Credentials and variables

### ISSUE THREAD

**Issue by juryrigging** [huginn/huginn#2950]
I've been having a play with credentials as liquid variables. 

I tend to standardise my credential names from a scraped field. Having a field in the event that bears a resemblance to my credential names tends to be a good aide memoir when writing agents for which credential I intend to call. Bit odd, perhaps, but it helps. But given the standard naming I wondered if I could torture it by unholy means into a variable.

So I hooked up a manual event agent and sent the following event data (with an added "cred" field containing my credential call):

``` json
{
    "site": "Backpacking Light",
    "title": "Followed in Plain Sight",
    "author": "Shilletha Curtis",
    "url": "https://backpackinglight.com/followed-in-plain-sight/",
    "name": "BackpackingLight",
    "cred": "{% credential discord_BackpackingLight %}"
  }
```
To this post agent: 

``` json
{
  "post_url": "{{cred}}",
  "expected_receive_period_in_days": "28",
  "content_type": "json",
  "method": "post",
  "payload": {
   "content": "New {{author}} post:{% line_break %}{{title}}{% line_break %}{{url}}"
  },
  "emit_events": "true",
  "output_mode": "merge"
}
```
It happily sent the payload to the webhook. So far so good. Looks like credentials can be sent as liquid variables.

So I tried building a credential call with the event formatting agent:

``` json
{
  "instructions": {
     "cred": "{{name | prepend: '{% credential discord_' | append: ' %}' }}"
  },
  "mode": "merge"
}
```
And sent the same data, minus the "cred"  field, since I was creating that with this agent. The event came back looking identical to the data I had pasted into the manual event agent earlier. This seemed promising.

However, once it hit the post agent I got the error `bad URI(is not URI?): {% credential discord_BackpackingLight %}`.

I hooked up my manual event agent to the event formatting agent and sent the same event data as before (this time sending my credential call as "discord" in the manual event agent, because "cred" was in use by the event formatting agent and I want to compare the two), and got the following event:

``` json
{
  "site": "Backpacking Light",
  "title": "Followed in Plain Sight",
  "author": "Shilletha Curtis",
  "url": "https://backpackinglight.com/followed-in-plain-sight/",
  "name": "BackpackingLight",
  "discord": "[actual webhook url]",
  "cred": "{% credential discord_BackpackingLight %}"
}
```
Fair enough. "discord" looked much like "cred" in the event from the manual event agent. So it should resolve when it hits the next agent, right? 

Wrong. Piping it through another agent yields the same output—`"cred": "{% credential discord_BackpackingLight %}`— it doesn't resolve to the url, and I assume this is the cause of the error. I checked my work: copying the event formatting agent output and putting it back into a manual event agent connected to the post agent does send, so the outputted credential does appear to be valid.

So what makes it work when passed to the post agent by the manual event agent but not when passed by the event agent, when it appears to be the same field? 

I realise this seems a bit pointless, and whatever applications it could be used for have other, probably better, ways to be implemented. This was meant as a bit of fun to see if it could be done, and I've now spent several hours trying to understand *why* it's not working when as far as I can see it looks like it should. I have practically no experience with ruby, liquid, or json beyond mucking about trying to break agents, so I can well believe I'm missing something.

**Comment by juryrigging** [comment]
The full error:
```
Error Backtrace
                        bad URI(is not URI?): {% credential discord_BackpackingLight %}
/usr/lib/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split'
/usr/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
/usr/lib/ruby/2.5.0/uri/rfc3986_parser.rb:117:in `convert_to_uri'
/usr/lib/ruby/2.5.0/uri/generic.rb:1101:in `merge'
/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.1/lib/faraday/connection.rb:415:in `build_exclusive_url'
/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:192:in `build_env'
/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
/app/app/models/agents/post_agent.rb:205:in `handle'
/app/app/models/agents/post_agent.rb:159:in `block (2 levels) in receive'
/app/app/concerns/liquid_interpolatable.rb:64:in `interpolate_with'
/app/app/models/agents/post_agent.rb:154:in `block in receive'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/relation/delegation.rb:87:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/relation/delegation.rb:87:in `each'
/app/app/models/agents/post_agent.rb:153:in `receive'
/app/app/jobs/agent_receive_job.rb:8:in `perform'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:40:in `block in perform_now'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/i18n-1.8.2/lib/i18n.rb:313:in `with_locale'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:25:in `block (4 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:24:in `block (3 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:45:in `block in tag_logger'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:45:in `tag_logger'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/logging.rb:21:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:39:in `perform_now'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:25:in `block in execute'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/railtie.rb:43:in `block (4 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/reloader.rb:72:in `block in wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/reloader.rb:71:in `wrap'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/railtie.rb:42:in `block (3 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/execution.rb:23:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/activejob-6.0.3.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:78:in `invoke_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:230:in `block in run'
/usr/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:229:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:213:in `block in work_off'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:212:in `times'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:212:in `work_off'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:172:in `loop'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:172:in `block in start'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:79:in `block in add'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:171:in `start'
/app/lib/delayed_job_worker.rb:6:in `run'
/app/app/concerns/long_runnable.rb:71:in `block in run!'
```
