### ISSUE TITLE
Cant create any agents: ActionView::Template::Error (can't modify frozen String: ""):

### ISSUE THREAD

**Issue by positivegossip** [huginn/huginn#2956]
I'm running the lastest master branch on a Ubuntu instance.

When trying to create a new agent, I get a error message: "We're sorry, but something went wrong."

Checking Rails Application log /home/huginn/huginn/log/production.log returns the following:

```
[6112654e-7c91-4d34-96ba-694fc04ea4a9] ActionView::Template::Error (can't modify frozen String: ""):
[6112654e-7c91-4d34-96ba-694fc04ea4a9]     25:           <% if @agent.new_record? %>
[6112654e-7c91-4d34-96ba-694fc04ea4a9]     26:             <div class="form-group type-select">
[6112654e-7c91-4d34-96ba-694fc04ea4a9]     27:               <%= f.label :type %>
[6112654e-7c91-4d34-96ba-694fc04ea4a9]     28:               <%= f.select :type, options_for_select(agent_type_select_options, @agent.type), {}, class: 'form-control', autofocus: true %>
[6112654e-7c91-4d34-96ba-694fc04ea4a9]     29:             </div>
[6112654e-7c91-4d34-96ba-694fc04ea4a9]     30:           <% end %>
[6112654e-7c91-4d34-96ba-694fc04ea4a9]     31:         </div>
[6112654e-7c91-4d34-96ba-694fc04ea4a9]
[6112654e-7c91-4d34-96ba-694fc04ea4a9] (eval):2:in `new'
[6112654e-7c91-4d34-96ba-694fc04ea4a9] (eval):2:in `html_description'
[6112654e-7c91-4d34-96ba-694fc04ea4a9] app/helpers/agent_helper.rb:94:in `block (2 levels) in agent_type_select_options'
[6112654e-7c91-4d34-96ba-694fc04ea4a9] app/helpers/agent_helper.rb:94:in `map'
[6112654e-7c91-4d34-96ba-694fc04ea4a9] app/helpers/agent_helper.rb:94:in `block in agent_type_select_options'
[6112654e-7c91-4d34-96ba-694fc04ea4a9] app/helpers/agent_helper.rb:93:in `agent_type_select_options'
[6112654e-7c91-4d34-96ba-694fc04ea4a9] app/views/agents/_form.html.erb:28
[6112654e-7c91-4d34-96ba-694fc04ea4a9] app/views/agents/_form.html.erb:12
[6112654e-7c91-4d34-96ba-694fc04ea4a9] app/views/agents/new.html.erb:14
[6112654e-7c91-4d34-96ba-694fc04ea4a9] config/initializers/silence_worker_status_logger.rb:3:in `call'
```

Any idea how to fix this issue? Thank you.

**Comment by MarkStanhope** [comment]
I have the same problem, running on Ubuntu 20.04

**Comment by positivegossip** [comment]
I found out why this issue is happening.

The root cause fix is to upgrade rubygems. `gem update --system`

Specially foreman needs to be on the newest version.

**Comment by nkakouros** [comment]
I have the same issue and updating did not help.

**Comment by goodnewz** [comment]
> I have the same issue and updating did not help.

So I had the same issue and moving to Ruby 2.6.6 did help me. See this comment for more details: 

https://github.com/huginn/huginn/issues/2822#issuecomment-652284732
