### ISSUE TITLE
Could not find 'dotenv'

### ISSUE THREAD

**Issue by Axel12321** [huginn/huginn#2985]
Hi guys! I have a problem with huginn set up. I installed everything correctly but when i run the command "foreman start" these are the results: 

Traceback (most recent call last):
	8: from /home/alexandros/gems/bin/foreman:23:in `<main>'
	7: from /usr/lib/ruby/2.7.0/rubygems.rb:295:in `activate_bin_path'
	6: from /usr/lib/ruby/2.7.0/rubygems.rb:295:in `synchronize'
	5: from /usr/lib/ruby/2.7.0/rubygems.rb:296:in `block in activate_bin_path'
	4: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1373:in `activate'
	3: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1391:in `activate_dependencies'
	2: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1391:in `each'
	1: from /usr/lib/ruby/2.7.0/rubygems/specification.rb:1402:in `block in activate_dependencies'

/usr/lib/ruby/2.7.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'dotenv' (>= 0.7) among 303 total gem(s) (Gem::MissingSpecError)

Checked in 'GEM_PATH=/home/alexandros/.gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/share/rubygems-integration/2.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0:/home/alexandros/gems', execute `gem env` for more information

do i have to install the "dotenv" gem and place in the gem file or what i dont get it please help! <3

**Comment by Axel12321** [comment]
i installed it with "gem install dotenv" and then i did bundle install im not sure tho but something like that works
