### ISSUE TITLE
docker: problem with single container `huginn/huginn-single-process`, multiple workers + twitter

### ISSUE THREAD

**Issue by dreamcat4** [huginn/huginn#2991]
Hi there,
Don't particularly know if this bug affects any other specific configurations. However the configuration I was able to reproduce it with is as follows:

* Seperate PGSQL Database `image: postgres`
* Using official Huggin docker image `huginn/huginn-single-process`
* Using tag `latest` (tag `4d17829cf6b15b004ad3f4be196303dca4944810`, digest=`c794eddc7b47e7d39a55c5d6f0813388f289514d68467b24166b861eb0bfe540`)

Setting these ENVs in Compose orchestration tool:

```yaml
    env:
      - RAILS_ENV=production
      - DATABASE_ADAPTER=postgresql
      - POSTGRES_PORT_5432_TCP_ADDR=huginn.postgres.lan
      - WORKER_CMD=bin/threaded.rb
```

Then Huggin fails to start and with no log output after the line:

```sh
Bundled gems are installed into `./vendor/bundle`
```
HOWEVER, after addint the following ENV variable:

* `DATABASE_NAME=huginn`

 Then a stacktrace does occur. Which is precisely as follows: 

```sh
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32`.
Fetching gem metadata from https://rubygems.org/......
Using rake 13.0.1
Using ace-rails-ap 2.0.1
Using concurrent-ruby 1.1.6
Using minitest 5.14.1
Using thread_safe 0.3.6
Using zeitwerk 2.3.0
Using builder 3.2.4
Using erubi 1.9.0
Using mini_portile2 2.4.0
Using crass 1.0.6
Using rack 2.2.2
Using nio4r 2.5.2
Using websocket-extensions 0.1.4
Using mimemagic 0.3.5
Using mini_mime 1.0.2
Using public_suffix 3.0.2
Using jmespath 1.1.3
Using bcrypt 3.1.13
Using msgpack 1.3.1
Using kaminari-core 1.1.1
Using bundler 1.17.3
Using method_source 0.9.2
Using thor 0.20.3
Using buftok 0.2.0
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using cookiejar 0.3.2
Using daemons 1.1.9
Using declarative 0.0.9
Using declarative-option 0.1.0
Using orm_adapter 0.5.0
Using unf_ext 0.0.7.4
Using dotenv 2.0.1 from source at `vendor/gems/dotenv-2.0.1`
Using hashie 3.5.6
Using multi_json 1.13.1
Using multipart-post 2.0.0
Using jwt 1.5.6
Using multi_xml 0.6.0
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using equalizer 0.0.11
Using polyglot 0.3.5
Using ffi 1.12.2
Using evernote-thrift 1.25.1
Using oauth 0.4.7
Using sax-machine 1.3.2
Using rb-fsevent 0.10.2
Using little-plugger 1.1.4
Using memoist 0.16.0
Using os 0.9.6
Using httpclient 2.8.3
Using mime-types-data 3.2016.0521
Using uber 0.1.0
Using retriable 3.0.2
Using haversine 0.3.0
Using http-form_data 1.0.1
Using json 2.3.0
Using to_regexp 0.2.1
Using kgio 2.10.0
Using kramdown 1.3.3
Using libv8 7.3.492.27.1 (x86_64-linux)
Using liquid 4.0.3
Using systemu 2.6.4
Using mini_magick 4.9.5
Using mqtt 0.3.1
Using naught 1.1.0
Using net-ftp-list 3.2.8
Using netrc 0.11.0
Using raindrops 0.17.0
Using tilt 2.0.10
Using simple_oauth 0.3.1
Using slack-notifier 1.0.0
Using xmpp4r 0.5.6
Using i18n 1.8.2
Using tzinfo 1.2.7
Using memoizable 0.4.2
Using nokogiri 1.10.9
Using websocket-driver 0.7.2
Using marcel 0.3.3
Using mail 2.7.1
Fetching pg 1.1.3
Using addressable 2.5.2
Using aws-sdk-core 2.2.15
Using bootsnap 1.4.5
Using coffee-script 2.4.1
Using huginn_agent 0.4.0
Using select2-rails 3.5.9.3
Using unf 0.1.4
Using faraday 0.12.1
Using em-socksify 0.3.0
Using treetop 1.6.10
Using ethon 0.12.0
Using evernote_oauth 0.2.3
Using rb-inotify 0.9.10
Using geokit 1.8.5
Using httparty 0.14.0
Using rb-kqueue 0.2.4
Using sassc 2.3.0
Using twilio-ruby 3.11.6
Using logging 2.2.2
Using mime-types 3.1
Using representable 3.0.4
Using jsonpath 1.0.1
Using macaddr 1.7.1
Using mini_racer 0.2.9
Using uglifier 2.7.2
Using activesupport 6.0.3.1
Using loofah 2.5.0
Using rack-test 1.1.0
Using sprockets 3.7.2
Using warden 1.2.8
Using et-orbi 1.0.9
Using omniauth 1.6.1
Using twitter-stream 0.1.15 from https://github.com/cantino/twitter-stream.git (at huginn@a80822d)
Using unicorn 5.1.0
Using domain_name 0.5.20170404
Using dotenv-rails 2.0.1 from source at `vendor/gems/dotenv-2.0.1`
Using oauth2 1.4.0
Using faraday_middleware 0.12.2
Using forecast_io 2.0.1
Using foreman 0.63.0
Using signet 0.7.3
Using google-cloud-env 1.0.0
Using rails-dom-testing 2.0.3
Using rails-html-sanitizer 1.3.0
Using globalid 0.4.2
Using activemodel 6.0.3.1
Using delayed_job 4.1.8
Using erector 0.10.0 from https://github.com/dsander/erector.git (at rails6@821c2fa)
Using feedjira 3.1.0
Using sass-listen 4.0.0
Using hipchat 1.2.0
Using httmultiparty 0.3.16
Using http-cookie 1.0.3
Using listen 3.0.8
Using omniauth-oauth 1.1.0
Using uuid 2.3.7
Using rufus-scheduler 3.4.2
Using typhoeus 1.3.1
Using dropbox-api 0.5.0 from https://github.com/dsander/dropbox-api.git (at 86cb7b5@86cb7b5)
Using omniauth-oauth2 1.3.1
Using tumblr_client 0.8.5 from https://github.com/albertsun/tumblr_client.git (at e046fe6@e046fe6)
Using actionview 6.0.3.1
Using activejob 6.0.3.1
Using activerecord 6.0.3.1
Using em-http-request 1.1.2
Using sass 3.7.4
Using googleauth 0.5.1
Using http 2.1.0
Using hypdf 1.0.10
Using rest-client 2.0.2
Using omniauth-evernote 1.2.1
Using omniauth-tumblr 1.2
Using omniauth-twitter 1.3.0
Using ruby-growl 4.1
Using omniauth-37signals 1.0.5
Using omniauth-dropbox-oauth2 0.3.0 from https://github.com/bamorim/omniauth-dropbox-oauth2.git (at 3504670@3504670)
Using omniauth-wunderlist 0.0.2
Using actionpack 6.0.3.1
Using kaminari-actionview 1.1.1
Using kaminari-activerecord 1.1.1
Using delayed_job_active_record 4.1.4 from https://github.com/dsander/delayed_job_active_record.git (at rails6-zeitwerk@ac2dfef)
Using font-awesome-sass 4.7.0
Using twitter 5.15.0 from https://github.com/sferik/twitter.git (at master@d11707e)
Using rturk 2.12.1
Using weibo_2 0.1.7 from https://github.com/albertsun/weibo_2.git (at master@ac38d04)
Using actioncable 6.0.3.1
Using activestorage 6.0.3.1
Using actionmailer 6.0.3.1
Using railties 6.0.3.1
Using sprockets-rails 3.2.1
Using kaminari 1.1.1
Using actionmailbox 6.0.3.1
Using actiontext 6.0.3.1
Using coffee-rails 5.0.0
Using responders 3.0.0
Using jquery-rails 4.2.2
Using sassc-rails 2.1.2
Using spectrum-rails 1.3.4
Using rails 6.0.3.1
Using google-api-client 0.13.0
Using google-cloud-core 1.0.0
Using devise 4.7.1
Using sass-rails 6.0.0
Using bootstrap-kaminari-views 0.0.5
Using geokit-rails 2.2.0
Using google-cloud-translate 1.0.0
Installing pg 1.1.3 with native extensions
Bundle complete! 109 Gemfile dependencies, 187 gems now installed.
Gems in the groups test and development were not installed.
Bundled gems are installed into `./vendor/bundle`
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `async_exec': PG::UndefinedTable: ERROR:  relation "agents" does not exist (ActiveRecord::StatementInvalid)
LINE 8:  WHERE a.attrelid = '"agents"'::regclass
                            ^
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:65:in `block (2 levels) in query'
	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `block in query'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:722:in `block (2 levels) in log'
	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:721:in `block in log'
	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `log'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `query'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql_adapter.rb:820:in `column_definitions'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:114:in `columns'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/schema_cache.rb:76:in `columns'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/schema_cache.rb:82:in `columns_hash'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/model_schema.rb:488:in `load_schema!'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/attributes.rb:247:in `load_schema!'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/attribute_decorators.rb:50:in `load_schema!'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/model_schema.rb:478:in `block in load_schema'
	from /usr/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/model_schema.rb:475:in `load_schema'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/model_schema.rb:352:in `columns_hash'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/inheritance.rb:82:in `descends_from_active_record?'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/inheritance.rb:88:in `finder_needs_type_condition?'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/core.rb:297:in `relation'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/scoping/named.rb:57:in `default_scoped'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/scoping/named.rb:44:in `all'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/scoping/named.rb:192:in `block in scope'
	from /app/app/models/agents/twitter_stream_agent.rb:135:in `setup_worker'
	from /app/lib/agent_runner.rb:94:in `block (2 levels) in load_workers'
	from /app/lib/agent_runner.rb:62:in `block in with_connection'
	from /app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
	from /app/lib/agent_runner.rb:61:in `with_connection'
	from /app/lib/agent_runner.rb:93:in `block in load_workers'
	from /app/lib/agent_runner.rb:89:in `each'
	from /app/lib/agent_runner.rb:89:in `load_workers'
	from /app/lib/agent_runner.rb:69:in `run_workers'
	from /app/lib/agent_runner.rb:39:in `run'
	from /app/bin/threaded.rb:13:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	from /app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/commands/runner/runner_command.rb:42:in `perform'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/command/base.rb:69:in `perform'
	from /app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/command.rb:46:in `invoke'
	from /app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `block in require'
	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `require'
	from bin/rails:9:in `<main>'
```

So according to that stacktrace it seems like something to do with starting twitter worker agents.

Then I removed the following ENV config variable:

* `WORKER_CMD=bin/threaded.rb`

And the exception is gone, and Huggin will startup normally. And Huggin works fine. But there is no longer any extra worker ruby threads spawned right? So I guess it must be operating in a mode which is slower to service requests etc.

Is this a normal error message? Because I could not find it anywhere here in the issues tracker. Is there something wrong or broken in the official Huggin docker image?

Another interesting point was I noticed that one of the gem dependancies (for twitter) looks a bit old now. With newer versions available:

```sh
Using twitter 5.15.0 from https://github.com/sferik/twitter.git (at master@d11707e)
```

So do you think that mounting a new bundler gems list into the container to update any such gem(s) versions would have any bearing on this specific type of error message and be worth trying at all? Or is the error instead not anything to do with that, but to do with being unable to spawn workers?

Because I think I read the instructions page on Github here correctly. It says to use this env var to do it:

* `WORKER_CMD=bin/threaded.rb`

So what is wrong here? I do not think anybody much uses this method. However I would like to very much so. Many thanks.

BTW it does not appear to matter (error still occurs) even if...

* Remove all of the `TWITTER_` api ENV vars settings
* Start with a brand new clean empty database, which no longer contains any sorts of user added data entries about twitter

**Comment by dreamcat4** [comment]
It would seem the exception occurs when `CMD` being run is:

```sh
exec bundle exec rails runner "bin/threaded.rb" RAILS_ENV=production
```

whatever that means (sorry IDK rails stuff) but it starts up over here...

https://github.com/huginn/huginn/blob/master/bin/threaded.rb
