### ISSUE TITLE
Webagent failing CA check, docker version

### ISSUE THREAD

**Issue by Taomyn** [huginn/huginn#3027]
Hi, I use the docker version of Huginn on my Fedora server and now one of my web agents is failing due to a CA certificate issue - another victim of the Let's Encrypt certificate expiration:

`[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Fetching https://voiceattack.com/Default.aspx
[00:00:00] ERROR -- : Error when fetching url: Peer certificate cannot be authenticated with given CA certificates
/app/vendor/bundle/ruby/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/adapters/faraday.rb:106:in `block in request'
/app/vendor/bundle/ruby/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/callbacks.rb:146:in `block in execute_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/callbacks.rb:145:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/callbacks.rb:145:in `execute_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/operations.rb:35:in `finish'
/app/vendor/bundle/ruby/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/easy_factory.rb:164:in `block in set_callback'
/app/vendor/bundle/ruby/2.5.0/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `block in complete'
/app/vendor/bundle/ruby/2.5.0/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/ethon-0.12.0/lib/ethon/easy/response_callbacks.rb:68:in `complete'
/app/vendor/bundle/ruby/2.5.0/gems/ethon-0.12.0/lib/ethon/easy/operations.rb:33:in `perform'
/app/vendor/bundle/ruby/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/operations.rb:16:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/cacheable.rb:18:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/block_connection.rb:31:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/stubbable.rb:25:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/request/before.rb:26:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/adapters/faraday.rb:82:in `perform_request'
/app/vendor/bundle/ruby/2.5.0/gems/typhoeus-1.3.1/lib/typhoeus/adapters/faraday.rb:72:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/gzip.rb:24:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.1/lib/faraday/request/url_encoded.rb:15:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.1/lib/faraday/request/multipart.rb:15:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
/app/vendor/bundle/ruby/2.5.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
/app/app/concerns/web_request_concern.rb:26:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
/app/vendor/bundle/ruby/2.5.0/gems/faraday-0.12.1/lib/faraday/connection.rb:149:in `get'
/app/app/models/agents/website_agent.rb:397:in `check_url'
/app/app/models/agents/website_agent.rb:386:in `block in check_urls'
/app/app/models/agents/website_agent.rb:385:in `each'
/app/app/models/agents/website_agent.rb:385:in `check_urls'
/app/app/models/agents/website_agent.rb:379:in `check'
/app/app/concerns/sortable_events.rb:92:in `check'
/app/app/concerns/dry_runnable.rb:31:in `dry_run!'
/app/app/controllers/agents/dry_runs_controller.rb:41:in `create'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/abstract_controller/base.rb:195:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/activerecord-6.0.3.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/abstract_controller/base.rb:136:in `process'
/app/vendor/bundle/ruby/2.5.0/gems/actionview-6.0.3.1/lib/action_view/rendering.rb:39:in `process'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal.rb:190:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_controller/metal.rb:254:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:32:in `each'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:32:in `serve'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:834:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
/app/vendor/bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/conditional_get.rb:40:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/cookies.rb:648:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:101:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:37:in `call_app'
/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:26:in `block in call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `tagged'
/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:26:in `call'
/app/config/initializers/silence_worker_status_logger.rb:3:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/static.rb:126:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/engine.rb:527:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/railtie.rb:190:in `public_send'
/app/vendor/bundle/ruby/2.5.0/gems/railties-6.0.3.1/lib/rails/railtie.rb:190:in `method_missing'
/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/handler/webrick.rb:95:in `service'
/usr/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
/usr/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
/usr/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
[00:00:00] INFO -- : Dry Run finished`

Is there anything I can do to update it so it recognises the new CA? My Fedora 34 server is up-to-date as far as I can tell.

**Comment by degan6** [comment]
@Taomyn , I'm glad its fixed for you. I also just fixed the issue, minutes ago but had some pain getting it to work.

For anyone reading this. I run Huginn on Debian. After running the `upgrade ca-certificates`  in everyway possible and doing an in-place upgrade upgrading from Debian 9 to 10 it still didn't grab the new cert.

I ended up just adding the new [R3 cert](https://letsencrypt.org/certificates/) to the servers store [with this article](https://manuals.gfi.com/en/kerio/connect/content/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html). You'll want to dem version of the file from LE and rename it as a crt file.

```
wget https://letsencrypt.org/certs/lets-encrypt-r3.pem
sudo cp lets-encrypt-r3.pem /usr/local/share/ca-certificates/r3.crt
```

This is not the right way to do this as the cert should be included in the bundle from the CA package. But after a few hours I gave up and just wanted it to work.

**Comment by gingerbeardman** [comment]
I also had this around the period my let's encrypt failed to renew on time. It fixed itself when the renew succeeded, but the errors remained in the job log.
