### ISSUE TITLE
Twitter Service not showing up (Huginn on docker)

### ISSUE THREAD

**Issue by sergio-ns** [huginn/huginn#3037]
I have Huginn running in a docker container, twitter keys have been added to the .env file.
3-legged OAuth is enabled for my Twitter app, not doing so would cause a "We're sorry something went wrong" error.

When clicking on the "Authenticate with Twitter" button I'm led to the Twitter authentication page, after entering the password I get a"Redirecting you back to your application. This may take a few moments" message, as expected, after which I'm driven back to the Huginn services page.
Still no Twitter service is displayed in the list (see image)
It's basically what happens in #2966 but I doubt that the solution mentioned there applies to a docker deployment

Thanks
![r8d2AFp](https://user-images.githubusercontent.com/46521034/142736321-9a6dc92c-e0ff-4c3c-a654-d2e0c5eef780.png)

**Comment by jhk5263** [comment]
We have the same problem

**Comment by spaskob** [comment]
Same problem.

**Comment by jangliss** [comment]
Having the same issues using latest (2b01bb295063) docker image. Not finding the log/production.log that is mentioned in several documents, so I cannot see any issues there.  I've done the callback URLs in twitter also mentioned in other documents as well /auth/twitter, /auth/twitter/callback, /users/auth/twitter, /users/auth/twitter/callback.

**Comment by upuldi** [comment]
I am having the same issue. Does anyone have a fix?

**Comment by kcebul12** [comment]
same thing here running Huginn on a Debian 9 VPS

**Comment by SebastianKoenig1** [comment]
Have exactly the same issue with the current docker image. Anyone any idea how to solve this issue?

**Comment by jangliss** [comment]
I've been sporadically poking at this, and this evening I tried enabling test environment by setting `RAILS_ENV=test`. When I navigate to Services and click on "Authenticate with Twitter" the error below is dumped to stderr

```
foreman stdout | 03:35:44 web.1  | [2022-03-22 22:35:44] ERROR RuntimeError: Could not find a valid mapping for path "/auth/twitter"
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/devise-4.7.1/lib/devise/mapping.rb:51:in `find_by_path!'
foreman stdout | 03:35:44 web.1  |  /app/vendor/bundle/ruby/2.6.0/gems/devise-4.7.1/lib/devise/omniauth.rb:19:in `block in <main>'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:491:in `fail!'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/omniauth-oauth-1.1.0/lib/omniauth/strategies/oauth.rb:41:in `rescue in request_phase'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/omniauth-oauth-1.1.0/lib/omniauth/strategies/oauth.rb:27:in `request_phase'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/omniauth-twitter-1.3.0/lib/omniauth/strategies/twitter.rb:61:in `request_phase'
foreman stdout | 03:35:44 web.1  |  /app/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:226:in `request_call'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:188:in `call!'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
foreman stdout | 03:35:44 web.1  |  /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
foreman stdout | 03:35:44 web.1  |  /app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/middleware/cookies.rb:654:in `call'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
03:35:44 web.1  |   /app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:101:in `run_callbacks'
```

This seems to suggest that the registration of routes for `/auth/twitter` has not occurred. On some searching around, I've found this seems to come up if an error occurs and the request is sent back to `Devise`, which results in the `routes` not being processed.

- https://github.com/huginn/huginn/issues/2892
- https://github.com/heartcombo/devise/issues/2004
- https://github.com/swapmyvote/swapmyvote/pull/333

I don't know enough ruby (any at all really) to really dig in and troubleshoot, and the docker container is missing any kind of editor to try adding in any extra debugging code.

**Comment by fireshaper** [comment]
I'm also having the same problem. All of my env vars are set in docker and I get to authenticate on Twitter just fine. It's just like Huginn isn't saving the Service.

**Comment by jangliss** [comment]
Tested again today with the updated docker image (971806eb0c48).  Seems to have progressed a little bit further, though still seeing issues.  I do now get redirected to the Twitter OAuth page as expected, sign in works, get sent back to huginn as you'd expect, but the /services page is exactly the same as before, with the authenticate twitter button as if the authentication hadn't actually worked.  Logs seem to show the redirect and oauth data being sent back from twitter successfully:

```
huginn_1  | 05:10:52 web.1  | [b4e9fc3c-6629-4b9a-b522-7e3c4041f609] Started GET "/auth/twitter/callback?oauth_token=5dXXXXXXXXXX&oauth_verifier=5RXXXXXX" for 172.31.0.3 at 2022-05-30 00:10:09 -0500
huginn_1  | 05:10:52 web.1  | [b4e9fc3c-6629-4b9a-b522-7e3c4041f609] (twitter) Callback phase initiated.
huginn_1  | 05:10:52 web.1  | [b4e9fc3c-6629-4b9a-b522-7e3c4041f609] Processing by OmniauthCallbacksController#twitter as HTML
huginn_1  | foreman stdout | 05:10:52 web.1  | [b4e9fc3c-6629-4b9a-b522-7e3c4041f609]   Parameters: {"oauth_token"=>"5dXXXXXX", "oauth_verifier"=>"5RXXXXX"}
huginn_1  | 05:10:52 web.1  | [b4e9fc3c-6629-4b9a-b522-7e3c4041f609] Redirected to https://huginn.XXXXXXX/services
huginn_1  | 05:10:52 web.1  | [b4e9fc3c-6629-4b9a-b522-7e3c4041f609] Completed 302 Found in 33ms (ActiveRecord: 11.4ms | Allocations: 10632)
```

**Comment by xux1217** [comment]
Occur the same issue. Still not work in docker.

**Comment by wuyuansheng1982** [comment]
Same issue with docker, It errors out directly, not taken to twitter for credentials at all.

**Comment by nitlott** [comment]
any workaround on this would be greatful :)

**Comment by jelofsson** [comment]
Mine just errors out directly saying `We're sorry, but something went wrong.`.

**Comment by jelofsson** [comment]
> Same issue with docker, It errors out directly, not taken to twitter for credentials at all.

Double check that you are using the `Consumer API Keys`, they are the correct ones to use.
