### ISSUE TITLE
Huginn uses half of CPU after upgrading from Ubuntu 18 to Ubuntu 20

### ISSUE THREAD

**Issue by Pcsl** [huginn/huginn#3040]
I'm not sure what happened with Huginn after upgrading my VPS to Ubuntu 20.04.3 LTS. It seems it affected some setups of Huginn because when accessing Huginn via my browser, I get a '502 bad gateway' error.

However, the worst part is that even if I stop the Huginn service the process keep running no matter what (user huginn, command ruby) and it is always taking up 50 % of my CPU as I'm in a shared server I'm afraid that not being able to solve it will make my server to be shut down by the provider.

I'm getting errors like this in my Unicorn.log
`2021/11/29 10:01:06 [crit] 51722#51722: *53 connect() to unix:/home/huginn/huginn/tmp/sockets/unicorn.socket failed (13: Permission denied) while connecting to upstream, client: *hidden IP*, server: your_server_fqdn, request: "GET / HTTP/1.1", upstream: "http://unix:/home/huginn/huginn/tmp/sockets/unicorn.socket:/502.html", host: "*hidden host*"`

Production.log shows this kind of error that look related to MySQL but I'm unable to fix it
```

I, [2021-11-28T19:34:44.743324 #451]  INFO -- : 2021-11-28T19:34:44-0800: [Worker(host:*hidden hostname* pid:451)] Error while reserving job: Mysql2::Error::ConnectionError: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2): SELECT  `delayed_jobs`.* FROM `delayed_jobs` WHERE ((run_at <= '2021-11-29 03:34:44.741305' AND (locked_at IS NULL OR locked_at < '2021-11-29 03:32:44.741356') OR locked_by = 'host:*hidden hostname* pid:451') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 5
I, [2021-11-28T19:34:49.405917 #451]  INFO -- : 2021-11-28T19:34:49-0800: [Worker(host:*hidden hostname* pid:451)] Starting job worker
I, [2021-11-28T19:34:49.407193 #451]  INFO -- : 2021-11-28T19:34:49-0800: [Worker(host:*hidden hostname* pid:451)] Error while reserving job: Can't connect to local MySQL server through socket 
```

Any help to solve this or at least stop Ruby taking so much CPU resources would be great.
Thank you.

**Comment by Pcsl** [comment]
I was able to stop it after reinstalling Ruby and other packages. However, now I am getting this error that I can't resolve:

```
I, [2021-11-30T11:30:38.889100 #88485]  INFO -- : Refreshing Gem list
/usr/local/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
bundler: failed to load command: unicorn (/home/huginn/huginn/vendor/bundle/ruby/2.6.0/bin/unicorn)
NoMethodError: private method `allowed_tags' called for #<Rails::Html::SafeListSanitizer:0x00005579bf8a5ed8>
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/actionview-6.0.3.1/lib/action_view/helpers/sanitize_helper.rb:132:in `sanitized_allowed_tags'
  /home/huginn/huginn/config/initializers/sanitizer.rb:1:in `<main>'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:318:in `block in load'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:291:in `load_dependency'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:318:in `load'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.1/lib/rails/engine.rb:666:in `block in load_config_initializer'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:182:in `instrument'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.1/lib/rails/engine.rb:665:in `load_config_initializer'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.1/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.1/lib/rails/engine.rb:624:in `each'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.1/lib/rails/engine.rb:624:in `block in <class:Engine>'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.1/lib/rails/initializable.rb:32:in `instance_exec'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.1/lib/rails/initializable.rb:32:in `run'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.1/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.1/lib/rails/initializable.rb:50:in `each'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.1/lib/rails/initializable.rb:50:in `tsort_each_child'
  /usr/local/lib/ruby/2.6.0/tsort.rb:415:in `call'
  /usr/local/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
  /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
  /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
  /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.1/lib/rails/initializable.rb:60:in `run_initializers'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.1/lib/rails/application.rb:363:in `initialize!'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.1/lib/rails/railtie.rb:190:in `public_send'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/railties-6.0.3.1/lib/rails/railtie.rb:190:in `method_missing'
  /home/huginn/huginn/config/environment.rb:5:in `<top (required)>'
  config.ru:4:in `require_relative'
  config.ru:4:in `block in <main>'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:125:in `instance_eval'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:125:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `eval'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/unicorn-5.1.0/lib/unicorn.rb:56:in `block in builder'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:752:in `build_app!'
  /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/unicorn-5.1.0/lib/unicorn/http_server
```
