### ISSUE TITLE
Agents won't run - foreman exiting 

### ISSUE THREAD

**Issue by spencerskinner99** [huginn/huginn#3098]
Similar issue to #864 where the agents wont run at all

My docker compose it 

  ```
huginn:
    image: huginn/huginn
    container_name: huginn
    hostname: huginn
    #network_mode: "service:vpn-huginn"
    network_mode: le_bridge
    restart: unless-stopped
    ports:
       - "3004:3004"
    depends_on:
      - mariadb-huginn
      #- vpn-huginn
    environment:
      PUID: 1001
      PGID: 1001
      PORT: 3004
      HUGINN_DATABASE_NAME: "huginn" 
      HUGINN_DATABASE_USERNAME: "huginn" 
      HUGINN_DATABASE_PASSWORD: "huginn" 
      DATABASE_HOST: 192.168.2.13
      DATABASE_PORT: 3308
      INVITATION_CODE: huginn
      TIMEZONE: Europe/London

    
  mariadb-huginn:
    image: mariadb
    container_name: mariadb-huginn
    hostname: mariadb-huggin
    network_mode: le_bridge
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: huginn
      MYSQL_DATABASE: huginn
      MYSQL_USER: huginn
      MYSQL_PASSWORD: huginn
    ports:
    - 3308:3306
    volumes:
    - /Docker_Configs/webmonitor/mariadb_huggin/db:/var/lib/mysql
```

These are the start up logs for a fresh huginn container 

```
Generating random APP_SECRET_TOKEN.
1+0 records in
1+0 records out
36 bytes copied, 5.3346e-05 s, 675 kB/s
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
You are replacing the current local value of without, which is currently "test:development"
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Using rake 13.0.6
Using ace-rails-ap 2.0.1
Using concurrent-ruby 1.1.9
Using i18n 1.8.11
Using minitest 5.15.0
Using thread_safe 0.3.6
Using tzinfo 1.2.9
Using zeitwerk 2.5.3
Using activesupport 6.0.4.4
Using builder 3.2.4
Using erubi 1.10.0
Using mini_portile2 2.6.1
Using racc 1.6.0
Using nokogiri 1.12.5 (x86_64-linux)
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.13.0
Using rails-html-sanitizer 1.4.2
Using actionview 6.0.4.4
Using rack 2.2.3
Using rack-test 1.1.0
Using actionpack 6.0.4.4
Using nio4r 2.5.8
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.5
Using actioncable 6.0.4.4
Using globalid 1.0.0
Using activejob 6.0.4.4
Using activemodel 6.0.4.4
Using activerecord 6.0.4.4
Using marcel 1.0.2
Using activestorage 6.0.4.4
Using mini_mime 1.1.2
Using mail 2.7.1
Using actionmailbox 6.0.4.4
Using actionmailer 6.0.4.4
Using actiontext 6.0.4.4
Using public_suffix 4.0.6
Using addressable 2.8.0
Using jmespath 1.1.3
Using aws-sdk-core 2.2.15
Using bcrypt 3.1.16
Using msgpack 1.4.2
Using bootsnap 1.9.3
Using kaminari-core 1.1.1
Using kaminari-actionview 1.1.1
Using kaminari-activerecord 1.1.1
Using kaminari 1.1.1
Using bundler 2.3.5
Using method_source 0.9.2
Using thor 0.20.3
Using railties 6.0.4.4
Using sprockets 3.7.2
Using sprockets-rails 3.4.2
Using rails 6.0.4.4
Using bootstrap-kaminari-views 0.0.5
Using buftok 0.2.0
Using coffee-script-source 1.12.2
Using execjs 2.7.0
Using coffee-script 2.4.1
Using coffee-rails 5.0.0
Using cookiejar 0.3.2
Using daemons 1.1.9
Using declarative 0.0.20
Using delayed_job 4.1.9
Using delayed_job_active_record 4.1.4 from https://github.com/dsander/delayed_job_active_record.git (at rails6-zeitwerk@ac2dfef)
Using orm_adapter 0.5.0
Using responders 3.0.0
Using warden 1.2.8
Using devise 4.7.1
Using unf_ext 0.0.7.4
Using unf 0.1.4
Using domain_name 0.5.20170404
Using dotenv 2.0.1 from source at `vendor/gems/dotenv-2.0.1`
Using dotenv-rails 2.0.1 from source at `vendor/gems/dotenv-2.0.1`
Using hashie 3.5.7
Using multi_json 1.15.0
Using multipart-post 2.1.1
Using faraday 0.17.4
Using jwt 2.3.0
Using multi_xml 0.6.0
Using oauth2 1.4.7
Using dropbox-api 0.5.0 from https://github.com/dsander/dropbox-api.git (at 86cb7b5@86cb7b5)
Using eventmachine 1.2.7
Using em-socksify 0.3.0
Using http_parser.rb 0.6.0
Using em-http-request 1.1.2
Using equalizer 0.0.11
Using polyglot 0.3.5
Using treetop 1.6.10
Using erector 0.10.0 from https://github.com/dsander/erector.git (at rails6@821c2fa)
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Using et-orbi 1.0.9
Using ffi 1.12.2
Using ethon 0.12.0
Using evernote-thrift 1.25.1
Using oauth 0.5.8
Using evernote_oauth 0.2.3
Using faraday_middleware 0.12.2
Using sax-machine 1.3.2
Using feedjira 3.2.0
Using rb-fsevent 0.10.2
Using rb-inotify 0.9.10
Using sass-listen 4.0.0
Using sass 3.7.4
Using font-awesome-sass 4.7.0
Using forecast_io 2.0.1
Using foreman 0.63.0
Using gems 1.2.0
Using geokit 1.8.5
Using geokit-rails 2.2.0
Using gmail_xoauth 0.4.2
Using memoist 0.16.2
Using os 1.1.4
Using signet 0.16.0
Using googleauth 0.17.1
Using httpclient 2.8.3
Using trailblazer-option 0.1.2
Using uber 0.1.0
Using representable 3.1.1
Using retriable 3.1.2
Using rexml 3.2.5
Using webrick 1.7.0
Using google-apis-core 0.4.1
Using google-apis-discovery_v1 0.7.0
Using google-apis-generator 0.4.0
Using google-api-client 0.53.0
Using google-cloud-env 1.5.0
Using google-cloud-errors 1.2.0
Using google-cloud-core 1.6.0
Using google-protobuf 3.19.2 (x86_64-linux)
Using googleapis-common-protos-types 1.3.0
Using grpc 1.42.0 (x86_64-linux)
Using googleapis-common-protos 1.3.12
Using rly 0.2.3
Using google-gax 1.8.2
Using google-cloud-translate 2.3.0
Using haversine 0.3.0
Using httparty 0.14.0
Using hipchat 1.2.0
Using mimemagic 0.4.3
Using httmultiparty 0.3.16
Using http-cookie 1.0.3
Using http-form_data 1.0.1
Using http 2.1.0
Using huginn_agent 0.6.1
Using hypdf 1.0.10
Using jquery-rails 4.2.2
Using json 2.3.0
Using to_regexp 0.2.1
Using jsonpath 1.0.1
Using kgio 2.10.0
Using kramdown 2.3.1
Using libv8 7.3.492.27.1 (x86_64-linux)
Using liquid 4.0.3
Using listen 3.0.8
Using systemu 2.6.4
Using macaddr 1.7.1
Using memoizable 0.4.2
Using mime-types-data 3.2021.1115
Using mime-types 3.4.1
Using mini_magick 4.11.0
Using mini_racer 0.2.9
Using mqtt 0.3.1
Using mysql2 0.5.2
Using naught 1.1.0
Using net-ftp-list 3.2.8
Using netrc 0.11.0
Using omniauth 1.9.1
Using omniauth-oauth2 1.7.2
Using omniauth-dropbox-oauth2 0.3.0 from https://github.com/huginn/omniauth-dropbox-oauth2.git
Using omniauth-oauth 1.1.0
Using omniauth-evernote 1.2.1
Using omniauth-google-oauth2 0.8.2
Using omniauth-tumblr 1.2
Using omniauth-twitter 1.3.0
Using raindrops 0.17.0
Using rb-kqueue 0.2.4
Using rest-client 2.0.2
Using rturk 2.12.1
Using uuid 2.3.7
Using ruby-growl 4.1
Using rufus-scheduler 3.4.2
Using sassc 2.3.0
Using tilt 2.0.10
Using sassc-rails 2.1.2
Using sass-rails 6.0.0
Using select2-rails 3.5.9.3
Using simple_oauth 0.3.1
Using slack-notifier 1.0.0
Using spectrum-rails 1.3.4
Using tumblr_client 0.8.5 from https://github.com/albertsun/tumblr_client.git (at e046fe6@e046fe6)
Using twilio-ruby 5.62.0
Using twitter 5.15.0 from https://github.com/sferik/twitter.git
Using twitter-stream 0.1.15 from https://github.com/cantino/twitter-stream.git (at huginn@a80822d)
Using typhoeus 1.3.1
Using uglifier 2.7.2
Using unicorn 5.1.0
Using weibo_2 0.1.7 from https://github.com/albertsun/weibo_2.git (at master@ac38d04)
Using xmpp4r 0.5.6
Bundle complete! 110 Gemfile dependencies, 199 gems now installed.
Gems in the groups 'test' and 'development' were not installed.
Bundled gems are installed into `./vendor/bundle`
2022-03-20 23:34:54,060 INFO Included extra file "/etc/supervisor/conf.d/bootstrap.conf" during parsing
2022-03-20 23:34:54,060 INFO Included extra file "/etc/supervisor/conf.d/foreman.conf" during parsing
2022-03-20 23:34:54,060 INFO Included extra file "/etc/supervisor/conf.d/mysqld.conf" during parsing
2022-03-20 23:34:54,070 INFO RPC interface 'supervisor' initialized
2022-03-20 23:34:54,070 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-03-20 23:34:54,070 INFO supervisord started with pid 1
2022-03-20 23:34:55,075 INFO spawned: 'stdout' with pid 377
2022-03-20 23:34:55,078 INFO spawned: 'bootstrap' with pid 378
2022-03-20 23:34:55,087 INFO success: bootstrap entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-03-20 23:34:55,232 INFO spawned: 'mysqld' with pid 380
2022-03-20 23:34:56,313 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-03-20 23:34:56,313 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
bootstrap stdout | DATABASE_HOST=192.168.2.13
bootstrap stdout | Starting mysql server...
mysqld stdout | 2022-03-20T23:34:55.755762Z mysqld_safe Logging to syslog.
mysqld stdout | 2022-03-20T23:34:55.790106Z mysqld_safe Logging to '/var/log/mysql/error.log'.
mysqld stdout | 2022-03-20T23:34:56.312510Z mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
bootstrap stdout | . bootstrap stdout | . bootstrap stdout | .2022-03-20 23:35:00,376 INFO spawned: 'foreman' with pid 789
2022-03-20 23:35:00,377 INFO success: foreman entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2022-03-20 23:35:00,387 INFO exited: bootstrap (exit status 0; expected)
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | Database 'huginn' already exists
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
foreman stderr | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:38 web.1  | started with pid 826
foreman stdout | 23:35:38 jobs.1 | started with pid 828
foreman stdout | 23:35:38 web.1  | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:38 jobs.1 | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:38 jobs.1 | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:38 web.1  | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:39 jobs.1 | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:39 web.1  | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:39 jobs.1 | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:39 web.1  | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:39 jobs.1 | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:39 web.1  | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:40 web.1  | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:40 jobs.1 | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:40 jobs.1 | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:40 web.1  | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:40 jobs.1 | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:40 web.1  | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:41 jobs.1 | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:41 web.1  | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:42 jobs.1 | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:42 jobs.1 | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:42 web.1  | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:42 web.1  | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:43 jobs.1 | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:43 web.1  | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:45 jobs.1 | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:45 jobs.1 | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:45 web.1  | => Booting WEBrick
23:35:45 web.1  | => Rails 6.0.4.4 application starting in production http://0.0.0.0:3004
23:35:45 web.1  | => Run `rails server --help` for more startup options
foreman stdout | 23:35:45 web.1  | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:46 web.1  | /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
foreman stdout | 23:35:47 web.1  | [2022-03-20 23:35:47] INFO  WEBrick 1.7.0
23:35:47 web.1  | [2022-03-20 23:35:47] INFO  ruby 2.6.6 (2020-03-31) [x86_64-linux-gnu]
23:35:47 web.1  | [2022-03-20 23:35:47] INFO  WEBrick::HTTPServer#start: pid=827 port=3004
foreman stdout | 23:35:47 jobs.1 | /app/lib/huginn_scheduler.rb:141:in `+': no implicit conversion of nil into String (TypeError)
23:35:47 jobs.1 | 	from /app/lib/huginn_scheduler.rb:141:in `block in setup'
23:35:47 jobs.1 | 	from /app/lib/huginn_scheduler.rb:140:in `times'
23:35:47 jobs.1 | 	from /app/lib/huginn_scheduler.rb:140:in `setup'
foreman stdout | 23:35:47 jobs.1 | 	from /app/app/concerns/long_runnable.rb:86:in `setup!'
23:35:47 jobs.1 | 	from /app/lib/agent_runner.rb:82:in `block in run_workers'
23:35:47 jobs.1 | 	from /app/lib/agent_runner.rb:79:in `each'
23:35:47 jobs.1 | 	from /app/lib/agent_runner.rb:79:in `run_workers'
23:35:47 jobs.1 | 	from /app/lib/agent_runner.rb:39:in `run'
23:35:47 jobs.1 | 	from bin/threaded.rb:13:in `<main>'
23:35:47 jobs.1 | 	from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:62:in `load'
23:35:47 jobs.1 | 	from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:62:in `load'
23:35:47 jobs.1 | 	from /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.4.4/lib/rails/commands/runner/runner_command.rb:42:in `perform'
23:35:47 jobs.1 | 	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
23:35:47 jobs.1 | 	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
23:35:47 jobs.1 | 	from /app/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
23:35:47 jobs.1 | 	from /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.4.4/lib/rails/command/base.rb:69:in `perform'
23:35:47 jobs.1 | 	from /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.4.4/lib/rails/command.rb:46:in `invoke'
23:35:47 jobs.1 | 	from /app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.4.4/lib/rails/commands.rb:18:in `<main>'
23:35:47 jobs.1 | 	from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
23:35:47 jobs.1 | 	from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
23:35:47 jobs.1 | 	from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
23:35:47 jobs.1 | 	from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
23:35:47 jobs.1 | 	from /app/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
23:35:47 jobs.1 | 	from bin/rails:9:in `<main>'
foreman stdout | 23:35:47 jobs.1 | Starting HuginnScheduler
foreman stdout | 23:35:47 jobs.1 | exited with code 1
23:35:47 system | sending SIGTERM to all processes
foreman stdout | 23:35:47 web.1  | terminated by SIGTERM
2022-03-20 23:35:47,658 INFO exited: foreman (exit status 0; expected)

```

Best guess is foreman seems to be crashing for some reason?

**Comment by SebastianKoenig1** [comment]
Did you specify the TIMEZONE variable? I specified TIMEZONE: Europe/Berlin and removing that from my env file then run docker again solved this issue.

**Comment by spencerskinner99** [comment]
That seems to have done the trick. 

Thanks!
