### ISSUE TITLE
How to enable cookies in WebsiteAgent

### ISSUE THREAD

**Issue by 87051392** [huginn/huginn#3142]
when accessing the website,It run out this information "Cookies must be enabled in order to view this page" 

WebsiteAgent:
```
{
  "expected_update_period_in_days": "200",
  "url": "https://www.gov.il/he/api/NewsApi/Index?OfficeId=104cb0f4-d65a-4692-b590-94af928c19c0&limit=10&topic=3f9fe17e-8c90-4328-a968-b6be5f3c14da&subTopic=f2b1d480-79c0-4023-a44a-0457bfaf2268&skip=0",
  "type": "json",
  "mode": "on_change",
  "extract": {
    "title": {
      "path": "results[*].UrlName"
    }
  },
  "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
}
```

```
[00:00:00] INFO -- : Dry Run started
[00:00:00] INFO -- : Fetching https://www.gov.il/he/api/NewsApi/Index?OfficeId=104cb0f4-d65a-4692-b590-94af928c19c0&limit=10&topic=3f9fe17e-8c90-4328-a968-b6be5f3c14da&subTopic=f2b1d480-79c0-4023-a44a-0457bfaf2268&skip=0
[00:00:02] ERROR -- : Error when fetching url: 783: unexpected token at '<HTML>
<head>
<script>
Challenge=951049;
ChallengeId=231132642;
GenericErrorMessageCookies="Cookies must be enabled in order to view this page.";
</script>
<script>
function test(var1)
{
	var var_str=""+Challenge;
	var var_arr=var_str.split("");
	var LastDig=var_arr.reverse()[0];
	var minDig=var_arr.sort()[0];
	var subvar1 = (2 * (var_arr[2]))+(var_arr[1]*1);
	var subvar2 = (2 * var_arr[2])+var_arr[1];
	var my_pow=Math.pow(((var_arr[0]*1)+2),var_arr[1]);
	var x=(var1*3+subvar1)*1;
	var y=Math.cos(Math.PI*subvar2);
	var answer=x*y;
	answer-=my_pow*1;
	answer+=(minDig*1)-(LastDig*1);
	answer=answer+subvar2;
	return answer;
}
</script>
<script>
client = null;
if (window.XMLHttpRequest)
{
	var client=new XMLHttpRequest();
}
else
{
	if (window.ActiveXObject)
	{
		client = new ActiveXObject('MSXML2.XMLHTTP.3.0');
	};
}
if (!((!!client)&&(!!Math.pow)&&(!!Math.cos)&&(!![].sort)&&(!![].reverse)))
{
	document.write("Not all needed JavaScript methods are supported.<BR>");

}
else
{
	client.onreadystatechange  = function()
	{
		if(client.readyState  == 4)
		{
			var MyCookie=client.getResponseHeader("X-AA-Cookie-Value");
			if ((MyCookie == null) || (MyCookie==""))
			{
				document.write(client.responseText);
				return;
			}
			
			var cookieName = MyCookie.split('=')[0];
			if (document.cookie.indexOf(cookieName)==-1)
			{
				document.write(GenericErrorMessageCookies);
				return;
			}
			window.location.reload(true);
		}
	};
	y=test(Challenge);
	client.open("POST",window.location,true);
	client.setRequestHeader('X-AA-Challenge-ID', ChallengeId);
	client.setRequestHeader('X-AA-Challenge-Result',y);
	client.setRequestHeader('X-AA-Challenge',Challenge);
	client.setRequestHeader('Content-Type' , 'text/plain');
	client.send();
}
</script>
</head>
<body>
<noscript>JavaScript must be enabled in order to view this page.</noscript>
</body>
</HTML>'
/app/vendor/bundle/ruby/2.6.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
/app/vendor/bundle/ruby/2.6.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
/app/app/models/agents/website_agent.rb:651:in `parse'
/app/app/models/agents/website_agent.rb:423:in `handle_data'
/app/app/models/agents/website_agent.rb:404:in `block in check_url'
/app/vendor/bundle/ruby/2.6.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
/app/app/models/agents/website_agent.rb:401:in `check_url'
/app/app/models/agents/website_agent.rb:386:in `block in check_urls'
/app/app/models/agents/website_agent.rb:385:in `each'
/app/app/models/agents/website_agent.rb:385:in `check_urls'
/app/app/models/agents/website_agent.rb:379:in `check'
/app/app/concerns/sortable_events.rb:92:in `check'
/app/app/concerns/dry_runnable.rb:31:in `dry_run!'
/app/app/controllers/agents/dry_runs_controller.rb:41:in `create'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/abstract_controller/base.rb:195:in `process_action'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_controller/metal/rendering.rb:30:in `process_action'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:135:in `run_callbacks'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/abstract_controller/callbacks.rb:41:in `process_action'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_controller/metal/rescue.rb:22:in `process_action'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.4.4/lib/active_support/notifications.rb:180:in `block in instrument'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.4.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.4.4/lib/active_support/notifications.rb:180:in `instrument'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.4.4/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/abstract_controller/base.rb:136:in `process'
/app/vendor/bundle/ruby/2.6.0/gems/actionview-6.0.4.4/lib/action_view/rendering.rb:39:in `process'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_controller/metal.rb:190:in `dispatch'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_controller/metal.rb:254:in `dispatch'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/journey/router.rb:32:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/journey/router.rb:32:in `serve'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/routing/route_set.rb:834:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
/app/vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
/app/vendor/bundle/ruby/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/middleware/cookies.rb:654:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.4.4/lib/active_support/callbacks.rb:101:in `run_callbacks'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.4.4/lib/rails/rack/logger.rb:37:in `call_app'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.4.4/lib/rails/rack/logger.rb:26:in `block in call'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.4.4/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.4.4/lib/active_support/tagged_logging.rb:28:in `tagged'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.4.4/lib/active_support/tagged_logging.rb:80:in `tagged'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.4.4/lib/rails/rack/logger.rb:26:in `call'
/app/config/initializers/silence_worker_status_logger.rb:3:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/middleware/static.rb:126:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/actionpack-6.0.4.4/lib/action_dispatch/middleware/host_authorization.rb:97:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.4.4/lib/rails/engine.rb:527:in `call'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.4.4/lib/rails/railtie.rb:190:in `public_send'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.0.4.4/lib/rails/railtie.rb:190:in `method_missing'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
/app/vendor/bundle/ruby/2.6.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:140:in `service'
/app/vendor/bundle/ruby/2.6.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:96:in `run'
/app/vendor/bundle/ruby/2.6.0/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread'
[00:00:02] INFO -- : Dry Run finished
```

Is there any solutions to solve  this problem.Looking forward to your reply.

**Comment by ohingardail** [comment]
The problem is that the www.gov.il API site doesn't render up JSON directly, but uses a javascript (rendered by a client-side web browser) that provides the JSON. This seems an odd thing to do on a public JSON datastream; I suppose www.gov.il have their reasons; perhaps they want to stop public data trawling, or want to enforce a data subscription of some kind (or it might just be bad design).

You can run wget on a Unix/Linux commandline (which is basically what the Huginn Website Agent is doing), you can see the problem.
For example, here is a properly rendered JSON datastream from the UK police:
```
wget https://data.police.uk/api/forces
```
You get something like:
```
[{"id":"avon-and-somerset","name":"Avon and Somerset Constabulary"},{"id":"bedfordshire","name":"Bedfordshire Police"},{"id":"cambridgeshire","name":"Cambridgeshire Constabulary"},{"id":"cheshire","name":"Cheshire Constabulary"},{"id":"city-of-london","name":"City of London Police"},{"id":"cleveland","name":"Cleveland Police"},
: 
: 
:
```
If you do the same on the www.gov.il API, you get the HTML page you saw (not the JSON stream, which only gets rendered by a client-side javascript-enabled web browser):
```
wget https://www.gov.il/he/api/NewsApi/Index?OfficeId=104cb0f4-d65a-4692-b590-94af928c19c0&limit=10&topic=3f9fe17e-8c90-4328-a968-b6be5f3c14da&subTopic=f2b1d480-79c0-4023-a44a-0457bfaf2268&skip=0
```
You get:
```
<HTML>
<head>
<script>
Challenge=510510;
ChallengeId=250374319;
GenericErrorMessageCookies="Cookies must be enabled in order to view this page.";
:
: 
:
<noscript>JavaScript must be enabled in order to view this page.</noscript>
</body>
</HTML>
```

In other words, the Huginn Website Agent never gets to see the JSON data at all; the server-side (www.gov.il) makes sure that you can only see the JSON data via a web browser with javascript enabled. They key text is "JavaScript must be enabled in order to view this page." and not "Cookies must be enabled in order to view this page." 

My first approach would be to investigate the www.gov.il API to see if there are any options or URL parameters that present the data without javascript intermediation (I tried to look for myself, but I can't read Hebrew). Even if you can only download a plain text file with structured data in it, you can still parse it with a Huginn agent.

There is also [this](https://github.com/huginn/huginn/wiki/Browser-Emulation-using-browserless) and [this](https://github.com/huginn/huginn/wiki/Browser-Emulation-using-fulldom-server) although I've never tried either.

You could also use something like the [Selenium Webdriver](https://www.selenium.dev/documentation/webdriver/) (which is not part of Huginn) to emulate a real web browser, and pass the renedered JSON page onto Huginn.

**Comment by irfancharania** [comment]
This may help: https://github.com/huginn/huginn/wiki/Browser-Emulation-Using-PhantomJs-Cloud
