### ISSUE TITLE
Numerous timeouts using PhantomJS links

### ISSUE THREAD

**Issue by Taomyn** [huginn/huginn#3172]
I'm getting numerous timeouts when I use links generated for the PhantomJSCloud service. The links generated are fine when I test them manually but the process within Huginn more often than not time out - even a few moments after a manual test of the same link. I have 3 other agents using PhantomJSCloud and they all behave the same though they fail randomly at different times so it's quite in consistent.

The logs show:

`Fetching https://phantomjscloud.com/api/browser/v2/<my-api>/?request=%7B%22url%22%3A%22https%3A%2F%2Fhub.docker.com%2Fr%2Fhuginn%2Fhuginn%2Ftags%22%2C%22renderType%22%3A%22plainText%22%2C%22outputAsJson%22%3Atrue%2C%22requestSettings%22%3A%7B%22ignoreImages%22%3Atrue%2C%22userAgent%22%3A%22Mozilla%2F5.0%20%28X11%3B%20Linux%20x86_64%3B%20rv%3A105.0%29%20Gecko%2F20100101%20Firefox%2F105.0%22%7D%7D`

Then when it tries to fetch and parse gets:

```
Error when fetching url: execution expired (Delayed::Worker.max_run_time is only 600 seconds)
/app/vendor/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi/pointer.rb:59:in `read_string'
/app/vendor/bundle/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/easy/callbacks.rb:54:in `block in header_write_callback'
/app/vendor/bundle/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/easy/operations.rb:29:in `easy_perform'
/app/vendor/bundle/ruby/2.7.0/gems/ethon-0.12.0/lib/ethon/easy/operations.rb:29:in `perform'
/app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.3.1/lib/typhoeus/request/operations.rb:16:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.3.1/lib/typhoeus/request/cacheable.rb:18:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.3.1/lib/typhoeus/request/block_connection.rb:31:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.3.1/lib/typhoeus/request/stubbable.rb:25:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.3.1/lib/typhoeus/request/before.rb:26:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.3.1/lib/typhoeus/adapters/faraday.rb:82:in `perform_request'
/app/vendor/bundle/ruby/2.7.0/gems/typhoeus-1.3.1/lib/typhoeus/adapters/faraday.rb:72:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/gzip.rb:24:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/request/url_encoded.rb:15:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/request/multipart.rb:15:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
/app/vendor/bundle/ruby/2.7.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
/app/app/concerns/web_request_concern.rb:26:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/rack_builder.rb:143:in `build_response'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/connection.rb:387:in `run_request'
/app/vendor/bundle/ruby/2.7.0/gems/faraday-0.17.4/lib/faraday/connection.rb:138:in `get'
/app/app/models/agents/website_agent.rb:397:in `check_url'
/app/app/models/agents/website_agent.rb:386:in `block in check_urls'
/app/app/models/agents/website_agent.rb:385:in `each'
/app/app/models/agents/website_agent.rb:385:in `check_urls'
/app/app/models/agents/website_agent.rb:482:in `block in receive'
/app/app/concerns/liquid_interpolatable.rb:75:in `block (2 levels) in interpolate_with_each'
/app/app/concerns/liquid_interpolatable.rb:64:in `interpolate_with'
/app/app/concerns/liquid_interpolatable.rb:73:in `block in interpolate_with_each'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.5.1/lib/active_record/relation/delegation.rb:88:in `each'
/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.5.1/lib/active_record/relation/delegation.rb:88:in `each'
/app/app/concerns/liquid_interpolatable.rb:72:in `interpolate_with_each'
/app/app/models/agents/website_agent.rb:465:in `receive'
/app/app/concerns/sortable_events.rb:99:in `receive'
/app/app/jobs/agent_receive_job.rb:8:in `perform'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.5.1/lib/active_job/execution.rb:40:in `block in perform_now'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/i18n-1.12.0/lib/i18n.rb:322:in `with_locale'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.5.1/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.5.1/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.5.1/lib/active_job/logging.rb:25:in `block (4 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/notifications.rb:180:in `block in instrument'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/notifications.rb:180:in `instrument'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.5.1/lib/active_job/logging.rb:24:in `block (3 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.5.1/lib/active_job/logging.rb:45:in `block in tag_logger'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/tagged_logging.rb:80:in `tagged'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.5.1/lib/active_job/logging.rb:45:in `tag_logger'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.5.1/lib/active_job/logging.rb:21:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.5.1/lib/active_job/execution.rb:39:in `perform_now'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.5.1/lib/active_job/execution.rb:25:in `block in execute'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.5.1/lib/active_job/railtie.rb:43:in `block (4 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/execution_wrapper.rb:91:in `wrap'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/reloader.rb:72:in `block in wrap'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/execution_wrapper.rb:91:in `wrap'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/reloader.rb:71:in `wrap'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.5.1/lib/active_job/railtie.rb:42:in `block (3 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:121:in `instance_exec'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.5.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.5.1/lib/active_job/execution.rb:23:in `execute'
/app/vendor/bundle/ruby/2.7.0/gems/activejob-6.0.5.1/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/backend/base.rb:78:in `invoke_job'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/usr/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:230:in `block in run'
/usr/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:229:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:213:in `block in work_off'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:212:in `times'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:212:in `work_off'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/usr/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/app/vendor/bundle/ruby/2.7.0/gems/delayed_job-4.1.9/lib/delayed/worker.rb:172:in `loop'
/app/vendor/bundle/ruby/2.7.0/gems/
```

I'm using the docker version of Huginn, running on Fedora 36, and as you can see I have increased the time out to 10min which hasn't helped. This has been happening for months but has recently just got worse so I thought I should report it.

Any ideas why this is happening?

**Comment by gingerbeardman** [comment]
This is another issue that is an outstanding and ongoing bug @knu
