### ISSUE TITLE
Unable to start jobs worker : fugit fails to parse cron string "*/1 * * * * " (ArgumentError)

### ISSUE THREAD

**Issue by bit-man** [huginn/huginn#3225]
When huginn tries to start jobs worker it fails with error  **invalid cron string "*/1 * * * * " (ArgumentError)**

Filtered log output for jobs worker :
```
$ docker logs  huggin-huginn-1 | grep jobs
01:11:49 jobs.1 | started with pid 558
foreman stdout | 01:11:52 jobs.1 | /usr/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
01:11:52 jobs.1 | /app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
foreman stdout | 01:11:52 jobs.1 | /usr/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
01:11:52 jobs.1 | /app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:214: warning: previous definition of BUFSIZE was here
01:11:52 jobs.1 | /usr/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
01:11:52 jobs.1 | /app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:541: warning: previous definition of Socket was here
foreman stdout | 01:11:54 jobs.1 | /app/vendor/bundle/ruby/2.7.0/gems/fugit-1.5.2/lib/fugit/cron.rb:51:in `do_parse': invalid cron string "*/1 * * * * " (ArgumentError)
01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/rufus-scheduler-3.8.1/lib/rufus/scheduler/jobs_repeat.rb:281:in `initialize'
foreman stdout | 01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/rufus-scheduler-3.8.1/lib/rufus/scheduler.rb:712:in `new'
01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/rufus-scheduler-3.8.1/lib/rufus/scheduler.rb:712:in `do_schedule'
01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/rufus-scheduler-3.8.1/lib/rufus/scheduler.rb:226:in `cron'
01:11:54 jobs.1 | 	from /app/app/concerns/long_runnable.rb:135:in `schedule'
01:11:54 jobs.1 | 	from /app/app/concerns/long_runnable.rb:121:in `cron'
01:11:54 jobs.1 | 	from /app/lib/huginn_scheduler.rb:134:in `block in setup'
01:11:54 jobs.1 | 	from /app/lib/huginn_scheduler.rb:133:in `each'
01:11:54 jobs.1 | 	from /app/lib/huginn_scheduler.rb:133:in `setup'
01:11:54 jobs.1 | 	from /app/app/concerns/long_runnable.rb:86:in `setup!'
foreman stdout | 01:11:54 jobs.1 | 	from /app/lib/agent_runner.rb:82:in `block in run_workers'
01:11:54 jobs.1 | 	from /app/lib/agent_runner.rb:79:in `each'
01:11:54 jobs.1 | 	from /app/lib/agent_runner.rb:79:in `run_workers'
01:11:54 jobs.1 | 	from /app/lib/agent_runner.rb:39:in `run'
01:11:54 jobs.1 | 	from bin/threaded.rb:13:in `<main>'
01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:62:in `load'
foreman stdout | 01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:62:in `load'
01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/commands/runner/runner_command.rb:42:in `perform'
01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
foreman stdout | 01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/command/base.rb:69:in `perform'
01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/command.rb:46:in `invoke'
01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/commands.rb:18:in `<main>'
01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
foreman stdout | 01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
01:11:54 jobs.1 | 	from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
01:11:54 jobs.1 | 	from bin/rails:9:in `<main>'
foreman stdout | 01:11:54 jobs.1 | Starting HuginnScheduler
foreman stdout | 01:11:54 jobs.1 | exited with code 1
```

Running in docker with mutlple container linkage with MariaDB using [this docker-compose](https://gitlab.com/bit-man/the-automation-club/-/blob/106a2cd38f112411afbf7a178a6bc3af70c97281/huggin/docker-compose.yml) and [latest huginn](https://hub.docker.com/layers/huginn/huginn/latest/images/sha256-1123bb3e051b2205fdda6064a43f138fc816f46d4511aa79995085f613847024?context=explore) image at the moment of this bug report. Tested in previous images to 1 month old and same problem is found

**Comment by bit-man** [comment]
Running `bundle exec rails runner bin/threaded.rb`  inside the running container throws the same exception and stacktrace

**Comment by bit-man** [comment]
Just discovered that the `TIMEZONE=America/Argentina/Buenos_Aires` environment variable setting (not show in the previous docker-compose file) is causing the problem even that this timezone name is defined in TZinfo

```
irb(main):001:0> require 'tzinfo'
=> true
irb(main):002:0> TZInfo::Timezone.get("America/Argentina/Buenos_Aires")
=> #<TZInfo::DataTimezone: America/Argentina/Buenos_Aires>
```
When `TIMEZONE` is undefined it works ok but is not my timezone :cry: 

Also setting it to  `TIMEZONE=NONEXISTENT` fails to start huginn

```
ArgumentError: Invalid Timezone: NONEXISTENT
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/core_ext/time/zones.rb:100:in `rescue in find_zone!'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/core_ext/time/zones.rb:82:in `find_zone!'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/railtie.rb:42:in `block in <class:Railtie>'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/initializable.rb:32:in `instance_exec'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/initializable.rb:32:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/initializable.rb:60:in `run_initializers'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/application.rb:363:in `initialize!'
/app/config/environment.rb:5:in `<main>'
/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `block in require'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/dependencies.rb:324:in `require'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/application.rb:339:in `require_environment!'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/application.rb:523:in `block in run_tasks_blocks'
/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Caused by:
foreman stderr | TZInfo::InvalidTimezoneIdentifier: Invalid identifier
/app/vendor/bundle/ruby/2.7.0/gems/tzinfo-1.2.11/lib/tzinfo/zoneinfo_data_source.rb:232:in `load_timezone_info'
/app/vendor/bundle/ruby/2.7.0/gems/tzinfo-1.2.11/lib/tzinfo/timezone.rb:92:in `get'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/core_ext/time/zones.rb:89:in `find_zone!'
/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.6.1/lib/active_support/railtie.rb:42:in `block in <class:Railtie>'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/initializable.rb:32:in `instance_exec'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/initializable.rb:32:in `run'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/initializable.rb:60:in `run_initializers'
/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.6.1/lib/rails/application.rb:363:in `initialize!'
/app/config/environment.rb:5:in `<main>'
```

**Comment by jjeffers** [comment]
@bit-man a recent change to the TIMEZONE to tzinfo mapping may have fixed (https://github.com/huginn/huginn/issues/3483). Can you try latest and see if this resolved your issue?
