### ISSUE TITLE
diagrams are broken since last commits

### ISSUE THREAD

**Issue by hihouhou** [huginn/huginn#3232]
Hello,

I build a new image (like very often ) for Huginn but I saw that now diagrams are broken. about logs : 
```==> log/production.log <==
I, [2023-03-14T14:32:27.402541 #78]  INFO -- : [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX] Started GET "/diagram" for XXXXXXXXXXXX at 2023-03-14 14:32:27 +0100
I, [2023-03-14T14:32:27.403614 #78]  INFO -- : [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX] Processing by DiagramsController#show as HTML
I, [2023-03-14T14:32:27.675858 #78]  INFO -- : [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]   Rendered diagrams/show.html.erb within layouts/application (Duration: 269.8ms | Allocations: 134150)
I, [2023-03-14T14:32:27.675922 #78]  INFO -- : [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]   Rendered layout layouts/application.html.erb (Duration: 269.9ms | Allocations: 134179)
I, [2023-03-14T14:32:27.676034 #78]  INFO -- : [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX] Completed 500 Internal Server Error in 272ms (ActiveRecord: 5.9ms | Allocations: 135186)
F, [2023-03-14T14:32:27.676541 #78] FATAL -- : [XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX] ActionView::Template::Error (wrong number of arguments (given 6, expected 1..2)):
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]     22:       </div>
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]     23:
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]     24:       <div class='digraph'>
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]     25:         <%= render_agents_diagram(@agents, layout: params[:layout]) %>
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]     26:       </div>
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]     27:     </div>
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]     28:   </div>
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX] app/helpers/dot_helper.rb:30:in 'popen'
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX] app/helpers/dot_helper.rb:30:in 'dot_to_svg'
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX] app/helpers/dot_helper.rb:3:in 'render_agents_diagram'
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX] app/views/diagrams/show.html.erb:25
[XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX] config/initializers/silence_worker_status_logger.rb:3:in 'call'
```
I found a commit about app/helpers/dot_helper.rb (If it can help)

**Comment by malagebidi** [comment]
I also encountered the same problem

**Comment by krendil** [comment]
I'm encountering the same issue, using the official huginn/huginn:latest docker image with
Image digest: `huginn/huginn@sha256:217da3e6b377d888ac864a9942b53ba366edda804441d32538783915e44ce568`
Image ID: `sha256:a3059a44c9528405c90aa71fef46938f29d9124f04641da49123482e4efd32f5`
which is the most recent one at time of writing

**Comment by hihouhou** [comment]
I did a test from https://github.com/huginn/huginn/commit/ba852f1edc26bf0e87d6a7a13389124e22d0bde0 and it seems to be fixed for my test server

**Comment by hihouhou** [comment]
validated in prod with 338 agents, thank you @knu

**Comment by knu** [comment]
Ah, sorry for this!
