### ISSUE TITLE
error during manual installation with Ruby 3.2.2

### ISSUE THREAD

**Issue by rockbenben** [huginn/huginn#3261]
I manually redeployed Huginn using Ruby 3.2.2, but encountered an error when executing 'sudo bundle exec rake production:export'. 

```
root@huginn:/home/huginn/huginn# sudo bundle exec rake production:export
rake aborted!
NoMethodError: undefined method `exists?' for File:Class
/home/huginn/huginn/lib/tasks/production.rake:17:in `remove_upstart_config'
/home/huginn/huginn/lib/tasks/production.rake:26:in `block (2 levels) in <main>'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_l                                                                                                                                                     oad'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/comman                                                                                                                                                     d.rb:27:in `run'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invoca                                                                                                                                                     tion.rb:127:in `invoke_command'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392                                                                                                                                                     :in `dispatch'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.r                                                                                                                                                     b:485:in `start'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (requir                                                                                                                                                     ed)>'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `                                                                                                                                                     with_friendly_errors'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
Tasks: TOP => production:export => production:check
(See full trace by running task with --trace)
```

Additionally, the current manual deployment tutorial is for version 2.7, but it prompts an issue with the Ruby version during the execution as I changed it to below.

```
curl -L --progress-bar https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.xz | tar xJ
cd ruby-3.2.2
```

**Comment by Galoperd** [comment]
Hi, same error here. Did you solved ?

**Comment by rockbenben** [comment]
> Hi, same error here. Did you solved ?

Retain Ruby 2.7.7 while modifying the Huginn repository cloning process.

`sudo -u huginn -H git clone https://github.com/huginn/huginn.git -b latest_rubygems huginn`

**Comment by Galoperd** [comment]
solved, thank you !
