### ISSUE TITLE
Regression: Value in Trigger Agent can no longer be a list

### ISSUE THREAD

**Issue by degan6** [huginn/huginn#3292]
First, thank you for your recent work on keeping Huginn update to date! I have many agents and automations in it so its great to see more work being put in!

After updating to the latest commit, my trigger agents with lists in the `value` section fail with the error.

I narrowed it down to the following:

The JSON below does not work:

```
{
  "expected_receive_period_in_days": "2",
  "keep_event": "true",
  "rules": [
    {
      "type": "regex",
      "value": [
"gitlab"
      ],
      "path": "post.title"
    },
    "regex"
  ],
  "must_match": "1",
  "message": "<p>{{post.title}} - {{post.author}}</p><p>Date Published: {{post.date_published | date: \"%a, %b %d, %Y\" }}</p>{{post.content_html}}"
}
```

This Json does work
{
  "expected_receive_period_in_days": "2",
  "keep_event": "true",
  "rules": [
    {
      "type": "regex",
      "value": "gitlab",
      "path": "post.title"
    },
    "regex"
  ],
  "must_match": "1",
  "message": "<p>{{post.title}} - {{post.author}}</p><p>Date Published: {{post.date_published | date: \"%a, %b %d, %Y\" }}</p>{{post.content_html}}"
}

I get the error:

```
                        Validation failed: expected_receive_period_in_days, message, and rules, with a type, value, and path for every rule, are required
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activerecord-6.1.7.3/lib/active_record/validations.rb:80:in `raise_validation_error'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activerecord-6.1.7.3/lib/active_record/validations.rb:53:in `save!'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activerecord-6.1.7.3/lib/active_record/transactions.rb:302:in `block in save!'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activerecord-6.1.7.3/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activerecord-6.1.7.3/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activerecord-6.1.7.3/lib/active_record/transactions.rb:302:in `save!'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activerecord-6.1.7.3/lib/active_record/suppressor.rb:48:in `save!'
/home/huginn/huginn/app/concerns/dry_runnable.rb:73:in `save!'
/home/huginn/huginn/app/jobs/agent_receive_job.rb:10:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.3/lib/active_job/execution.rb:48:in `block in perform_now'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/i18n-1.13.0/lib/i18n.rb:322:in `with_locale'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.3/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.3/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.3/lib/active_job/instrumentation.rb:21:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `block in instrument'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.3/lib/active_job/instrumentation.rb:31:in `instrument'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.3/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.3/lib/active_job/logging.rb:22:in `block in tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/tagged_logging.rb:37:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/tagged_logging.rb:99:in `tagged'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.3/lib/active_job/logging.rb:22:in `tag_logger'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.3/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:137:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.3/lib/active_job/execution.rb:47:in `perform_now'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.3/lib/active_job/execution.rb:25:in `block in execute'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.3/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/execution_wrapper.rb:91:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/reloader.rb:72:in `block in wrap'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/execution_wrapper.rb:91:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/reloader.rb:71:in `wrap'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.3/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:137:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.3/lib/active_job/execution.rb:23:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.3/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/backend/base.rb:78:in `invoke_job'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:231:in `block (2 levels) in run'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/timeout-0.3.2/lib/timeout.rb:189:in `block in timeout'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/timeout-0.3.2/lib/timeout.rb:196:in `timeout'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:231:in `block in run'
/usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:230:in `run'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:313:in `block in reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:313:in `reserve_and_run_one_job'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:214:in `block in work_off'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:213:in `times'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:213:in `work_off'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:176:in `block (4 levels) in start'
/usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:175:in `block (3 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:174:in `block (2 levels) in start'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:173:in `loop'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:173:in `block in start'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block in add'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:172:in `start'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/command.rb:137:in `run'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/command.rb:125:in `block in run_process'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:264:in `start_proc'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/daemons-1.1.9/lib/daemons/controller.rb:73:in `run'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/command.rb:123:in `run_process'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/command.rb:98:in `daemonize'
script/delayed_job:5:in `<top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
```

**Comment by ww2283** [comment]
I feel like the regex handling could be an issue as well, after updating, my trigger agent with regex all failed. I get error message `expected_receive_period_in_days, message, and rules, with a type, value, and path for every rule, are required`

**Comment by knu** [comment]
I see, validation rules for the `value` key were made too strict in 583a3c26.  I'll fix it.

**Comment by degan6** [comment]
@knu Thank you for getting this fixed so quickly!
