### ISSUE TITLE
Huginn Installation Issue

### ISSUE THREAD

**Issue by weir1** [huginn/huginn#3305]
I am stuck here guys from yesterday

`:~/huginn$ sudo bundle exec rake production:export
Stopping huginn ...
ok: down: huginn-web-1: 0s, normally up
Exporting new services ...
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/export/base.rb:133:in `block in export_template': undefined method `exists?' for File:Class (NoMethodError)

      File.read(matchers.detect { |m| File.exists?(m) })
                                          ^^^^^^^^
Did you mean?  exist?
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/export/base.rb:133:in `each'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/export/base.rb:133:in `detect'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/export/base.rb:133:in `export_template'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/export/base.rb:139:in `write_template'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/export/runit.rb:19:in `block (2 levels) in export'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/export/runit.rb:12:in `upto'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/export/runit.rb:12:in `block in export'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/engine.rb:252:in `block in each_process'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/engine.rb:251:in `each'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/engine.rb:251:in `each_process'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/export/runit.rb:11:in `export'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/cli.rb:62:in `export'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/vendor/thor/lib/thor/command.rb:27:in `run'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/vendor/thor/lib/thor.rb:369:in `dispatch'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/lib/foreman/vendor/thor/lib/thor/base.rb:444:in `start'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bundler/gems/foreman-a5f9b78fa5cf/bin/foreman:7:in `<top (required)>'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bin/foreman:25:in `load'
        from /home/huginn/huginn/vendor/bundle/ruby/3.2.0/bin/foreman:25:in `<main>'
rake aborted!
'foreman export runit -a huginn -l /home/huginn/huginn/log /etc/service' exited with a non-zero return value: [foreman export] creating: huginn-web-1
[foreman export] creating: huginn-web-1/env
[foreman export] creating: huginn-web-1/log
/home/huginn/huginn/lib/tasks/production.rake:85:in `run'
/home/huginn/huginn/lib/tasks/production.rake:60:in `block (2 levels) in <main>'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `load'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/exec.rb:23:in `run'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:492:in `exec'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/home/huginn/huginn/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
Tasks: TOP => production:export
(See full trace by running task with --trace)
`

**Comment by weir1** [comment]
I have resolved this issue finally
removed that extra s manually
install bundle with non root account

again stuck with socket issue
give appropriate permission
stopped unicorn file & kill all the process after that restarted again

voila
