### ISSUE TITLE
Can't install huginn with Operation not permitted (ThreadError)

### ISSUE THREAD

**Issue by tortoo** [huginn/huginn#3325]
After executing the command: 
```
docker run --name huginn \             
        --restart=always \
    --link PostgreSQL:postgres \
    -p 3000:3000 \
    -e HUGINN_DATABASE_USERNAME=huginn \
    -e HUGINN_DATABASE_PASSWORD=huginn \
    -e HUGINN_DATABASE_ADAPTER=postgresql \
    huginn/huginn
```
It gave this: 
```
Unable to find image 'huginn/huginn:latest' locally
latest: Pulling from huginn/huginn
2ab09b027e7f: Pull complete 
234c8a12fd0f: Pull complete 
fd8d6c82661d: Pull complete 
4f4fb700ef54: Pull complete 
185725d1c187: Pull complete 
e0232f33baed: Pull complete 
96974ca220be: Pull complete 
1bfd9afa7b73: Pull complete 
a58989011754: Pull complete 
695d90d833e0: Pull complete 
070190d2f575: Pull complete 
dc43042a683c: Pull complete 
3e2bb704855c: Pull complete 
21c35905194c: Pull complete 
5da032b4c3a2: Pull complete 
966953169a06: Pull complete 
5654de3d29e6: Pull complete 
0bcba159360e: Pull complete 
1179016d4496: Pull complete 
1b8896b7c6a9: Pull complete 
418757e0947e: Pull complete 
fd16e04a2981: Pull complete 
b188261be0fc: Pull complete 
ae8dbe2909f5: Pull complete 
b529b757e053: Pull complete 
d3dd8d7a37ed: Pull complete 
f88d76f1f523: Pull complete 
b34f56b3ed9a: Pull complete 
13ded963dad2: Pull complete 
Digest: sha256:dbe871597d43232add81d1adfc5ad9f5cf9dcb5e1f1ba3d669598c20b96ab6c1
Status: Downloaded newer image for huginn/huginn:latest
Generating random APP_SECRET_TOKEN.
1+0 records in
1+0 records out
36 bytes copied, 0.000200975 s, 179 kB/s
You are replacing the current local value of without, which is currently "test:development"
/usr/local/lib/ruby/3.2.0/open3.rb:223:in `detach': can't create Thread: Operation not permitted (ThreadError)
        from /usr/local/lib/ruby/3.2.0/open3.rb:223:in `popen_run'
        from /usr/local/lib/ruby/3.2.0/open3.rb:103:in `popen3'
        from /usr/local/lib/ruby/3.2.0/open3.rb:290:in `capture3'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/source/git/git_proxy.rb:342:in `block in capture'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/shared_helpers.rb:70:in `with_clean_git_env'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/source/git/git_proxy.rb:340:in `capture'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/source/git/git_proxy.rb:258:in `git'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/source/git/git_proxy.rb:87:in `full_version'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/env.rb:78:in `git_version'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/env.rb:116:in `environment'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/env.rb:17:in `report'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:71:in `request_issue_report_for'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:50:in `log_error'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:123:in `rescue in with_friendly_errors'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:115:in `with_friendly_errors'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
/app/vendor/bundle/ruby/3.2.0/gems/timeout-0.3.2/lib/timeout.rb:101:in `initialize': can't create Thread: Operation not permitted (ThreadError)
        from /app/vendor/bundle/ruby/3.2.0/gems/timeout-0.3.2/lib/timeout.rb:101:in `new'
        from /app/vendor/bundle/ruby/3.2.0/gems/timeout-0.3.2/lib/timeout.rb:101:in `create_timeout_thread'
        from /app/vendor/bundle/ruby/3.2.0/gems/timeout-0.3.2/lib/timeout.rb:134:in `block in ensure_timeout_thread_created'
        from /app/vendor/bundle/ruby/3.2.0/gems/timeout-0.3.2/lib/timeout.rb:132:in `synchronize'
        from /app/vendor/bundle/ruby/3.2.0/gems/timeout-0.3.2/lib/timeout.rb:132:in `ensure_timeout_thread_created'
        from /app/vendor/bundle/ruby/3.2.0/gems/timeout-0.3.2/lib/timeout.rb:181:in `timeout'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1269:in `connect'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1248:in `do_start'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1243:in `start'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:657:in `start'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:597:in `connection_for'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:870:in `request'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/fetcher/downloader.rb:63:in `request'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/fetcher/downloader.rb:19:in `fetch'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/fetcher/compact_index.rb:124:in `call'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/compact_index_client/updater.rb:47:in `update'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/compact_index_client.rb:92:in `update'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/compact_index_client.rb:79:in `update_and_parse_checksums!'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/fetcher/compact_index.rb:68:in `available?'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/fetcher/compact_index.rb:15:in `call'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/fetcher/compact_index.rb:15:in `block in compact_index_request'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/fetcher.rb:158:in `use_api'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:392:in `block in api_fetchers'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:392:in `select'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:392:in `api_fetchers'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:397:in `block in remote_specs'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/index.rb:9:in `build'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:396:in `remote_specs'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:129:in `specs'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/lazy_specification.rb:82:in `materialize_for_installation'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/spec_set.rb:205:in `map!'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/spec_set.rb:205:in `specs_for_dependency'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/spec_set.rb:34:in `block in for'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/spec_set.rb:22:in `loop'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/spec_set.rb:22:in `for'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/spec_set.rb:85:in `materialize'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/definition.rb:507:in `materialize'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/definition.rb:197:in `specs'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/installer.rb:231:in `ensure_specs_are_compatible!'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/installer.rb:83:in `block in run'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/process_lock.rb:12:in `block in lock'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/process_lock.rb:9:in `open'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/process_lock.rb:9:in `lock'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/installer.rb:71:in `run'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/installer.rb:23:in `install'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli/install.rb:62:in `run'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:261:in `block in install'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/settings.rb:131:in `temporary'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:260:in `install'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:34:in `dispatch'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/cli.rb:28:in `start'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/exe/bundle:45:in `block in <top (required)>'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /app/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.12/exe/bundle:33:in `<top (required)>'
        from /usr/local/bin/bundle:25:in `load'
        from /usr/local/bin/bundle:25:in `<main>'
```
Found the other two similar issue #3174 and #3098. But it’s not the same, don’t know what to do.

**Comment by tortoo** [comment]
After adding the `--privileged` option in `docker run` command the installation goes smoothly. But this doesn't seem safe. Some people solved this [here](https://stackoverflow.com/questions/76703987/rabbitmq-docker-failed-to-create-thread-operation-not-permitted-1) with docker version update. I checked my version and it's 19.03.15. You can see by executing `apt-cache madison docker-ce` that it should be the latest stable version. My system is Debian 9. So is there any better solution?

**Comment by tortoo** [comment]
After updating Debian 9 to 10 the docker stable version was changed to 24.0.6. Docker prompt the following at the end: 
```
To run Docker as a non-privileged user, consider setting up the Docker daemon in rootless mode for your user:
    dockerd-rootless-setuptool.sh install

Visit https://docs.docker.com/go/rootless/ to learn about rootless mode.
To run the Docker daemon as a fully privileged service, but granting non-root users access, refer to https://docs.docker.com/go/daemon-access/

WARNING: Access to the remote API on a privileged Docker daemon is equivalent to root access on the host. Refer to the 'Docker daemon attack surface' documentation for details: https://docs.docker.com/go/attack-surface/
```

The huginn installIton went well with no `--privileged` option.
Slightly different is after executing `docker ps` the `PORTS` shows `0.0.0.0:3000->3000/tcp, :::3000->3000/tcp` rather than only `0.0.0.0:3000->3000/tcp` on another Debian 9 server which was deployed two years ago.
