### ISSUE TITLE
Configure secure SMTP

### ISSUE THREAD

**Issue by smgermano** [huginn/huginn#3362]
Hi, newby in huginn using docker on ARM, i just try to get my first agent with notification. This configuration on .envfile:
  
SMTP_DOMAIN=gmail.com
SMTP_USER_NAME=onemail@gmail.com
SMTP_PASSWORD=***
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_SSL=false

// Set to true to send real emails via SMTP when running in the development Rails environment.
// Set to false to have emails intercepted in development and displayed at http://localhost:3000/letter_opener
SEND_EMAIL_IN_DEVELOPMENT=true

I get this error on agent: "Username and Password not accepted
[error.txt](https://github.com/huginn/huginn/files/14564554/error.txt)
"

I can't enable "Less secure app" from google account

https://support.google.com/accounts/answer/6010255?hl=en&visit_id=638457871964006258-1717832900&p=less-secure-apps&rd=1

"Starting in Fall of 2024, less secure apps, third-party apps, or devices that have you sign in with only your username and password will no longer be supported for Google Workspace accounts. For exact dates, visit Google Workspace Updates.To continue to use a specific app with your Google Account, you’ll need to use a more secure type of access that doesn’t share password data..  Learn how to use Sign in with Google."

Someone has another way of configure SMTP for huginn ? Maybe secure way?

**Comment by smgermano** [comment]
Hi @virtadpt, thanks for replying,

You are right, is just a gmail address, not gmail server. So, I tried SMTP_DOMAIN=smtp.gmail.com, and rebuild container 

But same error: "SMTP_DOMAIN to "                        535-5.7.8 Username and Password not accepted. For more information, go to
/usr/lib/ruby/2.5.0/net/smtp.rb:981:in `check_auth_response'
/usr/lib/ruby/2.5.0/net/smtp.rb:736:in `auth_plain'
/usr/lib/ruby/2.5.0/net/smtp.rb:728:in `authenticate'
/usr/lib/ruby/2.5.0/net/smtp.rb:565:in `do_start'
/usr/lib/ruby/2.5.0/net/smtp.rb:518:in `start'
..."

Two factors auth. on gmail is necessary ?

**Comment by smgermano** [comment]
Hi again, seems works using now with an account with two factor authentication and app password: 
seeing this thread:
[](https://github.com/huginn/huginn/issues/2699)

```
to:	admin@example.com
date:	Mar 12, 2024, 3:43 PM
subject:	You have some notifications!
mailed-by:	gmail.com

```
Needs adjustments: about "admin@example.com"

Thanks!

**Comment by smgermano** [comment]
Resolved
