### ISSUE TITLE
SMTP no longer works without auth since PR#3398

### ISSUE THREAD

**Issue by michalmiddleton** [huginn/huginn#3415]
Hi @knu 
This PR https://github.com/huginn/huginn/pull/3398 broke sending emails without auth for me. 
I assume it's related to the net-smtp update.

My SMTP configuration:
```yaml
  - name: EMAIL_FROM_ADDRESS
    value: me@###.com
  - name: SMTP_DOMAIN
    value: ###.com
  - name: SMTP_USER_NAME
    value: none
  - name: SMTP_SERVER
    value: "192.168.#.#"
  - name: SMTP_PORT
    value: "25"
  - name: SMTP_ENABLE_STARTTLS_AUTO
    value: "false"
```

Docker tags:
- last working tag: `66dd4eded3dc48c3ca6aa3a902c8023d48097c13`
- broken in: `62c18822d614db94748e378d1c725ac8ccbb89f2`

Error I get:
```log
                        SMTP-AUTH requested but missing user name
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp/authenticator.rb:20:in `check_args'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:884:in `check_auth_args'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:669:in `do_start'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:642:in `start'
/app/vendor/bundle/ruby/3.2.0/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/app/vendor/bundle/ruby/3.2.0/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/app/vendor/bundle/ruby/3.2.0/gems/mail-2.8.1/lib/mail/message.rb:2145:in `do_delivery'
/app/vendor/bundle/ruby/3.2.0/gems/mail-2.8.1/lib/mail/message.rb:253:in `block in deliver'
/app/vendor/bundle/ruby/3.2.0/gems/actionmailer-6.1.7.7/lib/action_mailer/base.rb:559:in `block in deliver_mail'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `block in instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/actionmailer-6.1.7.7/lib/action_mailer/base.rb:557:in `deliver_mail'
/app/vendor/bundle/ruby/3.2.0/gems/mail-2.8.1/lib/mail/message.rb:253:in `deliver'
/app/vendor/bundle/ruby/3.2.0/gems/actionmailer-6.1.7.7/lib/action_mailer/message_delivery.rb:119:in `block in deliver_now'
/app/vendor/bundle/ruby/3.2.0/gems/actionmailer-6.1.7.7/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/app/vendor/bundle/ruby/3.2.0/gems/actionmailer-6.1.7.7/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
/app/app/models/agents/email_agent.rb:59:in `block (2 levels) in receive'
/app/app/models/agents/email_agent.rb:50:in `each'
/app/app/models/agents/email_agent.rb:50:in `block in receive'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-6.1.7.7/lib/active_record/relation/delegation.rb:88:in `each'
/app/vendor/bundle/ruby/3.2.0/gems/activerecord-6.1.7.7/lib/active_record/relation/delegation.rb:88:in `each'
/app/app/models/agents/email_agent.rb:49:in `receive'
/app/app/jobs/agent_receive_job.rb:8:in `perform'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.7/lib/active_job/execution.rb:48:in `block in perform_now'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/i18n-1.14.4/lib/i18n.rb:322:in `with_locale'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.7/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.7/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.7/lib/active_job/instrumentation.rb:21:in `block in instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `block in instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/notifications.rb:203:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.7/lib/active_job/instrumentation.rb:31:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.7/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.7/lib/active_job/logging.rb:22:in `block in tag_logger'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/tagged_logging.rb:37:in `tagged'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/tagged_logging.rb:99:in `tagged'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.7/lib/active_job/logging.rb:22:in `tag_logger'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.7/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:137:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.7/lib/active_job/execution.rb:47:in `perform_now'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.7/lib/active_job/execution.rb:25:in `block in execute'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.7/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/execution_wrapper.rb:91:in `wrap'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/reloader.rb:72:in `block in wrap'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/execution_wrapper.rb:91:in `wrap'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/reloader.rb:71:in `wrap'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.7/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.7/lib/active_support/callbacks.rb:137:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.7/lib/active_job/execution.rb:23:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.7/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/backend/base.rb:78:in `invoke_job'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:231:in `block (2 levels) in run'
/app/vendor/bundle/ruby/3.2.0/gems/timeout-0.4.1/lib/timeout.rb:186:in `block in timeout'
/app/vendor/bundle/ruby/3.2.0/gems/timeout-0.4.1/lib/timeout.rb:193:in `timeout'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:231:in `block in run'
/usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:230:in `run'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:313:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:313:in `reserve_and_run_one_job'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:214:in `block in work_off'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:213:in `times'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:213:in `work_off'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:176:in `block (4 levels) in start'
/usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:175:in `block (3 levels) in start'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:174:in `block (2 levels) in start'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:173:in `loop'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:173:in `block in start'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block in add'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:172:in `start'
/app/lib/delayed_job_worker.rb:6:in `run'
/app/app/concerns/long_runnable.rb:71:in `block in run!'
```

**Comment by Bootta11** [comment]
Im also unable to configure smtp. 

Here is my env:
`EMAIL_FROM_ADDRESS=huginn@my-sandbox-name.mailgun.org
SMTP_DOMAIN=my-sandbox-name.mailgun.org
SMTP_USER_NAME=postmaster@my-sandbox-name.mailgun.org
SMTP_PASSWORD=my-mailgun-smtp-password
SMTP_SERVER=smtp.mailgun.org
SMTP_PORT=587
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
SEND_EMAIL_IN_DEVELOPMENT=true`

I start huginn in docker:

`sudo docker run -d --restart always -p "127.0.0.1:3000:3000" --env-file ./.env --name huginn ghcr.io/huginn/huginn`

Here are Email Agent options: 

`{
  "subject": "You have a notification!",
  "headline": "Your notification:",
  "expected_receive_period_in_days": "2",
  "recipients": [
    "my.mail@gmail.com"
  ]
}`

Can someone help?

**Comment by knu** [comment]
Sorry for the trouble.  This must be the problem between net-smtp 0.5.0 and gmail_xoauth 0.4.2.  I'll update gmail_xoauth shortly.
https://github.com/huginn/huginn/pull/3417

**Comment by newton-wi** [comment]
Hello,
Unfortunately, still does not seem to work.
I run tag 989873668ab8c3a9fc072452ed7e8908cbc3b35c.

In the past it worked when I had set "SMTP_USER_NAME=none".
With that I get "Exception during receive. SMTP-AUTH requested but missing user name".

I've seen config/initializers/action_mailer.rb that it should be possible to set "SMTP_AUTHENTICATION=none".
With that I get "Exception during receive. 503 AUTH command used when not advertised".

Without any auth related env var set (only EMAIL_FROM_ADDRES,  SMTP_DOMAIN, SMTP_PORT, SMTP_SERVER as in all tries) I get: "Exception during receive. 503 AUTH command used when not advertised".

Best Regards,

Michael

**Comment by knu** [comment]
SMTP servers without authentication are very rare nowadays.  Explicitly specifying `SMTP_AUTHENTICATION=none` is the way to go.

**Comment by knu** [comment]
As you can see, the ActionMailer config specifies the "plain" authentication method by default, and there could have been some change in rails or net/smtp that led to send AUTH even if the user name is not given.

**Comment by newton-wi** [comment]
Please note, that "SMTP_AUTHENTICATION=none" is not sufficient for me, I need to set that AND "SMTP_USER_NAME=none" to get it working.

Disclaimer: This is NOT to nitpick about that, I can very well live with that, it is about to let others know how to get their setup fixed should they experience the same.

**Comment by knu** [comment]
Would that be because the default `.env` has `SMTP_USER_NAME=you@gmail.com` in it?  If that's the case, we should probably remove the default mail settings from `.env` to avoid confusion.

**Comment by newton-wi** [comment]
If I delete both SMTP_USER_NAME and SMTP_PASSWORD from .env (and restart foreman) it works, so yes, deleting that vars from .env might avoid confusion.

**Comment by knu** [comment]
The above PR explicitly handles the case where SMTP_USER_NAME is `none` and disables authentication.
