### ISSUE TITLE
Unable to send mail - lots of Ruby "block" messages !?

### ISSUE THREAD

**Issue by nodecentral** [huginn/huginn#3444]
Hi, I have seen a number of issues raised about the difficult some people face when trying to send email via Huginn, and having tried many of them - and with there seemingly no other way to troubleshoot then keep updating the environment file - I'm posting my log messages here as no matter what I change I keep getting what looks like the same error message...

My SMTP environment settings are as follows, but please keep in mind I've tried multiples so it's not reflective of every attempt. I have also checked the details, and used the username/password/server/port via an SSL LUA script I wrote, so I seem to have the key attributes, I just can't seem to get them in the right place?

Any help would be appreciated

````
      - SMTP_DOMAIN=mydomain.com
      - SMTP_USER_NAME=my.name@mydomain.com
      - SMTP_PASSWORD="taznas-ertytd-sunky0"
      - SMTP_SERVER=smtp.ionos.co.uk
      - SMTP_PORT=465
      - SMTP_AUTHENTICATION=plain
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_SSL=false
      - SEND_EMAIL_IN_DEVELOPMENT=true
````
And the error is below.
````
                        end of file reached
/app/vendor/bundle/ruby/3.2.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:237:in `rbuf_fill'
/app/vendor/bundle/ruby/3.2.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:199:in `readuntil'
/app/vendor/bundle/ruby/3.2.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:209:in `readline'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:1017:in `recv_response'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:676:in `block in do_start'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:1027:in `critical'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:676:in `do_start'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:642:in `start'
/app/vendor/bundle/ruby/3.2.0/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/app/vendor/bundle/ruby/3.2.0/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/app/vendor/bundle/ruby/3.2.0/gems/mail-2.8.1/lib/mail/message.rb:2145:in `do_delivery'
/app/vendor/bundle/ruby/3.2.0/gems/mail-2.8.1/lib/mail/message.rb:253:in `block in deliver'
/app/vendor/bundle/ruby/3.2.0/gems/actionmailer-6.1.7.8/lib/action_mailer/base.rb:559:in `block in deliver_mail'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `block in instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/actionmailer-6.1.7.8/lib/action_mailer/base.rb:557:in `deliver_mail'
/app/vendor/bundle/ruby/3.2.0/gems/mail-2.8.1/lib/mail/message.rb:253:in `deliver'
/app/vendor/bundle/ruby/3.2.0/gems/actionmailer-6.1.7.8/lib/action_mailer/message_delivery.rb:119:in `block in deliver_now'
/app/vendor/bundle/ruby/3.2.0/gems/actionmailer-6.1.7.8/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/app/vendor/bundle/ruby/3.2.0/gems/actionmailer-6.1.7.8/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
/app/app/models/agents/email_digest_agent.rb:62:in `block in check'
/app/app/models/agents/email_digest_agent.rb:54:in `each'
/app/app/models/agents/email_digest_agent.rb:54:in `check'
/app/app/jobs/agent_check_job.rb:7:in `perform'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/execution.rb:48:in `block in perform_now'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/i18n-1.14.4/lib/i18n.rb:322:in `with_locale'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/instrumentation.rb:21:in `block in instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `block in instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/instrumentation.rb:31:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/logging.rb:22:in `block in tag_logger'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/tagged_logging.rb:37:in `tagged'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/tagged_logging.rb:99:in `tagged'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/logging.rb:22:in `tag_logger'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:137:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/execution.rb:47:in `perform_now'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/execution.rb:25:in `block in execute'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/execution_wrapper.rb:91:in `wrap'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/reloader.rb:72:in `block in wrap'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/execution_wrapper.rb:91:in `wrap'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/reloader.rb:71:in `wrap'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:137:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/execution.rb:23:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/backend/base.rb:78:in `invoke_job'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:231:in `block (2 levels) in run'
/app/vendor/bundle/ruby/3.2.0/gems/timeout-0.4.1/lib/timeout.rb:186:in `block in timeout'
/app/vendor/bundle/ruby/3.2.0/gems/timeout-0.4.1/lib/timeout.rb:193:in `timeout'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:231:in `block in run'
/usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:230:in `run'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:313:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:313:in `reserve_and_run_one_job'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:214:in `block in work_off'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:213:in `times'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:213:in `work_off'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:176:in `block (4 levels) in start'
/usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:175:in `block (3 levels) in start'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:174:in `block (2 levels) in start'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:173:in `loop'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:173:in `block in start'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block in add'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:172:in `start'
/app/lib/delayed_job_worker.rb:6:in `run'
/app/app/concerns/long_runnable.rb:71:in `block in run!'
````

**Comment by AI-nsley69** [comment]
Same issue here.

Running Huginn through Docker with the latest image from ghcr:

```
                        end of file reached
/app/vendor/bundle/ruby/3.2.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:237:in `rbuf_fill'
/app/vendor/bundle/ruby/3.2.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:199:in `readuntil'
/app/vendor/bundle/ruby/3.2.0/gems/net-protocol-0.2.2/lib/net/protocol.rb:209:in `readline'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:1017:in `recv_response'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:1008:in `block in getok'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:1027:in `critical'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:1006:in `getok'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:986:in `quit'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:732:in `do_finish'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:645:in `ensure in start'
/app/vendor/bundle/ruby/3.2.0/gems/net-smtp-0.5.0/lib/net/smtp.rb:645:in `start'
/app/vendor/bundle/ruby/3.2.0/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/app/vendor/bundle/ruby/3.2.0/gems/mail-2.8.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/app/vendor/bundle/ruby/3.2.0/gems/mail-2.8.1/lib/mail/message.rb:2145:in `do_delivery'
/app/vendor/bundle/ruby/3.2.0/gems/mail-2.8.1/lib/mail/message.rb:253:in `block in deliver'
/app/vendor/bundle/ruby/3.2.0/gems/actionmailer-6.1.7.8/lib/action_mailer/base.rb:559:in `block in deliver_mail'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `block in instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/actionmailer-6.1.7.8/lib/action_mailer/base.rb:557:in `deliver_mail'
/app/vendor/bundle/ruby/3.2.0/gems/mail-2.8.1/lib/mail/message.rb:253:in `deliver'
/app/vendor/bundle/ruby/3.2.0/gems/actionmailer-6.1.7.8/lib/action_mailer/message_delivery.rb:119:in `block in deliver_now'
/app/vendor/bundle/ruby/3.2.0/gems/actionmailer-6.1.7.8/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/app/vendor/bundle/ruby/3.2.0/gems/actionmailer-6.1.7.8/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
/app/app/models/agents/email_digest_agent.rb:62:in `block in check'
/app/app/models/agents/email_digest_agent.rb:54:in `each'
/app/app/models/agents/email_digest_agent.rb:54:in `check'
/app/app/jobs/agent_check_job.rb:7:in `perform'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/execution.rb:48:in `block in perform_now'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/i18n-1.14.4/lib/i18n.rb:322:in `with_locale'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/instrumentation.rb:21:in `block in instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `block in instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/notifications.rb:203:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/instrumentation.rb:31:in `instrument'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/logging.rb:22:in `block in tag_logger'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/tagged_logging.rb:37:in `tagged'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/tagged_logging.rb:99:in `tagged'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/logging.rb:22:in `tag_logger'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:137:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/execution.rb:47:in `perform_now'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/execution.rb:25:in `block in execute'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/execution_wrapper.rb:91:in `wrap'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/reloader.rb:72:in `block in wrap'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/execution_wrapper.rb:91:in `wrap'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/reloader.rb:71:in `wrap'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `instance_exec'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activesupport-6.1.7.8/lib/active_support/callbacks.rb:137:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/execution.rb:23:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/activejob-6.1.7.8/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/backend/base.rb:78:in `invoke_job'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:231:in `block (2 levels) in run'
/app/vendor/bundle/ruby/3.2.0/gems/timeout-0.4.1/lib/timeout.rb:186:in `block in timeout'
/app/vendor/bundle/ruby/3.2.0/gems/timeout-0.4.1/lib/timeout.rb:193:in `timeout'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:231:in `block in run'
/usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:230:in `run'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:313:in `block in reserve_and_run_one_job'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:313:in `reserve_and_run_one_job'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:214:in `block in work_off'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:213:in `times'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:213:in `work_off'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:176:in `block (4 levels) in start'
/usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:175:in `block (3 levels) in start'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:174:in `block (2 levels) in start'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:173:in `loop'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:173:in `block in start'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block in add'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/app/vendor/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/worker.rb:172:in `start'
/app/lib/delayed_job_worker.rb:6:in `run'
/app/app/concerns/long_runnable.rb:71:in `block in run!'
```

Docker compose:
```
services:
    huginn:
        image: ghcr.io/huginn/huginn:latest
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - 3000:3000
        environment:
          - SMTP_DOMAIN=mydomain.com
          - SMTP_SERVER=smtp.zoho.eu
          - SMTP_PORT=587
          - SMTP_USER_NAME=user@mydomain.com
          - SMTP_PASSWORD=password

volumes:
    mysql-data:
```

I know for a fact that my email does not [contain special characters](https://github.com/huginn/huginn/wiki/SMTP-passwords-with-special-characters-need-to-be-surrounded-by-quotes) and have also tried to put the password in quotes, just incase.
